cvmfs/catalog_mgr_rw.cc, cvmfs/file_processing/file.h, cvmfs/pathspec/pathspec_pattern.cc, cvmfs/sql_impl.h, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_sync.cc, cvmfs/upload_facility.h, test/unittests/t_catalog_traversal.cc, test/unittests/t_history.cc, test/unittests/testutil.cc, test/unittests/testutil.h
Nothing catastrophic... However, some fixes that prevent potential segfaults in error states are nice to have. I'm always amazed what kind of things Coverity digs out of the code, like:
> check_return: Calling `FetchRow` without checking return value *(as is done elsewhere 43 out of 45 times)*.
or 
> Null-checking `manifest` suggests that it may be **null**, but it has already been dereferenced on all paths leading to the check.
=> Fix: Coverity Warnings

cvmfs/catalog_mgr_rw.cc, cvmfs/file_processing/file.h, cvmfs/pathspec/pathspec_pattern.cc, cvmfs/sql_impl.h, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_sync.cc, cvmfs/upload_facility.h, test/unittests/t_catalog_traversal.cc, test/unittests/t_history.cc, test/unittests/testutil.cc, test/unittests/testutil.h
This uses the `UniquePtr<>` in the `Database::Open()` and `Database::Create()` methods removing facilitating the error handling of those methods. Additionally a null pointer check was added for `Database::Open()`.
**Note:** This is based on [Fix: Coverity Warnings](https://github.com/cvmfs/cvmfs/pull/654).
=> Refactor: Database::Create and ::Open() use UniquePtr<>

cvmfs/download.cc, test/unittests/t_download.cc
Fix the destination_mem.size field of the JobInfo struct.
=> FIX: download of local files into memory

cvmfs/catalog_traversal.h, cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/object_fetcher.h, cvmfs/swissknife_history.cc, cvmfs/upload_facility.h, cvmfs/upload_local.cc, cvmfs/upload_local.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h, cvmfs/util.h, cvmfs/util_concurrency.h, cvmfs/util_concurrency_impl.h, test/unittests/t_callbacks.cc, test/unittests/t_catalog_traversal.cc, test/unittests/t_file_processing.cc, test/unittests/t_garbage_collector.cc, test/unittests/t_object_fetcher.cc, test/unittests/t_upload_facility.cc, test/unittests/t_util_concurrency.cc, test/unittests/testutil.h
I'd define a dependent type as a type that is dependent on a class template parameter. In the case below, `Foo<T>::VectorTN` would be a dependent type in `Foo<>` and can be used as:
```C++
template<typename T>
class Foo {
public:
typedef std::vector<T> VectorTN;
};
int main() {
typedef Foo<int> FooInt;
FooInt foo;
FooInt::VectorTN foo_int_vector;
return 0;
}
```
Instead of writing `dependent_type_name_t` for a dependent type this changes the convention to `DependentTypeNameTN` to comply with the naming convention, that types must be CamelCase. Hope that I caught all of them...
=> FIX: Dependent Type Naming Convention

test/unittests/t_catalog_traversal.cc, test/unittests/t_garbage_collector.cc
Apparently GCC 4.8 doesn't care about that...
=> FIX: Compile Errors due to Misplaced Typename

cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, test/unittests/t_garbage_collector.cc
This disentangles things in the garbage collector a bit and removes an experimental solution to the 'orphaned named snapshot' problem. We leave this particular thing as a known issue for later.
=> Refactor: GarbageCollector<> Extensibility Preparations

add-ons/tools/download_catalog_graph.py
This is a (quick and dirty) script that downloads the entire catalog graph of a given repository.
=> Add Script to Download Complete Catalog Graph

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_traversal.h, cvmfs/history.h, cvmfs/history_sqlite.cc, cvmfs/history_sqlite.h, cvmfs/object_fetcher.h, cvmfs/sql.h, cvmfs/sql_impl.h, cvmfs/util.h, test/unittests/t_object_fetcher.cc, test/unittests/t_sqlite_database.cc, test/unittests/t_unlink_guard.cc, test/unittests/testutil.cc, test/unittests/testutil.h
This add an auto-manage functionality to the `Database<>` class that unlinks the underlying SQLite file when the database is destructed. By default, this  feature is disabled (legacy compatibility) but it exposes an API to control it:
```C++
void Database<>::TakeFileOwnership();
void Database<>::DropFileOwnership();
void Database<>::OwnsFile();
```
The `ObjectFetcher<>` is hiding the file dependency of `Catalog` and `History` objects. Hence if returned by `ObjectFetcher<>` they have the auto-management enabled by default for convenience. If the using code of `ObjectFetcher<>` wishes to manage the database file manually, both `Catalog` and `History` expose a facade API for controlling the underlying database:
```C++
void History::TakeDatabaseFileOwnership();
void …
```
=> FIX: ObjectFetcher<> Leaks Temporary Files

test/unittests/t_dns.cc, test/unittests/t_uuid.cc
This fixes a couple of compiler warnings in `t_uuid.cc` and `t_dns.cc`. Googletest is pedantic when it comes to type safe comparisons. Furthermore I replaced some `assert()` calls by googletest's `ASSERT_TRUE()` with the advantage that this fails only the current test and doesn't kill the `cvmfs_unittests` binary entirely.
Some general remarks to the usage of googletest that I've seen in the code base:
* `ASSERT_EQ(<expected>, <actual>)` --> The first parameter is the expected value!
* `ASSERT_TRUE(a == b)` is bad practise, because there is an `ASSERT_EQ()`
=> FIX: Compiler Warnings in t_uuid.cc and t_dns.cc

cvmfs/cvmfs_server, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, cvmfs/upload_facility.cc, cvmfs/upload_spooler_definition.cc, cvmfs/upload_spooler_definition.h
This is related to [CVM-703](https://sft.its.cern.ch/jira/browse/CVM-703) and allows to configure the number of maximal concurrent writes in the `server.conf` using `CVMFS_MAXIMAL_CONCURRENT_WRITES=...`. However, I would not sell this as a real feature, yet. It configures the maximal number of upload jobs in the queue rather than actual concurrency. At least for the local uploader (into POSIX based backends) there is no real write concurrency right now. S3 does a better job with the cURL multi API, I believe.
Anyway, it doesn't hurt to have this configurable. We'll anyway need to have a deeper look into optimising the write backend so real concurrency, async I/O or similar is left to be implemented...
=> Feature: Configure Maximal Concurrent Upload Count

cvmfs/cvmfs_server
Removes an accidentally added debug print from `cvmfs_server`.
=> FIX: Remove Unintentional Debug Print

cvmfs/cache.cc, cvmfs/cache.h, cvmfs/catalog_mgr.h, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h
This fixes a problem with the catalog handling during publish. Temporary files for downloaded, opened and committed catalogs were not cleaned up properly. I've reused the auto-cleanup feature implemented [earlier this week](https://github.com/cvmfs/cvmfs/pull/667) to take care of opened writable catalogs. Besides that, committed (and compressed) catalog files needed to be treated asynchronously in a callback.
=> Fix: Leaked Temporary Catalog Files during Publish

cvmfs/s3fanout.cc
Cherry-picked a missing commit from Seppo to fix the proper setting of HTTP verbs in curl handles. This fixes a problem with the garbage collection in conjunction with the S3 backend. (Thanks for the hint on that, @ssheikki).
=> FIX: Always set Correct HTTP Verb

cvmfs/cvmfs_server, test/src/578-automaticgarbagecollection/main, test/src/580-automaticgarbagecollectionstratum1/main
This (optionally) runs the automatic garbage collection after `cvmfs_server snapshot` fetched new revisions from the stratum 0. Additionally there is an integration test to verify the behaviour.
=> Feature: Automatic Garbage Collection in `cvmfs_server snapshot`

cvmfs/cvmfs_server, cvmfs/swissknife_gc.cc
This fixes a problem with the automatic garbage collection in `cvmfs_server snapshot` when the replication has an alias name. Furthermore it contains some minor logging improvements.
=> Fix: Garbage Collection in cvmfs_server snapshot

cvmfs/cvmfs_server, test/src/536-healthcheck/main, test/src/582-autorepairmountpoints/main
We've seen the stratum 0 repository mount and transaction state get out of sync in certain occasions. CernVM-FS 2.1.19 was able to detect that inconsistency but didn't recover from it ([CVM-650](https://sft.its.cern.ch/jira/browse/CVM-650)). This extends the health check to automatically mount the repository's mount points as expected by the transaction state. Using the configuration variable `CVMFS_AUTO_REPAIR_MOUNTPOINT` one can disable this repair mechanism and go back to the same behaviour as 2.1.19.
There is one more health check making sure that the stored base hash is equal to the currently mounted hash. I will take care of that one in an independent pull request.
Additionally this contains adaptions to the previous health check test case (536) which makes use of the …
=> Feature: Auto Recover Mountpoints

cvmfs/sql.h, cvmfs/sql_impl.h, test/unittests/t_sqlite_database.cc
This fixes the 'sporadic SQL insert failure' that showed up in some unit test cases. There is a convenience method `Sql::Bind<>()` that binds a specific value to an internal SQLite query placeholder and uses template parameter deduction to figure out which concrete `Sql::Bind...()` method to use (f.e. `BindInteger()`, `BindDouble()`, ...). For `std::string` it was using `BindText()` which just binds a pointer to the internal string buffer. This is fine for strings that stay around until `Sql::Execute()` is called on the same query object. Hence, it was causing undefined behaviour when using `Sql::Bind<>()` with temporary strings like:
```C++
const int bar = 1337;
Sql q(db, "INSERT INTO foo (:bar);")
q->Bind(1, "foo" + StringifyInt(bar)); // binding a temporary (resulted in undefined …
```
=> Fix: Memory Error in Sql::Bind<>

test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh
This disables the garbage collection integration tests 577 and 579 that both check for orphaned named snapshot deletion scenarios. This is a minor known issue of the garbage collection as freezed for CernVM-FS 2.1.20.
=> TEST: Disable Integration Tests 577 and 579

cvmfs/cvmfs_server, test/src/580-automaticgarbagecollectionstratum1/main, test/test_functions
This allows to use `cvmfs_server add-replica -z` to create a stratum 1 that runs the garbage collection after every `cvmfs_server snapshot`. As a default `CVMFS_GC_TIMESTAMP_THRESHOLD` is set to *3 days ago*. Furthermore this contains a minor fix for `cvmfs_server gc` that had a shell quotation flaw after another recent Pull Request.
Also integration test 580 is adapted to use the new `cvmfs_server add-replica -z` switch and to check the generated configuration file more strictly.
=> Fix: cvmfs_server add-replica -z to enable automatic garbage collection

cvmfs/cvmfs_server, test/src/578-automaticgarbagecollection/main, test/src/580-automaticgarbagecollectionstratum1/main
As @DrDaveD correctly pointed out, `CVMFS_GARBAGE_COLLECTION=true` is not necessary on stratum 1 as this information is already embedded in the manifest file put together and signed by stratum 0. Therefore, this makes `CVMFS_GARBAGE_COLLECTION` a stratum-0-only configuration variable and takes only the *.cvmfspublished* file into account on stratum 1. Furthermore this renames `CVMFS_GC_TIMESTAMP_THRESHOLD` to `CVMFS_AUTO_GC_TIMESPAN` for better usability.
=> Fix: Rename Timestamp Threshold and Remove CVMFS_GARBAGE_COLLECTION from Stratum 1

test/cloud_testing/platforms/slc6_x86_64_test.sh
This is a follow up of "[TEST: Disable Integration Tests 577 and 579](https://github.com/cvmfs/cvmfs/pull/692)". I forgot to disable them for the S3 based test cases as well.
=> TEST: Disable Failing Tests 577 and 579 for S3

test/unittests/testutil.cc
Turns out, that the `mktime()` function seems to react non-deterministic for semi-correct inputs. First, the [documentation](http://www.cplusplus.com/reference/ctime/tm/) says, that `tm_mon` needs to be from 0 to 11 (January == 0) and furthermore I specified the `tm_isdst` 'daylight saving time' flag. This seems to fix some unit tests that failed occasionally (not always) on SLC6 x64.... Enjoy the little things!
=> FIX: mktime Produced Non-Deterministic Results on SL6

cvmfs/cvmfs_server
`cvmfs_server mkfs -z` would produce a repository that has garbage collection and auto-tagging enabled. This would produce a warning message, that auto-tagging might obstruct the garbage collection. If there is a tag created for each published revision, the garbage collection will not remove anything. The resulting repository is sane though, and potentially people might want to have just that behaviour. Also one can always change this configuration and/or delete already generated auto-tags. Therefore I decided to just make this a warning instead of an error.
=> Feature: Print Warning If AUTO_TAG and GC are Enabled

test/src/580-automaticgarbagecollectionstratum1/main
Since integration test 580 tests the behaviour of time based automatic garbage collection, it is inherently dependent on the runtime of the test case. Unfortunately this is highly unpredictable. I hope to mitigate the race condition effect a bit with this patch... Try and error, mostly :(
=> FIX: Integration Test 580 - Race Mitigation

cvmfs/cvmfs_server
This is a minor fix to the stratum 1 migration routine to be utilised for legacy 2.1.19 stratum 1s. What was missing is the addition of `CVMFS_STRATUM1=<url>` that was introduced with 2.1.20 to fully support the S3 backend.
=> Fix: Stratum1 Migration Routine

cvmfs/cvmfs_server, test/src/582-autorepairmountpoints/main
This extends the automatic repair feature that came with [Feature: Auto Recover Mountpoints](https://github.com/cvmfs/cvmfs/pull/689).
Most significantly this now refuses to tamper with repositories currently in a transaction. Instead, it suggests to use `cvmfs_server abort` that goes ahead and automatically repairs the out-of-sync mountpoints together with aborting the currently active transaction. This is a safe guard against bogus transactions potentially causing arbitrary damage by being published.
Furthermore, this patch now allows for the automatic repair of out-of-sync mounted repositories with differing mounted root hash and latest published root hash. These auto-repair features directly tackle the known issue and manual repair steps described …
=> Feature: Automatic Mountpoint Repair on Stratum0

test/migration_tests/001-hotpatch/main, test/migration_tests/common.sh
This fixes more quirks in the migration test. Namely, that `dpkg` cannot erase packages based on their *provides* field. We first need to figure out which actual package *provides* `cvmfs-config`. Furthermore in `checksum_large_files()` waiting for the background processes was flawed and didn't work.
Merging myself, to start a new test run...
=> FIX: Migration Test (again)

cvmfs/history_sql.cc, cvmfs/history_sql.h, test/unittests/t_history.cc
When opening a legacy history database file in read-only mode, the database is not automagically migrated to the newest schema. Unfortunately the code was not prepared to handle older database schemas and failed due to missing database fields. (Fixes [CVM-762](https://sft.its.cern.ch/jira/browse/CVM-762) - thanks for reporting @DrDaveD).
Additionally this adds some regression tests to ensure the bug stays fixed.
=> Fix: Reading of Legacy History Databases

cvmfs/sql.h, cvmfs/sql_impl.h
Since `sqlite::Database<>` used `sqlite3_close()` to close a database handle that was opened with `sqlite3_open_v2()` it failed. Unfortunately the failing happened silently, essentially leaking file descriptors. This uses `sqlite3_close_v2()` and does some debug error checking on the function.
=> Fix: Properly Close Database Files

test/unittests/t_object_fetcher.cc
Googletest is pretty pedantic... apparently to a different extent on various platforms...
=> FIX: Compiler Warning in t_object_fetcher.cc

cvmfs/dns.h, cvmfs/download.cc, test/src/052-roundrobindns/main, test/unittests/t_dns.cc
At least VMware Fusion, possibly other clients too, have problems connecting to IPv6 servers. Hence IPv4 addresses are preferred if available.
=> Fix IP resolving: prefer IPv4 over IPv6

cvmfs/cvmfs_server, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h
This allows to opt-out of the blocking behaviour of `cvmfs_server snapshot`. By default it will detect if a snapshot is currently running and wait for it to finish. When run as `cvmfs_server snapshot -t` it will not wait but fail with an error code instead.
=> Feature: Non-Blocking Snapshot on Stratum 1

test/migration_tests/001-hotpatch/main, test/migration_tests/common.sh
Seems that OpenStack at CERN does not properly configure the IPv6 setup by default. However CernVM-FS 2.1.19 uses IPv6 as the preferred protocol and might fail to mount repositories under these circumstances. This adds code to (temporarily) disable IPv6 while running the migration test.
Furthermore this contains a fix to allow the installation of multiple packages with the helper function `install_packages()` (formerly known as `install_package()`.
=> Fix: Migration Test

test/src/541-preloadcache/main
The test case works now (on my dev machine at least). However, these are changes I did to the test yesterday already. In particular it adds a proper `cleanup()` trap in case something goes wrong.
=> TEST: Adding cleanup() to Preload Test

test/unittests/t_smallhash.cc
Heute back ich, morgen brau ich und übermorgen caste ich die Königin auf `int`. ;-)
=> FIX: Plain C Cast Produces Warnings

cvmfs/cvmfs_server, cvmfs/swissknife_history.cc
Turns out, that `CVMFS_HASH_ALGORITHM` is not mandatory to be set in the server configuration and might be empty. Added a default for this setting.
Furthermore this reverses the order of tag listing (cf. `cvmfs_server tag -l`) for the human readable tag list.
=> Fix: CVMFS_HASH_ALGORITHM is Optional + List Tags in Reverse Chronological Order

test/migration_tests/001-hotpatch/main, test/migration_tests/common.sh
I am eventually getting to it, I believe. It now uses `sudo` for the checksumming, because many files reported *Permission Denied*. Furthermore I saw an occasion, that `get_providing_packages()` returns more than one result (namely `cvmfs-config-cern` and `cvmfs-config-egi`). Even though this should not happen anymore now, I believe its better to account for it. And finally removing packages with `apt-get` uses `purge` instead of `remove` to get rid of as many traces as possible.
=> Fix: Another Round of Migration Test Fixes

test/migration_tests/001-hotpatch/main, test/migration_tests/001-hotpatch/tarsum
Hopefully this way of checking the content of the generated tar archives is more resilient.
=> FIX: TAR Checksumming in Migration Test

cvmfs/catalog_sql.cc, test/src/554-defragcatalogrowid/main, test/test_functions
This replaces the - pretty inefficient and complex - SQL statement compacting the *rowid* field of the *catalog* SQLite table in catalog files. Furthermore it adds an additional check to the integration test 554 making sure that the *rowid* is dense after this transformation has run.
=> Fix: Inefficient Defragmentation SQL Query

test/src/580-automaticgarbagecollectionstratum1/main
This mitigates a potential race in integration test 580. The test will take longer but hopefully won't fail due to too slow publishing and time steered garbage collection anymore....
=> FIX: Mitigate Race in Integration Test 580

cvmfs/catalog_sql.cc, cvmfs/sql.cc, test/src/553-defragcatalog/main
The [recently implemented optimisation](https://github.com/cvmfs/cvmfs/pull/727) of the catalog defragmentation query was flawed. The *chunks* table has a foreign key into the *catalog* table. Therefore, the - intermediate - sweeping of the *catalog* table caused a foreign key violation. I fixed it by temporarily disabling the foreign key checks in SQLite (`PRAGMA foreign_keys = OFF`). Furthermore I added a large file to the catalog defragmentation integration test (553) to actively check for this problem.
=> Fix: Catalog Defragmentation

cvmfs/catalog_traversal.h, test/unittests/t_catalog_traversal.cc
While running the GC manually on *cvm-cmstest01* I needed to interrupt it using CTRL+C. Afterwards it turned out, that the garbage collection was not properly reentrant. The second run failed when trying to download a nested catalog, because (presumably) I interrupted it while sweeping a nested catalog tree.
`CatalogTraversal` already allows to ignore load-failures of root catalogs. This was to support consecutive garbage collection runs. However, to make GC fully reentrant (also for interrupted runs) it needs to ignore nested catalog load failures as well. I changed the behaviour of `CatalogTraversal` accordingly and added another unit test to verify the proper functionality.
=> Fix: Reentrant Garbage Collection

test/cloud_testing/platforms/slc6_x86_64_test.sh, test/wiremock_wrapper.sh
Seems that `wiremock` needs a considerable amount of time to start up as a background service. The proxy-failover integration test case (572) fails occasionally because it tries to mount the CernVM-FS client through `wiremock` before it came up properly and fails. Java... ;-)
Furthermore the same test case is disabled for the S3 tests, because it relies on a local backend.
=> Fix: Proxy Failover Test

test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_setup.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_setup.sh, test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_test.sh, test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_setup.sh, test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_test.sh, test/cloud_testing/platforms/slc6_x86_64-NFS_setup.sh, test/cloud_testing/platforms/slc6_x86_64-NFS_test.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/migration_tests/common.sh
This adds a partition for `/var/lib/cvmfs`. It seems that the migration test fails on SLC 5 and 6 because the cache partition runs full. Furthermore this disables the migration test on CentOS 7, because there is no package of CernVM-FS 2.1.19 for it. Keeping my fingers crossed...
=> Fix: Migration Test on SLC5 and SLC6

test/cloud_testing/platforms/slc5_i386_setup.sh, test/cloud_testing/platforms/slc5_i386_test.sh, test/cloud_testing/platforms/slc5_x86_64_setup.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_i386_setup.sh, test/cloud_testing/platforms/slc6_i386_test.sh, test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_setup.sh, test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_test.sh, test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_setup.sh, test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_test.sh, test/cloud_testing/platforms/slc6_x86_64-NFS_setup.sh, test/cloud_testing/platforms/slc6_x86_64-NFS_test.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh
This reverts the partition management [merged yesterday](https://github.com/cvmfs/cvmfs/pull/735) because it caused problems.
Now, we create a single partition on the SLC5/6 32bit machines and those SLC6 64bit machines that are used to test special CernVM-FS configurations and mount it to `/var/lib/cvmfs`. On the ordinary SLC5/6 x64 machines this client cache directory is bind-mounted to the partition accommodating the local backend storage of the server tests. Simply symlinking the `/var/lib/cvmfs` directory didn't work, because the symlink is removed when the CernVM-FS rpm is uninstalled.
=> Fix: Partition Management on Cloud Testing Instances

cvmfs/swissknife_pull.cc
This aborts `cvmfs_server snapshot` by default if another `cvmfs_server snapshot` is currently running an initial snapshot of the repository. This addresses the behaviour Dave was asking for in [CVM-278](https://sft.its.cern.ch/jira/browse/CVM-278). To be honest, I am not sure why an initial snapshot does not pull any historic revisions but `cvmfs_server` is implemented like this.
=> Feature: Don't Wait for Initial Snapshots

cvmfs/cvmfs_server, test/src/557-basicgarbagecollect/main, test/src/558-garbagecollectnestedcatalogs/main, test/src/559-garbagecollectnamedtags/main, test/src/560-garbagecollectpreservehistory/main, test/src/561-garbagecollectmultihash/main, test/src/563-garbagecollectlegacy/main, test/src/573-garbagecollecttimestamp/main, test/src/574-garbagecollecttimestampwithtags/main, test/src/576-garbagecollectstratum1/main, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/578-automaticgarbagecollection/main, test/src/579-garbagecollectstratum1legacytag/main, test/src/580-automaticgarbagecollectionstratum1/main, test/src/581-snapshotgarbagecollectedrepo/main, test/test_functions
This adds the configuration variable `CVMFS_AUTO_GC` that enables the automatic garbage collection both for `cvmfs_server publish` and `cvmfs_server snapshot`. Eventually Dave [convinced me](https://github.com/cvmfs/cvmfs/pull/686) that this is the clearer way to configure the automatic garbage collection. Furthermore `CVMFS_AUTO_GC_TIMESPAN` becomes an optional parameter that defaults to *3 days ago* if not set. 
Also this places a comment in integration tests 577 and 579 to mark the line where they are supposed to break until the 'orphaned revision issue' is solved.
=> Feature: Dedicated Configuration Variable for Automatic Garbage Collection 

cvmfs/cvmfs_server
This checks the parsability value of `$CVMFS_AUTO_GC_TIMESPAN` *before* running anything. This is mainly a UX fix...
=> FIX: Check AUTO_GC_TIMESPAN in a Sanity Check

cvmfs/cvmfs_server, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, test/src/584-interleavingsnapshot/main
This fixes a potential race in `cvmfs_server snapshot` where an automatic garbage collection could still be running while a cron job could start a new snapshot already. With a certain possibility this could lead to files being removed just after they have been snapshotted.
Fix in short: The snapshotting lock maintained by `cvmfs_swissknife` was ported into the `cvmfs_server` script.
The automatic garbage collection in `cvmfs_server publish` is not affected by this, since we can use the common *transaction* mechanism to shield mutex concurrent invocations from each other.
Furthermore this contains an integration test case that checks the proper functionality of the `cvmfs_server snapshot` locking mechanism as well as the `cvmfs_server snapshot -t` flag to abort a snapshot instead of …
=> Fix: Race between Automatic Garbage Collection and Consecutive Snapshots

cvmfs/cvmfs_server
This fixes a variable name mistake in `cvmfs_server snapshot` that was detected by the failing integration test 550.
=> FIX: Mistaken Variable Name in `cvmfs_server snapshot`

test/test_functions
This mitigates a problem in the integration test driver that showed up on CentOS 7 where it didn't wait long enough for the umount of the previous test setup. I increased the timeout from five seconds to one minute. This should drastically decrease the probability to produce a false-fail during test case setup.
=> Fix: Test Driver Inadvertently Failing Test Case Setup

test/cloud_testing/platforms/slc6_x86_64_test.sh
This test does not fail on S3 but it doesn't use the S3 interface, since migration is only supported on local backends for now. Hence there is no point of running this test in the S3 test set.
=> Test: Disable Corrupt Legacy Repo Migration on S3

cvmfs/upload_s3.cc
This is a cherry-pick of the configuration typo fix [pushed](https://github.com/cvmfs/cvmfs/pull/747) by @ssheikki earlier today. I additionally changed the associated error message.
=> Fix: S3 Configuration Variable Typo

test/cloud_testing/platforms/slc6_x86_64_test.sh
These tests work with the S3 configuration but they do not interact with S3 what so ever.
=> TEST: Disable S3 Tests 563 and 583

test/src/516-createsnapshotadvanced/main, test/src/521-createmultiplesnapshots/main
This is done to take care of read access rights. Some binaries in `/bin` might not be readable by *sftnight*.
=> FIX: Use `cp_bin` Helper Instead of `cp -R /bin`

test/src/544-cvmfsdirtab/main, test/src/566-dirtabrecreatenested/main, test/test_functions
Same problem [as before](https://github.com/cvmfs/cvmfs/pull/753), but with `/usr/bin/*`. This is not critical but just to be sure.
=> Fix: Read Permission Problems when Copying from /usr/bin/*

python/cvmfs/catalog.py, python/cvmfs/history.py, python/cvmfs/manifest.py
This allows to directly open `Manifest`, `Catalog` or `History` from a local file using the python library like this:
```python
import cvmfs
catalog  = cvmfs.Catalog.open("/tmp/downloaded_catalog_fileC")
history  = cvmfs.History.open("/tmp/emailed_history_fileH")
manifest = cvmfs.Manifest.open("/srv/cvmfs/test.cern.ch/.cvmfspublished")
```
=> Python: Open Catalog, Manifest and History From a File

mount/domain.d/egi.eu.conf, mount/domain.d/opensciencegrid.org.conf, packaging/rpm/cvmfs-config-default.spec
There are less than 3 (2, actually) stratum 1s on both egi.eu and opensciencegrid.org that don't yet support the geo api, so we can set CVMFS_USE_GEOAPI=yes. 
In addition, the BNL URL in opensciencegrid.org.conf was missing http://.
=> Add use of geoapi to egi.eu and opensciencegrid.org, and correct BNL stratum 1 URL

ci/build_deb.sh, ci/build_rpm.sh, ci/common.sh
This contains scripts to automate the build of both *Debian* and *RPM* packages. In case of the *RPM* build script I just overhauled the old `makerpm.sh` used in EC. Furthermore it incorporates the `makedist.sh` as a utility functions.
Both scripts expect exactly the same command line parameters and should be usable independently from Jenkins:
```bash
build_???.sh <CernVM-FS source directory> <build result location> [<nightly build number>]
```
When no *nightly build number* is given, it will create release package versions, otherwise nightly builds will be created.
=> CI: Package Build Scripts for Debian and RPM

cvmfs/smallhash.h, test/unittests/t_async_reader.cc, test/unittests/t_atomic.cc, test/unittests/t_blocking_counter.cc, test/unittests/t_chunk_detectors.cc, test/unittests/t_file_processing.cc, test/unittests/t_file_sandbox.cc, test/unittests/t_hash_filters.cc, test/unittests/t_history.cc, test/unittests/t_lru.cc, test/unittests/t_object_fetcher.cc, test/unittests/t_smallhash.cc, test/unittests/t_sqlite_database.cc, test/unittests/t_synchronizing_counter.cc, test/unittests/t_upload_facility.cc, test/unittests/t_uploaders.cc
This appends the suffix *Slow* to unit tests that would usually run longer than two seconds. Using this, one can easily filter out these test cases with `cvmfs_unittests --gtest_filter='-*Slow'` and bring the unit test suite runtime down to about one minute.
I was taking a sample from a usual test run of the complete suite. These are the tests that have been disabled:
* T_Atomic.
*  ConcurrentTransactionalAssignmentsSlow
*  ConcurrentWriteOfAtomicIntsSlow
* T_Smallhash.
*  InsertAndCopyMd5Slow
*  MultihashCycleSlow
* T_ChunkDetectors.
*  StaticOffsetChunkDetectorSlow
*  Xor32ChunkDetectorSlow
* T_UploadFacility.
*  CallbacksSlow
* T_Uploaders/0.  # TypeParam = upload::S3Uploader
*  UploadHugeFileSlow
*  UploadManyFilesSlow
*  MultipleStreamedUploadSlow
* T_Uploaders/1.  # TypeParam = …
=> TEST: Disable 62 Slow Unit Tests

.gitignore
Eclipse generates in the root folder the following files and directories, which have been added to the .gitignore:
- .metadata/
- .settings/
- .RemoteSystemsTempFiles/
=> Changes in gitignore

cvmfs/cvmfs.cc, cvmfs/loader.cc, cvmfs/loader.h, cvmfs/options.cc, cvmfs/options.h, cvmfs/talk.cc, cvmfs/talk.h, cvmfs/upload_s3.cc, mount/mount.cvmfs.cc, test/unittests/CMakeLists.txt, test/unittests/t_options.cc
Changed the `namespace options` into the `class OptionsManager` and the derived classes `FastOptionsManager` and `BashOptionsManager`. We have just created a unique pull request since it was too complicated to split the changes.
=> Refactor options

ci/README.md
Follow up of previous [Pull Request](https://github.com/cvmfs/cvmfs/pull/803). Documentation that becomes outdated after less than one hour... O.o
=> Doc: Adapt Documentation to Script Rename

cvmfs/s3fanout.cc
The file size given to curl is now of type curl_off_t. Without this typecast SingleStreamed S3 unit test fails on SLC5 and ARM targets.
=> Fix: typecasts for S3 content length header added

add-ons/tools/download_catalog_graph.py, python/cvmfs/_common.py
This adds the possibility to easily save CernVM-FS repository objects to local disk both compressed and uncompressed by using `CompressedObject::save_to()` or `CompressedObject::save_uncompressed_to()`. Furthermore it updates *add-ons/tools/download_catalog_graph.py* to use this method and fixes the same script to append the 'C' suffix to downloaded files.
=> Python: Allow to Store Objects Uncompressed

packaging/rpm/cvmfs-universal.spec
Seems that the SLC4 RPM build requires those files in the cvmfs-unittests RPM as well. When processing the building of this RPM, `rpmbuild` crashes with the complaint that those files are installed by not packaged...
=> FIX: Add %doc Files to cvmfs_unittests RPM

cvmfs/swissknife_sync.cc, test/src/586-dirtabslashasterisk/main
This fixes a problem reported by @DrDaveD causing `cvmfs_swissknife dirtab` to crash if the `.cvmfsdirtab` file contains `/*`. The root cause was a filtering check to rule out the `.` and `..` directories from the dirtab application rules. The check is done using `std::substr` but unfortunately in the wrong order resulting in `"/.".substr(3)` and a crash.
=> Fix: /* in .cvmfsdirtab Causes Crash

cvmfs/cvmfs_server
This fixes some minor things to resurrect the OverlayFS support in the CernVM-FS server. Some things seemed to have changed in the OverlayFS implementation since it went into upstream:
* Kernel module is called `overlay` instead of `overlayfs`
* Same with file system type name
* OverlayFS now requires a `workdir` along with the `upperdir` and `lowerdir`
=> FIX: Upstream OverlayFS Integration 

cvmfs/cvmfs_server
This adapts `cvmfs_server` to deal with systemd to steer `apache`. Furthermore it contains a couple of minor adaptions to be compatible to CentOS 7. Most notably CentOS 7 does not expose an `/selinux` file system interface to inspect SELinux. Hence `cvmfs_server` now uses the standard tools `sestatus` and `getenforce` which probably makes more sense anyway.
These changes need proper multi-platform testing, of course. :o)
This Pull Request is based on [FIX: Upstream OverlayFS Integration](https://github.com/cvmfs/cvmfs/pull/832).
=> Feature: Systemd Awareness of cvmfs_server

cvmfs/cvmfs_server
With this both `cvmfs_server mkfs` and `cvmfs_server import` can automatically detect which (and if) a supported union file system is installed on the system and use it. For the moment AUFS gets the preference if both OverlayFS and AUFS are available.
This Pull Request is based on [FIX: Upstream OverlayFS Integration](https://github.com/cvmfs/cvmfs/pull/832) and [Feature: Systemd Awareness of cvmfs_server](https://github.com/cvmfs/cvmfs/pull/833).
=> Feature: Auto-Detect Installed Union File System

test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/centos7_x86_64_test.sh, test/test_functions
No magic here. The manipulating calls for `autofs` and `httpd` were already abstracted, just adding a conditional for `systemd` based systems.
=> TEST: Adding systemd Awareness to the Integration Test System

test/test_functions
This removes the default value (*aufs*) of the `CVMFS_TEST_UNIONFS` environment variable. Instead, this variable is optional now and leaves the decision to `cvmfs_server`. The integration test cases for the CernVM-FS server can now simply run on CentOS 7.1 and automagically pick up the `overlayfs` technical preview.
*Note:* This Pull Request is based on [TEST: Adding systemd Awareness to the Integration Test System](https://github.com/cvmfs/cvmfs/pull/839).
=> TEST: Allow Easy Testing of OverlayFS Based Server

test/cloud_testing/platforms/common_setup.sh, test/cloud_testing/platforms/common_test.sh
For some reason all generated log files needed to be specified multiple times in different scripts. This consolidates the log files into a common log file directory where arbitrary log files can be put.
=> TEST: Simplify Logfile Management in Cloud Tests

packaging/debian/cvmfs/control
This builds the `cvmfs_server` package on ubuntu for 32bit systems as well.
=> FIX: Allow cvmfs_server.deb Building

test/run.sh, test/test_functions
This allows the `run.sh` integration test runner to generate an XUnit compliant XML output that can be used by Jenkins to generate convenient test reports.
Features:
* Overview of passed and failed tests
* Failed tests attach their log output to the XML (easy accessibility in Jenkins)
* Measurement of test execution time in milliseconds
* Historic overview of test results in Jenkins
Sneak peek of Jenkins output for failed, skipped and succeeded integration and unit tests combined:
=> TEST: Integration Test Runner can Export XUnit XML

test/run.sh, test/test_functions
This allows a finer grained test case selection in `run.sh` like this:
```bash
./run.sh -o output.xml -x src/001* src/002* -- src/0*
```
The above line would run all client integration test except number 001 and 002. Before it was only possible to *either* provide an exclusion list *or* a test list.
Furthermore it contains minor fixes in the xUnit export code.
=> TEST: Finer Grained Integration Test Selection

test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/common_test.sh, test/cloud_testing/platforms/slc5_i386_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_i386_test.sh, test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_test.sh, test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_test.sh, test/cloud_testing/platforms/slc6_x86_64-NFS_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh
This changes the cloud test scripts in the following way:
* Produce xUnit XML outputs for unit tests and integration tests
* Split integration tests into *client* and *server* test runs
* Produce xUnit XML for S3 server tests (currently only on SLC6 x86_64)
* Enable server integration tests on CentOS 7 (OverlayFS - many failures expected)
* Enable migration tests on CentOS 7
* Automatically pick up new migration tests
Furthermore this contains minor script improvements in the cloud test scripts and builds on top of [TEST: Finer Grained Integration Test Selection](https://github.com/cvmfs/cvmfs/pull/846).
=> TEST: xUnit Output in Cloud Tests + CentOS 7 Server Tests

test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh
After introducing Ubuntu 12.04 LTS as a test platform it turned out that it contains an AUFS version that is vulnerable to the kernel deadlock problem and hence needs the [workaround](http://cernvm.cern.ch/portal/cvmfs/workaround-krnl-deadlock). The test machine got stuck as expected after `cvmfs_server` reported the potential problem. So at least our warning was triggered as expected.
This should fix the problem by introducing a custom Ubuntu 12.04 cloud test run script that puts the workaround in place before running the server test cases.
=> FIX: Ubuntu 12.04 Needs the AUFS Kernel Deadlock Workaround

test/migration_tests/001-hotpatch/main
CernVM-FS 2.1.20 introduced the new `cvmfs-config-*` packages which replaced `cvmfs-keys`. The hotpatch migration test cases needed to take that into account. Now, as CernVM-FS 2.1.20 has been released, the migration test case must forget about `cvmfs-keys` and `cvmfs-config-*` entirely as this is supposed to be handled by `yum` respectively `apt-get` again.
=> TEST: Migration Test Adaptions for 2.1.20 to 2.1.21

test/unittests/t_xattr.cc
The unit test `T_Xattr.CreateFromFile` failed on some platforms because it assumes that a new file doesn't have any extended attributes yet which is not always the case. For example on CentOS there seems to be a *security.selinux* attribute by default.
I've added a helper method to count the number of extended attributes for a given path. Furthermore the patch changes the prefix of the created temporary file from `/tmp/cvmfs-test` to `/tmp/cvmfs_ut_xattr`. I use this convention in other places as well to keep the namespace in `/tmp` clean and to be able to backtrack orphaned files to its owners.
=> FIX: Unit Test for eXtended Attributes from File

test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh
Seems that OverlayFS suffers from the same problem as old AUFS versions. :-( This adds the [kernel deadlock workaround](http://cernvm.cern.ch/portal/cvmfs/workaround-krnl-deadlock) to the CentOS 7 integration test context. 
Furthermore this disables the hardlink stresstest for Ubuntu 12.04 since the AUFS version is too old to handle it correctly in this distribution.
=> FIX: Kernel Deadlock in CentOS 7 with OverlayFS + Hardlink Stresstest in Ubuntu 12.04

test/cloud_testing/platforms/slc6_x86_64_setup.sh
This ensures that always the latest available AUFS kernel will be installed - or the test case will fail, if the AUFS kernel was not yet built.
=> FIX: Update Packages before Installing AUFS Kernel

cvmfs/s3fanout.cc, cvmfs/s3fanout.h, cvmfs/upload_s3.cc
Mutable objects are uploaded now with "Cache-control: no-cache" header. This is needed at least with Google cloud storage to execute consecutive changes to the repository (e.g. twice mkfs). The problem is described in more detailed at Jira ticket CVM-808.
=> Fix: S3-backend caching disabled for mutable objects (CVM-808)

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_mgr_ro.cc, cvmfs/catalog_mgr_ro.h, cvmfs/cvmfs_server, cvmfs/sql_impl.h, cvmfs/swissknife_sync.cc, test/src/519-importlegacyrepo/main, test/src/544-cvmfsdirtab/main, test/src/546-extendeddirtab/main, test/src/549-dirtabexclusions/main, test/src/557-basicgarbagecollect/main, test/src/565-dirtabwildcardexclusions/main, test/src/566-dirtabrecreatenested/main
As described in [CVM-818](https://sft.its.cern.ch/jira/browse/CVM-818) the application of `.cvmfsdirtab` doesn't properly remove temporarily downloaded catalog database files. This fixes it by adding an auto-management feature to `SimpleCatalogManager`. It uses the `TakeDatabaseFileOwnership()` method of `Catalog` to automatically clean up the underlying SQLite database files as soon as a catalog is closed.
Furthermore this fixes a malformed shell quotation in `cvmfs_server` that would have acted as a safe guard to clear out the temp directory after each publishing. During normal operation the procedures in `cvmfs_swissknife` should not leak any tmp files. However, crashes or user aborts could still cause it (cf. [CVM-816](https://sft.its.cern.ch/jira/browse/CVM-816)), hence I'd like to …
=> FIX: Dirtab Application Leaks Temporary Catalog Database Files

CMakeLists.txt, packaging/debian/cvmfs/control
Firstly, Debian respectively Ubuntu decided to add `-D_FORTIFY_SOURCE=2` to `CPPFLAGS` which is not recognised by CMake. The [fix](http://www.cmake.org/Bug/view.php?id=12928) was that `CPPFLAGS` were automagically appended to `CFLAGS` in CMake. Unfortunately this is leads to an error when configuring the c-ares dependency. This workaround separates compiler and pre-processor flags in `CFLAGS` as it is supposed to be. This way we still get the benefits from `-D_FORTIFY_SOURCE=2` but are independent of any internal CMake tricks. Hopefully...
The second change in Debian is the introduction of [multi-arch](https://wiki.debian.org/Multiarch) support for shared libraries. It allows you to install i386 and x86_64 libraries side-by-side through stretching the FHS. Arguably we do not benefit from …
=> Fix/Refactor: Building on Ubuntu 14.04+

CMakeLists.txt
This is a follow up for the [last pull request](https://github.com/cvmfs/cvmfs/pull/868). Turns out, that `unset()` [needs](http://www.cmake.org/pipermail/cmake/2010-January/034307.html) at least CMake 2.6.3 thus I'm bumping the required version. We have it installed on all our build machines - after I updated the package on SLES11.
=> FIX: CMake 2.6.3 required for unset()

CMakeLists.txt
Going back to CMake 2.6.2 to support vanilla SLES 11. I replaced `unset()` by `set(XXX "")` hoping to produce the same effect as before. (Testing now...)
=> Revert: CMake version 2.6.2 due to SLES 11

cvmfs/cvmfs.cc, cvmfs/talk.cc
Example output:
Cache Mode: read-write
Drainout Mode: no
Maintenance Mode: no
SQlite Statistics:
Number of allocations 212
General purpose allocator 45 KB / 55 KB
Largest malloc 8194 Bytes
Page cache allocations 12 / 12
Page cache overflows 0 KB / 0 KB
Largest page cache allocation 1272 Bytes
Scratch allocations 0 / 0
Scratch overflows 0 / 0
Largest scratch allocation 0 KB
Raw Counters:
Name|Value|Description
cache.n_certificate_hits|0|Number of certificate hits
cache.n_certificate_misses|1|Number of certificate misses
catalog_mgr.n_listing|0|Number of listings
catalog_mgr.n_lookup_inode|0|Number of inode lookups
catalog_mgr.n_lookup_path|0|Number of path lookups
catalog_mgr.n_lookup_path_negative|0|Number of negative path lookups
catalog_mgr.n_lookup_xattrs|0|Number of xattrs lookups …
=> STATISTICS: added ShortString counters to cvmfs_talk

cvmfs/cvmfs_server, cvmfs/download.cc, cvmfs/logging.cc, cvmfs/logging_internal.h, cvmfs/s3fanout.cc, cvmfs/swissknife_history.cc, cvmfs/swissknife_info.cc, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, cvmfs/upload_s3.cc
This fix enables CVMFS to follow HTTP redirect requests. This is useful when using repositories with several buckets and Squid. The only change required in the Squid configuration is that mapped url is returned with "302:"-prefix, which in effect redirects the CVMFS to download the requested file directly from the cloud storage.
=> Fix S3 and download HTTP redirects

test/src/588-manydirectories/main
This tests the filling of a (fairly) large repository. I see this as a regression test, since it can easily break CernVM-FS 2.1.19 with a low file descriptor limit. CernVM-FS 2.1.20 should not suffer from this test. Furthermore, it monitors some resource usage while running the publish operation and hence might be useful for optimisation benchmarking.
=> TEST: Create Many Directories + Measure FD, memory and CPU usage

cvmfs/cvmfs_server, test/src/588-manydirectories/main
This fixes a problem introduced with the latest [S3 pull request](https://github.com/cvmfs/cvmfs/pull/859) by @ssheikki. Furthermore it cleans up logging in the 588 test from this [pull request](https://github.com/cvmfs/cvmfs/pull/874).
=> FIX: CVMFS_FOLLOW_REDIRECTS switch (+ minor of previous PR)

bump_version.sh, cvmfs/libcvmfs.cc, cvmfs/libcvmfs.h, cvmfs/libcvmfs_int.cc, cvmfs/libcvmfs_int.h, cvmfs/util.cc, cvmfs/util.h, test/unittests/CMakeLists.txt, test/unittests/t_backoff.cc, test/unittests/t_libcvmfs.cc, test/unittests/t_util.cc, test/unittests/t_wpad.cc
Various fixes to libcvmfs:
- Restore 2.1.19 option names (with new names as aliases)
- Add unit tests
- Use "unix-none" sqlite vfs
- Defines for error codes
- Don't start quota manager
- Add LIBCVMFS_REVISION, LIBCVMFS_VERSION_MAJOR, LIBCVMFS_VERSION_MINOR
=> Fix libcvmfs

cvmfs/cvmfs_server
This streamlines the debug capability of `cvmfs_server`. Before a `cvmfs_server publish -d` would run the publishing in debug mode. All other calls to `cvmfs_swissknife` could not be used like that unfortunately. Now, an invocation like `CVMFS_SERVER_DEBUG=1 cvmfs_server publish` will enable debug mode for all the important usages of `cvmfs_swissknife`. Similarly, `CVMFS_SERVER_DEBUG=2` will attach `gdb` to `cvmfs_swissknife` invocations and allow for setting break points for debugging.
*Note:* This is quite an intrusive change and needs a full cloud test run.
=> Feature cvmfs server debug

test/unittests/CMakeLists.txt, test/unittests/t_smalloc.cc
There are basically two type of tests:
1) Normal functionality, using normal numbers and checking that it doesn't crash.
2) The opposite: making reservations of a huge amount of memory that should force CVMFS to crash.
The tests passed, by the way.
=> TEST: added t_smalloc.cc

cvmfs/catalog_sql.cc, cvmfs/cvmfs_server, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_migrate.h
This fixes integration tests 519, 550, 563 and 568 that are all related to the legacy catalog migration from 2.0 catalogs. With the [introduction of `xattr`](https://github.com/cvmfs/cvmfs/pull/768) in the catalog database schema, the migration code was not updated accordingly and therefore crashed.
Additionally this adds a check for such situations to catch them easier next time.
Furthermore this fixes an issue introduced by @ssheikki's [S3 Redirects Pull Request](https://github.com/cvmfs/cvmfs/pull/859) that was using a repository URL as the repository name, leading to a failure in `cvmfs_server` - `load_repo_config()`.
=> FIX: Legacy Catalog Migration

test/unittests/t_smalloc.cc
Turns out that 32bit platforms typedef `size_t` to a 32bit integer which raises a compile error since the numerical literal introduced [here](https://github.com/cvmfs/cvmfs/pull/879) is not representable by it. The testee `smalloc()` expects a `size_t` so I changed it to `std::numeric_limits<size_t>::max()` and hope that 4GiB are enough to cause a runtime error on `smalloc()`.
=> FIX: Compile on 32bit Platforms

test/test_functions
Example of the current output (look at the bottom to see the new counters):
\# repo=atlas.cern.ch
\# iterations=1
\# warm_cache=no
cache.n_certificate_hits|0|Number of certificate hits
cache.n_certificate_misses|1|Number of certificate misses
catalog_mgr.n_listing|381|Number of listings
catalog_mgr.n_lookup_inode|0|Number of inode lookups
catalog_mgr.n_lookup_path|36383|Number of path lookups
catalog_mgr.n_lookup_path_negative|24460|Number of negative path lookups
catalog_mgr.n_lookup_xattrs|0|Number of xattrs lookups
catalog_mgr.n_nested_listing|24849|Number of listings of nested catalogs
cvmfs.n_fs_dir_open|381|Overall number of directory open operations
cvmfs.n_fs_forget|502|Number of inode forgets
cvmfs.n_fs_lookup|26894|Number of lookups
cvmfs.n_fs_lookup_negative|24460|Number of …
=> STATISTICS: added memory median and maximum in benchmarks

add-ons/tools/download_catalog_graph.py
This is useful when downloading a full catalog tree of a production repository. Until now `download_catalog_tree.py` would always download the entire history graph however.
=> Feature: download_catalog_graph.py can skip history

cvmfs/catalog_mgr.h, cvmfs/dns.h, cvmfs/download.h, cvmfs/letter.h, cvmfs/libcvmfs.h, cvmfs/loader.h, cvmfs/manifest_fetch.h, cvmfs/s3fanout.h, cvmfs/whitelist.h, test/unittests/testutil.h
This fixes a couple of compiler warnings in the error message to ASCII translation. Essentially I got rid of the sanity check in every `Code2Ascii()` function. The type system should make sure that this is not necessary, as pointed out by the clang compiler on OSX 10.10.
Furthermore I replaced the explicit `kNumElem` by implicit length codes in the enums. This is not necessarily type-safe in conjunction with `Code2Ascii()`. It gets rid of one magic number though, and ensures that at least the array in `Code2Ascii()` is always large enough even if it gets forgotten in the future.
Finally a mismatch between a forward declared `struct cvmfs_context` and `class cvmfs_context` is fixed.
=> FIX: Some Compiler Warnings on OS X

ci/common.sh, ci/run_cpplint.sh
A fire-and-forget wrapper for `cpplint.py`. The wrapper looks for source files in `cvmfs`, `mount` and `test/unittests` for now. Also meant to be run manually before pushing or to be put into git-commit hooks...
Simply do:
```bash
sh ci/run_cpplint.sh
```
=> CI: CppLint Wrapper Script

cvmfs/smalloc.h, test/unittests/t_smalloc.cc
wel... you've seen me writing it...
=> Fix: Integer Overflow in Unittest For smmap()

test/unittests/t_smalloc.cc
Looking into that again due to an itching little toe: We actually just provoked the newly added assert. I increased the safety margin in the `T_Smalloc::BigMmap` test and checked for the expected error message.
=> FIX: Make T_Smalloc::BigMmap More Strict

test/unittests/t_garbage_collector.cc
As @Moliholy figured out, there were threads straying around under some circumstances in the unit tests. It turns out that those are spawned by `AbstractUploader` which is used in the `T_GarbageCollector` test case through the `GC_MockUploader` which is not properly cleaned up afterwards.
=> FIX: T_GarbageCollector didn't clean up properly

cvmfs/s3fanout.cc, cvmfs/s3fanout.h, test/unittests/c_file_sandbox.h, test/unittests/t_util.cc, test/unittests/testutil.h
There were a number of OS X unit tests failing and that needed fixes:
1. `T_Util::GetGidOf` failed since the group 'root' is called 'wheel' on OS X
2. `T_Uploaders` failed for `S3Uploader` since it used a `sem_t` that is not supported on OS X
3. `T_FileProcessor` failed because of bogus global state initialisation
Regarding the `sem_t` problem: OS X does provide the proper definitions of `sem_init()`, `sem_wait()` and so forth, but their implementation always returns -1 and sets `errno` to 'not implemented'. Thanks Apple! I replaced the semaphore in `S3Fanout` by `SynchronisingCounter`.
The 'root' group name is just replaced by 'wheel' with an `#ifdef`.
=> FIX: Some Failing OS X Unit Test

test/unittests/t_dns.cc
This increases the timeout threshold for `T_Dns::CaresResolverTimeout` and disables `T_Dns::CaresResolverBadResolver`.
=> FIX: Increase timeout threshold for cares

test/unittests/t_xattr.cc
On older platforms (like SLES11) extended attributes might not be supported (or need to be enabled at mount). This just adds a bit more verbose logging for the failing test case `T_Xattr::CreateFromFile` to make it easier to debug.
=> improve logging of T_Xattr::CreateFromFile

test/unittests/t_upload_facility.cc, test/unittests/testutil.h
This replaces the volatile flag `worker_thread_running` with a `tbb::atomic<>`. Furthermore there was a data race in `T_UploadFacility::InitializeAndTearDown` where the same flag was checked after the object has been deleted.
=> FIX: MockUploader and T_UploadFacility::InitializeAndTearDown

cvmfs/swissknife_check.cc
Fixes the problem described in [CVM-842](https://sft.its.cern.ch/jira/browse/CVM-842). When running `cvmfs_server check -c` no checks for the existence of data chunks should be performed. However, partial file chunks (with hash suffix `P`) were still checked.
=> FIX: cvmfs_server check -c doesn't ignore partials

cvmfs/fs_traversal.h, test/unittests/t_fs_traversal.cc, test/unittests/t_util.cc
* Overflow in T_Util.StringifyTime
* \0 character in T_Util.Shell
* Check that a directory is readable in T_FsTraversal.BlockDevice to avoid insufficient permissions errors.
By the way, when running the non-slow tests now I see this in the end:
[----------] Global test environment tear-down
[==========] 492 tests from 50 test cases ran. (51419 ms total)
[  PASSED  ] 492 tests.
YOU HAVE 1 DISABLED TEST
And it looks like that disabled test is not one of the new ones. Am I missing something?
=> Solved some compiling and test problems in some platforms

cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/object_fetcher.h, test/src/557-basicgarbagecollect/main, test/unittests/t_object_fetcher.cc
Turns out that both `HttpObjectFetcher` and `LocalObjectFetcher` leak empty temporary files when the download of an object fails.
This inserts the necessary error handling and extends both integration test `557` and `T_ObjectFetcher` to check this condition.
=> FIX: Garbage Collection leaks Empty Temp File

cvmfs/util.cc
char *tmp_dir = strdupa((path_prefix + ".XXXXXX").c_str());
tmp_dir points to memory that has been removed before the strdupa copies it, so it is actually accessing to already released memory. I think it should solve the issue with the CreateTempDir function.
=> FIX: CreateTempDir no longer uses corrupted memory

cvmfs/cvmfs_server, test/src/589-importrepo/main
As described in [CVM-780](https://sft.its.cern.ch/jira/browse/CVM-780), `cvmfs_server import` fails to import a repository that contains an expired whitelist. Unfortunately one cannot resign a whitelist if the repository is not registered to a release manager machine. This adds `cvmfs_server import -r` allowing to recreate the whitelist (given a valid repository master key) during the import procedure.
Furthermore this adds an integration test that imports a contemporary repository both with and without expired whitelists.
=> FIX: cvmfs_server import can recreate an expired whitelist

test/unittests/t_util.cc
With this "-" it automatically removes the 0 character in a date.
For example:
"01 Jun 2015 12:00:05" -> "1 Jun 2015 12:00:05"
The main difference between %-d and %e is that %e adds a whitespace where the "0" was supposed to be, which makes the comparison fail. Like this:
"01 Jun 2015 12:00:05" -> " 1 Jun 2015 12:00:05"
=> FIX: bug in T_Util.StringifyDate for 1-digit days

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_sql.cc, cvmfs/catalog_sql.h, cvmfs/swissknife_pull.cc
This retro-fixes the problem @jblomer pointed out pointed out [here](https://github.com/cvmfs/cvmfs/pull/918#discussion_r31390901). It ended up in a new pull request since the fix requires some refactoring which is worth reviewing individually.
Changes done:
1. `Catalog::AllChunksNext()` now returns hashes with proper suffix annotation instead of `hash` and `type` individually
2. `catalog::ChunkTypes` was removed and replaced by `shash::Suffix` directly (this depends on `shash::Suffix` being a `char` and should be fixed in the future, see TODO)
3. Consolidate `Peek()` and `Store()` functions in `swissknife pull` that depend on `preload_cache`
4. Extend `struct ChunkJob` to encapsulate the hash (de)serialisation
=> FIX: Snapshotting/Preloading Code after Hash Cleanup

cvmfs/cvmfs_server, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_migrate.h, cvmfs/swissknife_sign.cc, cvmfs/uid_map.h, test/src/589-catalogchown/main, test/unittests/CMakeLists.txt, test/unittests/t_uid_map.cc
This allows to map the 'user ID' and 'group ID' meta-data fields for an entire repository on catalog level using a simple mapping description (Jira: [CVM-836](https://sft.its.cern.ch/jira/browse/CVM-836)). It is based on map files similar to the ones for `CVMFS_UID_MAP` and `CVMFS_GID_MAP` on the client. For large repositories, a simple `chown -R foo:bar /cvmfs/foo.bar.ch` is not practical, as it would re-compress and re-hash the entire repository content.
Doing this on catalog level is still a heavy-weight operation and is not supposed to be done regularly. The feature is meant to simplify migration of existing repositories to new infrastructure with different user ID requirements.
To run it on an existing repository, one first needs to create two map files, both for UIDs and GIDs and …
=> Feature: Bulk Change of File Owner on Catalog Level

test/unittests/t_util.cc
Failed because an `fprintf()` parameter string warning was treated as error on debian package build.
=> FIX: Build on Ubuntu

test/src/519-importlegacyrepo/main, test/test_functions
The integration test got stuck with the EXDEV bug because it didn't apply the [workaround](http://cernvm.cern.ch/portal/cvmfs/workaround-krnl-deadlock) properly.
=> FIX: Integration Test 519 suffers from EXDEV bug in CentOS 7

cvmfs/cvmfs_server, cvmfs/swissknife_info.cc
In the past the `attr -qg` in `cvmfs_server` was failing every now and then because of tight kernel memory space. This now uses `cvmfs_swissknife info` to get the same information which hopefully fixes those hiccups.
=> FIX: Avoid using `attr -qg` for Retrieval of Mounted Root Hash

cvmfs/fs_traversal.h, test/unittests/t_fs_traversal.cc
This adds support for `S_ISCHR()` in `FsTraversal<>`. @Moliholy did already add quite some file system object types but for some reason the *character device* was missing. This is needed for the integration with `overlayfs`. Furthermore this pull request does some adaptions to `T_FsTraversal` for resilience and testing of the newly added character device.
=> Feature: Detect Character Device in FsTraversal

test/src/013-certificate_cache/main
```
if ! sudo cvmfs_talk -i lhcb.cern.ch internal affairs | grep -A1 "Certificate cache:" | tail -1 | grep -q "hits: 1"
```
It doesn't work now because the internal affairs command now produces a different output.
=> FIX: cloud test 013: ClientIntegrationTests.Caching of certificate

test/unittests/t_fs_traversal.cc
On some platforms both `T_FsTraversal::CharacterDevice` and `T_FsTraversal::BlockDevice` were failing due to `stat()`-ing dangling symlinks in `/dev/**`.
=> FIX: T_FsTraversal unit test

python/cvmfs/test/__main__.py, python/cvmfs/test/manifest_test.py
This adds a `__main__.py` to the already partly implemented unit test set for the python library. With that, one can run the unit tests simply by invoking:
`python python/cvmfs/test`
Furthermore this adds all newly added manifest fields to the test case.
=> Test: Preparing unit test set for CVMFS Python Package

python/cvmfs/__init__.py, python/cvmfs/manifest.py, python/cvmfs/root_file.py, python/cvmfs/test/__main__.py, python/cvmfs/test/manifest_test.py, python/cvmfs/test/md5_handling_test.py, python/cvmfs/test/whitelist_test.py, python/cvmfs/whitelist.py
This factors out some logic from `Manifest` into `RootFile` to reuse it in the newly added `Whitelist` wrapper. Furthermore it contains extensions to the test suite for both `Manifest` and `Whitelist`.
=> Python: Whitelist Wrapper

ci/common.sh, ci/run_python_unittests.sh
This checks if Python is installed, if it is not ancient (yes < 2.6 is ancient!) and if `python-xmlrunner` is installed on the system.
=> FIX: Inspect Python Suitability Beforehand

ci/common.sh
Turns out, that `cut` only knows the short-hand switches `-d` (instead of `--delimiter`) and `-f` (instead of `--field`) on OS X. meh!
=> FIX: Python Environment Retrieval

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_rw.cc, cvmfs/quota.cc, cvmfs/sql.h, cvmfs/sql_impl.h, test/unittests/t_sqlite_database.cc
This replaces the explicit SQL queries in `catalog.cc` and `catalog_rw.cc` to access information in the `properties` table with calls to `Database<>::GetProperty<>()` and `Database<>::SetProperty()` as requested in [CVM-720](https://sft.its.cern.ch/jira/browse/CVM-720).
=> Cleanup: Use Database<>::GetProperty<>() and Database<>::SetProperty()

python/cvmfs/__init__.py, python/cvmfs/certificate.py, python/cvmfs/manifest.py, python/cvmfs/repository.py, python/cvmfs/root_file.py, python/cvmfs/test/__main__.py, python/cvmfs/test/certificate_test.py, python/cvmfs/test/manifest_test.py, python/cvmfs/test/whitelist_test.py, python/cvmfs/whitelist.py
This allows the verification of the signatures both in the `Manifest` and the `Whitelist`. I am using `M2Crypto` for this, because its both available for RedHat and provides a simple wrapper around libopenssl. What is missing, is the integration of these verifications into a simple method call.
In detail, this introduces `Certificate` as python class, so that one can simply do:
```python
import cvmfs
repo = cvmfs.open_repository("http://cvmfs-stratum-one.cern.ch/cvmfs/altas.cern.ch")
cert = repo.retrieve_certificate()
repo.manifest.verify_signature(cert)
repo.verify_whitelist("/etc/cvmfs/keys/cern.ch/cern.ch.pub")
repo.open_repository("http://cvmfs-stratum-one.cern.ch/cvmfs/atlas.cern.ch", "/etc/cvmfs/keys/cern.ch/cern.ch.pub")
```
As always: Additional tests added to the python unit test …
=> Python: Verify Signatures of Manifest and Whitelist

ci/run_python_unittests.sh
Skip the python unit tests if this package was not found.
=> FIX: Check for M2Crypto Python Module

test/run.sh
It allows to execute run.sh with the "-d" option that enables the bash debug.
In a nutshell, this change is not meant to be used in a normal execution of a test/benchmark but to make our life easier while developing.
Example of execution:
```
./run.sh ~/benchmarks.log -d benchmarks/001-atlas/
```
=> TEST: added debug information to test/run.sh

test/benchmarks/004-cms/main, test/test_functions
Due to a race condition the cms.cern.ch repository couldn't always unmount. Now there is a 5-second-delay to allow the mounted repository to finish its stuff. 
Also added descriptions when a benchmark fails.
=> FIX: cms benchmark termination fixed

test/test_functions
There were some variables polluting the environment in test/test_functions, so I added "local" before them. Basically I took a look and (manually) fixed those that match the following regular expression:
```
^ +[^]( [a-z_-]+)=
```
=> FIX: added "local" to some variables in test_functions

ci/build_python-cvmfsutils_rpm.sh, python/setup.py
Unfortunately we cannot easily provide a universal RPM for el6 and el7 since the python version (and thus the installation destinations) differ.
=> FIX: Platform dependent Python Package RPM

ci/build_python-cvmfsutils_rpm.sh, ci/common.sh
The RPM builder doesn't provide a default `%{?dist}` tag in SuSE. -.-
=> FIX: Dist Tag for SuSE RPM

test/test_functions
Removing the whole cache directory only works if cvmfs is fully stopped. Otherwise removing the cache produces errors that made the last benchmarks fail (https://phsft-jenkins.cern.ch/view/CVMFS/job/CvmfsBenchmark/).  With this fix it should work.
=> FIX: manual cache cleanup for the benchmarks

ci/run_python_unittests.sh, python/run_unittests.py
On Python 2.7 `unittest2` is actually `unittest`.
=> FIX: unittest2 check on Python 2.7

python/cvmfs/__init__.py, python/cvmfs/_common.py, python/cvmfs/availability.py, python/cvmfs/test/availability_test.py, python/cvmfs/test/logistic_function_test.py
With the `Availability` class one can judge the current replication health of a repository given a *Stratum0* and a number of *Stratum1s*. The `Availability` class can be parameterised with thresholds for *revision difference* and *last snapshot attempt* (to be extended) which are used to compute a health score either for each individual replica or the entire repository network.
The score is computed using a [logistic function](https://www.wikiwand.com/en/Logistic_function) that provides a smooth curve between *healthy* and *fatal* for each observable. For example, given a *revision difference threshold* of 5, a repository would get health scores like the following:
Δrevision | health score
------------ | -------------
0 | 1.0
1 | 0.99
2 | 0.96
3 | 0.9
4 | 0.75
5 | 0.5
6 | 0.25
7 | 0.1
8 …
=> Python: Add Availability Class to Python Package

cvmfs/cvmfs_server
Turns out that the timestamp in `.cvmfs_last_snapshot` is dependent on the *locale* of the system and hence not easily parsable. For instance, Fermilab is currently in *CDT* which might be *Central Daylight Time* or *Cuba Daylight Time*. Meh!
This changes the timestamp to UTC regardless of the system's time zone.
=> FIX: .cvmfs_last_snapshot is locale dependent

python/cvmfs/_common.py, python/cvmfs/repository.py
This uses a timezone mapping I found on [StackOverflow](http://stackoverflow.com/questions/1703546/parsing-date-time-string-with-timezone-abbreviated-name-in-python/4766400#4766400) to work around the ambiguous time stamps in `.cvmfs_last_snapshot` in CernVM-FS 2.1.20. The [next release](https://github.com/cvmfs/cvmfs/pull/971) of CVMFS will put UTC time stamps there.
=> FIX: .cvmfs_last_snapshot contains ambiguous time zones

python/statistics_comparison.py
However now it prints an ugly warning while downloading the image, but it works like a charm.
```
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
```
After a bit of research it looks like there is nothing to do in order to suppress that warning...
=> FIX: enable docker pull and push from local repository

CMakeLists.txt
Apparently otherwise an `if (NOT ${USING_CLANG})` doesn't work...
=> FIX: set USING_CLANG to 0 explicitly

python/statistics_comparison.py, test/test_functions
Now benchmarks can run jobs in parallel. However, due to the fact that right now there are some clashes when writing into files in parallel, the default is set to 1, so in principle it doesn't break anything
=> Benchmark overload

python/cvmfs/__init__.py, python/cvmfs/_common.py, python/cvmfs/availability.py, python/cvmfs/certificate.py, python/cvmfs/manifest.py, python/cvmfs/repository.py, python/cvmfs/root_file.py, python/cvmfs/test/availability_test.py, python/cvmfs/test/certificate_test.py, python/cvmfs/test/file_sandbox.py, python/cvmfs/test/logistic_function_test.py, python/cvmfs/test/mock_repository.py, python/cvmfs/test/repository_test.py, python/cvmfs/test/tcp_server_26ish.py, python/cvmfs/test/whitelist_test.py, python/cvmfs/whitelist.py
This backports the cvmfsutils python package to Python 2.4 and makes it compliant to the python dependencies provided in RHEL5.
Things that needed to be done:
* Adapt exception handling in some places
* Replace ternary if-else operator with conventional if-else
* Python 2.4 doesn't have the `with open(<file>) as file_object` block
* There is no Abstract Base Class module (replaced by `raise NotImplementedError()`)
* Remove `requests` package as it is not provided on RHEL5
* Remove `unittest2` backport dependency
* Detect RHEL5's ancient `M2Crypto` library and work around missing features
* Backport Python 2.6's [`TCPServer.shutdown()`](http://fw-geekycoder.blogspot.ch/2011/09/how-to-implement-shutdown-method-in.html) functionality for the unittest suite
* The `ctypes` package is a …
=> Python: Backporting python-cvmfsutils to RHEL5

ci/run_python_unittests.sh
This adapts the unittest run script for `python-cvmfsutils` to check for the updated dependencies.
=> FIX: Python Unittests Run Script

test/src/589-catalogchown/main
Steve pointed out a potential problem in [CVM-836](https://sft.its.cern.ch/jira/browse/CVM-836) with `cvmfs_server catalog-chown`. Even though it turned out to be a usage mistake, I've already written the regression test code. So here it is.
=> TEST: catalog-chown the root entry

CMakeLists.txt, test/unittests/CMakeLists.txt
It's possible to run gcovr with many different binaries, so this way we could compile and run the integration tests and see how much they actually cover. Of course it could also be added to our Jenkins project.
Just as an example, check out http://cvm-stat01/integration/ 
I only ran the first 5 tests there, so there is not so much coverage.
=> TEST: added debug mode option for coverage

test/test_functions
This way you can specify more than one Valgrind tool. For example:
export CVMFS_OPT_TEST_TYPE="callgrind memcheck"  # would run valgrind twice, one for each tool
=> TEST: add multiple Valgrind options to the benchmark infrastructure

cvmfs/cvmfs_config
If automounter unmounts a repository just at the wrong moment, the repository itself can be remounted on the fly (base64 encoded guard files in /var/run/cvmfs/pause.cvmfs) but the config repository cannot necessarily.  This is now fixed.
=> FIX: remove race that can result in a hanging reload

cvmfs/cvmfs.cc, cvmfs/file_chunk.cc, cvmfs/file_chunk.h, cvmfs/libcvmfs.cc, cvmfs/libcvmfs.h, cvmfs/libcvmfs_int.cc, cvmfs/libcvmfs_int.h, cvmfs/libcvmfs_public_syms.txt, test/unittests/CMakeLists.txt, test/unittests/t_file_chunk.cc
Add a new function `cvmfs_pread` to libcvmfs.  Channeling all read calls through the library allows to take care of chunked files.  Instead of whole file caching, chunked files are downloaded and cached only once the corresponding byte range is requested.  Chunked files have a file descriptor with bit 30 set to 1.  The first 29 bit point to an array in `SimpleChunkTables` that holds a file descriptor and the list of chunks and offsets for this file.
The new functionality requires a small modification to the parrot source code (separate request to cctools project).  The change is backwards compatible and only effective if `LIBCVMFS_REVISION` >= 18.
This PR also moves the binary search to find a chunk idx given an offset from the fuse module to the `FileChunkReflist` and adds a unit test. …
=> Add support for chunked files to libcvmfs

cvmfs/loader.cc
OS X Fuse has a few mount options that differ from Linux fuse.  Use them appropriately.  Also turn off multi-threaded fuse for the time being until we understand current problems on Mac.
=> tune fuse mount options for Mac

cvmfs/monitor.cc, cvmfs/util.cc, mount/mount.cvmfs.cc
OS X uses lldb instead of gdb.  In addition this PR prepares the mount helper for osxfuse 3.
=> FIX: stack trace generation on OS X

cvmfs/cvmfs.cc, test/src/062-loadtag/main
The custom cvmfs sqlite vfs must not be activated before the history database is queried.
=> FIX: mount specific repository tags

test/test_functions
- Moved the cache directory to ~/.benchmark
- User added to the fuse group
- Granted ownership of /cvmfs/\<repo\> to the current user
- Added "sudo" to some commands
=> TEST: benchmarks no longer require to be executed as sudo

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_rw.cc, test/src/550-livemigration/main, test/src/592-magicsymlinks/main, test/test_functions
As described in [CVM-874](https://sft.its.cern.ch/jira/browse/CVM-874) magic symlinks can break when the repository's nested catalog structure changes. This adds a regression test for this issue and fixes the bug.
*Note*: The integration test neither checks the behaviour of magic symlinks in absence of their required environment variables nor their proper recreation in a CVMFS server installation. This is left for another test in conjunction with the implementation of [CVM-879](https://sft.its.cern.ch/jira/browse/CVM-879).
=> FIX/TEST: Magic Symlinks and Nested Catalogs

cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_union.cc, test/src/593-nestedwhiteout/main
This fixes a problem found by Alice and tracked in [CVM-880](https://sft.its.cern.ch/jira/browse/CVM-880). In short: When renaming a directory that contains AUFS whiteout entries the whiteouts might persist (even though useless) under certain circumstances. The CVMFS syncing process didn't expect those and crashed. This fix now ignores whiteouts in this case. Furthermore the Pull Request contains a regression test for the issue.
Note that a bit of refactoring in `SyncItem` was necessary to properly implement this fix. Namely, `SyncItem` now lazy-evaluates both the `stat()` for the read-only AUFS branch and for the r/w scratch branch. Up to now `SyncItem` was relying on the user to provide the correct directory entry type, this is now optional.
=> FIX: Renaming a Directory containing Changes fails to Publish

test/cloud_testing/platforms/common.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh
The latest version of [FakeS3](https://github.com/jubos/fake-s3) (0.2.1) seems not to work on SLC6. This allows to install an older (working) version of the ruby gem. With that the S3 cloud tests should hopefully not fail anymore.
=> FIX: Cloud testing FakeS3 Installation

cvmfs/cvmfs_server
This adds `cvmfs_server add-replica -s <S3 config file>` that behaves in the same way as `cvmfs_server mkfs -s` published with CVMFS 2.1.20.
=> Feature: Stratum1 S3 Convenience Switch

cvmfs/cvmfs_server, test/src/515-createsnapshot/main, test/src/516-createsnapshotadvanced/main, test/src/521-createmultiplesnapshots/main, test/src/576-garbagecollectstratum1/main
This changes the default temporary directory used by the S3 upstream definition from `/tmp` to `/var/spool/cvmfs/${repo_name}/tmp`. Furthermore it cleans out two leaked sentinel files that were left in the latter tmp directory.
Additionally some of the Stratum1 related tests are amended to check for an empty tmp directory after `cvmfs_server snapshot`.
=> FIX: S3 Upstream Temporary Directory

test/test_functions
Turns out that RHEL5 doesn't support templates with intermediate placeholders in `mktemp`. Hence, something like **foo.XXXXX.bar** will result in clashes on multiple calls to `mktemp`.
=> FIX: Unsupported mktemp Pattern (RHEL5)

test/src/593-nestedwhiteout/main
This 'fixes' the integration test 593 on RHEL5. For some reason SELinux is chipping in here with a funny error message. Supposedly it is due to funny labeling issues or potentially even a bug in AUFS. I don't see it happening anywhere else.
Since 593 tests a [rare corner case](https://sft.its.cern.ch/jira/browse/CVM-880) of AUFS, I decided to add a workaround into the integration test case that detects the *permission denied* error, checks that it is on RHEL5 and temporarily disables SELinux.
=> Workaround: Test 593 fails on RHEL5 due to SELinux

test/src/537-symlinkedbackend/main, test/src/538-symlinkedstratum1backend/main
Apparently the SELinux default behaviour on SL5 has changed so that `httpd` cannot read files when a backend is symlinked from **/srv/cvmfs/test.cern.ch** to **/tmp/test-workspace/...**.
I've disabled the enforcing mode for SELinux on those tests to work around it. What we really want to test here is that CVMFS can deal with those symlinked backends. Proper SELinux setup depends on the setup environment anyways .
Furthermore I refactored the `desaster_cleanup()` method into a `trap` based approach as done in newer tests as well. This gives better test maintainability and also more resilience against test interruptions.
=> FIX: Integration Tests for Symlinked Backends

test/cloud_testing/platforms/slc6_x86_64_test.sh, test/src/592-magicsymlinks/main
This fixes some S3 based server integration tests. Namely 585 and 591 don't make sense for S3 and are thus disabled in the cloud tests. The rather new 592 had a bug that broke it on S3.
=> FIX: SLC6 S3 Integration Tests

cvmfs/s3fanout.cc, test/cloud_testing/platforms/slc6_x86_64-gcov_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/src/515-createsnapshot/main, test/src/516-createsnapshotadvanced/main, test/src/521-createmultiplesnapshots/main, test/src/522-missingchunkfailover/main, test/src/523-corruptchunkfailover/main, test/src/524-corruptmanifestfailover/main, test/src/529-ripemd160/main, test/src/538-symlinkedstratum1backend/main, test/src/550-livemigration/main, test/src/576-garbagecollectstratum1/main, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/579-garbagecollectstratum1legacytag/main, test/src/580-automaticgarbagecollectionstratum1/main, test/src/581-snapshotgarbagecollectedrepo/main, test/src/584-interleavingsnapshot/main, test/src/588-sha256/main, test/test_functions
This enables the usage of the S3 backend in the integration tests dealing with Stratum1s. Some fixes were necessary to make it work:
* CVMFS_TEST_STRATUM0 was renamed to CVMFS_TEST_HTTP_BASE for consistency
* Stratum1s on S3 need a non-default HTTP URL to access the storage
* Refactor: use {{do_local_mount()}} in test cases 515, 516, 529 and 588 that takes the S3 based URLs into account
* Tests 529 and 588 were checking files directly in **/srv/cvmfs** which doesn't work with S3
* Timeouts in test 584 were too short for the slowish FakeS3
* Test 584 was failing due to slightly different logging output on S3
* The S3 backend is not cleared by `cvmfs_server rmfs` omitting the 'Initial Snapshot' on Stratum1s. Hence I made sure that the used Stratum1 names are unique
Furthermore this pull …
=> TEST: Use the S3 backend for Stratum1s in Integration Tests

test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh
Since Ubuntu doesn't support xattrs out of the box I disable it for now in the cloud tests on those platforms.
=> TEST: Disable Integration Test 585 (xattrs) in Ubuntu

python/cvmfs/_common.py
Some example test:
\>\>\> c = CompressedObject(open("/Users/guimard/sft.cern.ch/data/00/005b606488bcfe6fe1586e35380cc400a12b41C"))
\>\>\> c.size_compressed()
3832
\>\>\> c.size_uncompressed()
18432
=> PYTHON: added database file size method

.gitignore, Vagrantfile, vagrant/provision_cernvm.sh
This adds the possibility to bootstrap a Vagrant-managed build environment based on CernVM. What needs to be done, to make it work is as easy as that:
```bash
vagrant box add cernvm http://cernvm.cern.ch/releases/testing/ucernvm-prod.2.2-1.cernvm.x86_64.box
vagrant up
vagrant ssh
```
=> Feature: Vagrant-managed Development Environment 

cvmfs/upload.cc
When a `Spooler` was not properly initialised (for example because of a malformed spooler definition string) it segfaulted due to a missing NULL-check of the `AbstractUploader` member in the `Spooler`'s destructor. [CVM-891](https://sft.its.cern.ch/jira/browse/CVM-891)
=> FIX: Segfault on Malformed Spooler d'tor

packaging/debian/cvmfs/control
On Debian both packages `cvmfs-server` and `cvmfs-unittests` were depending on `cvmfs` which makes problems when running cloud tests against an older client. I've removed those dependencies to harmonise the packages with RPM.
=> FIX: Debian Dependencies of Server and Unittests

cvmfs/cvmfs_server, test/src/582-autorepairmountpoints/main, test/src/584-interleavingsnapshot/main, test/src/587-serverhooks/main
This works towards a fix for [CVM-810](https://sft.its.cern.ch/jira/browse/CVM-810) by unifying the various locks used in `cvmfs_server` into a couple of helper functions. I found a convincing implementation of [file based locks](http://rute.2038bug.com/node23.html.gz) in shell script which I built upon. The central idea is that hardlink creation is atomic in Unix.
Currently stale locks are only detected based on their creator's PID which might lead to false negatives. However, I wonder how likely this is, especially taking into account that stale locks itself should already be unlikely (requiring a host crash).
I am using the implementation for three different locks, namely: **in_transaction**, **is_publishing** and **is_snapshotting**. Furthermore the patch adapts a couple of …
=> FIX: Detect Stale Snapshotting Locks

cvmfs/swissknife_history.cc, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sign.h, cvmfs/upload.cc, cvmfs/upload.h, cvmfs/upload_local.cc, cvmfs/util_concurrency.h, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/src/594-backendoverwrite/main
When `touch`-ing a file in a repository the following publish will need to process this file (since it must figure out if the file was only `touch`'ed or actually modified). Processing an unchanged file will result in a content hash that is already present in the repository's backend storage. The local backend implementation didn't check for existing files and did an overwrite in such a case.
Technically this is not a problem, but it requires some extra IOPs and changes the 'last modified' timestamp of those files, which might have an influence on backup performance. See [CVM-894](https://sft.its.cern.ch/jira/browse/CVM-894) for details.
This adds a check for existence before overwriting those files. Furthermore it adds an integration test verifying that no overwrites happen anymore. Note …
=> FIX: Local Backend Overwrites Unchanged Files

Vagrantfile, vagrant/provision_slc6.sh
This adds a vagrant environment for SLC6 besides the CernVM based development environment. To run it, Vagrant needs to have the [vagrant-reload](https://github.com/aidanns/vagrant-reload) plugin installed to allow for a VM reboot at provisioning time (AUFS kernel install).
To use the SLC6 based development environment do:
```bash
vagrant plugin install vagrant-reload
vagrant up slc6
vagrant ssh slc6
```
=> Feature: Vagrant Environment for Scientific Linux 6

cvmfs/catalog_rw.cc, cvmfs/catalog_rw.h, cvmfs/catalog_sql.h, cvmfs/hash.h, cvmfs/sql.h, cvmfs/swissknife_pull.cc, test/unittests/t_async_reader.cc, test/unittests/t_file_processing.cc
Since the recently added **SHA2** hash has a length of 32 bytes in contrast to the previously supported hash algorithms **SHA1** and **RMD160** we now need to take the the hash length into account when copying them into nested catalogs. Otherwise all older client would have crashed when reading chunked files.
This pull request also incorporates minor refactorings; namely the removal of some magic numbers and the simplification of an `shash::Digest` and `shash::Any` c'tor.
=> FIX: Chunk Hashes getting Scrambled on Nested Catalog Creation

vagrant/provision_slc6.sh
This installs `jq` on the SLC6 development environment (needed for cloud testing) and adds the user 'sftnight' to the 'fuse' group by default.
=> Vagrant: Minor SLC6 Improvement

cvmfs/cvmfs_server, test/test_functions
The GeoIP database update code in `cvmfs_server` along with a change in [#1052](https://github.com/cvmfs/cvmfs/pull/1052) caused several integration tests to fail. Looking into it, I found the entire update logic incomprehensibly complicated and decided to rewrite it.
**NOTE:** Please don't merge yet, I'll add an integration test for this later today.
The semantic should be very much the same, but with a reasonable control flow. Changes done:
* move main logic from `update_geodb()` to `_update_geodb()`
* wrap the `cvmfs_server update-geodb` call into a simple sanity checker
* centralise static config (download URL, database location and filename)
* simplify the Apache config file creation (remove an evil and unnecessary stdin-stdout hack)
* break previously convoluted update logic into …
=> Rewrite: GeoIP database Installation and Update Logic

cvmfs/cvmfs_server, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/src/595-geoipdbupdate/main
This is a followup to yesterday's [pull request](https://github.com/cvmfs/cvmfs/pull/1056). Mainly it adds an integration test to verify the proper updating behaviour of the GeoIP database on Stratum1s. Furthermore it fixes a couple of minor sanity check inconsistencies.
@DrDaveD: Could you have a specific look at [this commit](https://github.com/cvmfs/cvmfs/commit/2964e13ca5d13f1a75412524954170b36e8ad3ba). I needed to remove the `check_apache()` and `check_wsgi_module()` calls from `cvmfs_server snapshot` as they assume root privileges. Do you think, we can survive without checking the proper installation of apache and WSGI on every `snapshot`?
=> TEST/FIX: GeoIP Database Update

test/src/595-geoipdbupdate/main
`date +%k` returns one-digit hours with a pre-pended whitespace. Sigh...
=> FIX: Flaky Test 595

python/cvmfs/__init__.py, python/cvmfs/_common.py, python/cvmfs/availability.py, python/cvmfs/catalog.py, python/cvmfs/certificate.py, python/cvmfs/dirent.py, python/cvmfs/history.py, python/cvmfs/repository.py, python/cvmfs/root_file.py, python/cvmfs/test/certificate_test.py, python/cvmfs/test/manifest_test.py, python/cvmfs/test/mock_repository.py, python/cvmfs/test/repository_test.py, python/cvmfs/test/whitelist_test.py, python/setup.py
This pull request changes the Repository class in the python API. Before it was necessary to instantiate a sub-class of Repository, i.e., RemoteRepository or LocalRepository. The first one always downloaded everything and didn't use any permanent cache, while the second one only could work in local.
In this context, I thought it was better to have just a Repository class so that the user can specify the cache directory and the remote directory. This way he can abstract from the use of full-cached, full-remote and the combination of these two, which is the way the client actually works.
Catalog class has been modified in consequence since it doesn't require a compressed file to be initialised, but an already decompressed one.
Updated example usage:
```
import cvmfs
repo = …
```
=> Python new Repository class

cvmfs/cvmfs_server, cvmfs/swissknife_check.cc, cvmfs/swissknife_check.h, test/test_functions
Funny insight: `my_program | grep -q needle` searches for the first occurrence of *needle* in the output stream of `my_program`. As soon as it found something, `grep` is exiting with return code 0, invalidating the pipe that is attached to `my_program's` stdout. This causes `my_program` to crash (most likely with SIGPIPE).
Unfortunately `cvmfs_swissknife lsrepo` cannot cleanup after himself in that case and leaves some temporary files behind. 
Note: This is based on [FIX: Consistent Usage of Temporary Directories](https://github.com/cvmfs/cvmfs/pull/1071).
=> FIX: Temp File Leakage in test_functions

cvmfs/cvmfs_server, cvmfs/swissknife_check.cc, cvmfs/swissknife_check.h
This fixes both `cvmfs_server` and `cvmfs_swissknife` when it was using **/tmp** instead of **${CVMFS_SPOOL_DIR}/tmp** as a working directory. This is mainly to confine any possible temp file leakage into our own environment.
This comes with the expense that also `cvmfs_server` commands that only require read-access need to run as the repository owner or root.
=> FIX: Consistent Usage of Temporary Directories

test/unittests/env.cc, test/unittests/env.h, test/unittests/t_util.cc
This fixes [yesterday's pull request](https://github.com/cvmfs/cvmfs/pull/1069) that tried to exploit GTest's feature to switch to the working directory of the parent process when spawning child processes for death tests. Unfortunately this doesn't work, because GTest determines this working directory before even `main()` is running in the parent process. Hence, death tests would not properly switch to the sandbox directory and start littering in the wrong location.
This fixes `CvmfsEnvironment` which now drops a file like **/tmp/cvmfs_ut_sandbox.pid.$PID** which can be found by the child processes using `getppid()`. The file contains the full path of the sandbox directory created by the main GTest process. This way we can actively switch to the sandbox before the death test is running.
=> FIX: Unittest Sandboxing

test/unittests/t_libcvmfs.cc
I guess Libcvmfs is using `chdir()` internally. Since the tmp file sandboxing depends on the working directory of the `cvmfs_unittests` process to be in a certain place, this poisons the execution environments of the following tests. In particular `T_Util.MakeSocket` and friends, as they depend on short paths.
=> FIX: T_Libcvmfs Poisons Working Directory for Other Tests

test/unittests/env.cc, test/unittests/env.h
As [proposed](https://github.com/cvmfs/cvmfs/pull/1073#issuecomment-134540065) by @jblomer, I've replaced the sandbox pointer file with an environment variable set but the parent and read by the death test children processes. That safes quite a bit of boilerplate and should be safer than the PID-file.
=> Refactor: Use Environment Variable for Test Sandbox

test/src/572-proxyfailover/main
This test was implicitly broken by [8bea34f](https://github.com/cvmfs/cvmfs/commit/8bea34fe594e2bb449633133bf5570630842fb4a) because this changed the return value of `stop_watch` from seconds to milliseconds. This requires adaptions in the expected runtimes inside this integration test that have never been done.
=> FIX: Integration Test 572 - Proxy Failover Scenario

ci/build_on_docker.sh, ci/common.sh, ci/docker/el4/Dockerfile, ci/docker/el4/README.md, ci/docker/el4/build.sh
This bases the EL4 build container on our own preserved SLC4 yum repositories. Furthermore it fixes a couple of minor things in the build system to make it work down to these ancient times.
=> CI: Build Scientific Linux 4 RPMs in a docker container

ci/common.sh, ci/cvmfs/rpm.sh
Turns out that `rpmbuild` retrieves its default architecture from the running kernel (like: `uname -m`) which is wrong inside 32bit docker containers. This explicitly passes `rpmbuild --target=...` and retrieves the architecture from GCC's default (`gcc -dumpmachine`).
=> CI: Use rpmbuild --target instead of Default Architecture

ci/docker/slc5_i386/Dockerfile
Generated tarball for SLC5 32bit is `slc5_i386.tar.gz`. Fixing that in the `Dockerfile`.
=> FIX: SLC5 32bit Dockerfile Refers to Wrong Tarball

ci/docker/cc7_x86_64/Dockerfile, ci/docker/fedora20_i386/Dockerfile, ci/docker/fedora20_x86_64/Dockerfile, ci/docker/fedora21_i386/Dockerfile, ci/docker/fedora21_x86_64/Dockerfile, ci/docker/slc4_i386/Dockerfile, ci/docker/slc5_i386/Dockerfile, ci/docker/slc5_x86_64/Dockerfile, ci/docker/slc6_i386/Dockerfile, ci/docker/slc6_x86_64/Dockerfile
This removes a bunch of packages from the build docker images that are not necessary for building. This is both to save space and to speed up the build process of the images. Note: This is somewhat a blue shot, I hope I didn't remove too much. :-) We'll see.
=> CI: Remove Unnecessary Packages from Docker Images

CMakeLists.txt, test/unittests/CMakeLists.txt
This Pull Request enables the "make check" feature, which compiles and runs the unit tests (only the fast ones).
The example sequence that compiles and runs _ONLY_ the unit tests would be:
```
mkdir build
cd build
cmake .. && make check
```
If we want to compile only the normal cvmfs sources it's enough with:
```
cmake .. && make
```
If we want to compile the sources and the unit tests, but not to run them:
```
cmake -DBUILD_UNITTESTS=yes .. && make
```
If we want to compile the sources and the unit tests, and run them:
```
cmake .. && make all check
```
If we want to execute the unit tests once they have already been compiled to avoid recompilation:
```
make test ARGS="-V"  # to make it verbose
OR
ctest -V
```
However, if no tests are compiled an error will be raised.
=> Enable "make check" command to build and run the unit tests

python/parser.py
- Fixes a problem with the order benchmarks appear in the CSV files
- Calculates and retrieves the standard deviation between different iterations as another column in the generated CSV. Notice that this adds two more columns: one for the original repository and one for the external repository
=> Statistics collector fix

ci/common.sh, ci/cvmfs/deb.sh, ci/docker/ubuntu1404_x86_64/Dockerfile, ci/docker/ubuntu1404_x86_64/build.sh, packaging/debian/cvmfs/rules
This allows for dockerized builds on Ubuntu 64bit including a recipe to generate the Docker image. Furthermore it builds with `make -j XX` now.
=> CI: Ubuntu 64bit docker recipe

ci/docker/sles11_x86_64/Dockerfile, ci/docker/sles11_x86_64/build.sh, ci/docker/sles11_x86_64/build_internal.sh
That was a bit of a fight. Mainly because the `openldap-client` RPM wasn't able to properly run it's post-install script. The workaround is as follows now:
1. install all dependencies for `openldap-client` via `zypper`
2. download the `openldap-client` RPM from the repository
3. install it via `rpm -i --noscript`
4. install `sles-release` via `zypper` that depends on `openldap-client`
This will probably render the installed LDAP package useless, but we don't care about that while using the docker container only for RPM builds.
A second complication was that there is no public SLES docker container that could have been used for bootstrapping. I am now using the `opensuse` container I used to bootstrap OpenSUSE 13. Hence, after bootstrapping I need to rebuild the RPM database as the …
=> CI: Add Docker Recipe for SLES 11

Vagrantfile, vagrant/provision_fedora.sh
This adds a Fedora 22 development box to our vagrant contexts. The box automatically comes up with OverlayFS up and running. Let's see if it is as broken as CentOS 7.1's version of it.
=> Vagrant: add Fedora 22 development box

Vagrantfile, vagrant/provision_fedora.sh
This creates a secondary ext4 hard drive for the Fedora 22 vagrant box and mounts it to /var/spool/cvmfs. Furthermore it fixes two things:
* syntax error in provisioning script
* `dnf -y update` while provisioning
=> Vagrant: Secondary hard drive for Fedora 22

cvmfs/CMakeLists.txt, cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_sql.cc, cvmfs/cvmfs.cc, cvmfs/options.cc, cvmfs/options.h, cvmfs/uid_map.h, test/src/063-uidmap/main, test/unittests/t_uid_map.cc
Remove the parsing of UID/GID maps from the options manager and uses the `IntegerMap` class developed for catalog migration.
NOTE: The semantics of `Map()` has been changed: instead of mapping values without explicit rule to zero, they are now mapped to themselves.  The `Map()` method wasn't used so far.
=> Use IntegerMap for CVMFS_{U/G}ID_MAP

cvmfs/cvmfs_server, test/test_functions
Fedora 22 has multiple `systemd` processes running. Hence, the check for `systemd` in `cvmfs_server` cannot simply do `$(pidof systemd) -eq 1` since this might have returned multiple PIDs. This introduces a `minpidof()` helper to figure out the lowest running PID that can then be checked for `1`.
=> FIX: systemd might run multiple times

cvmfs/cvmfs_server
Turns out that Fedora 22 with OverlayFS in a virtual machine on my laptop is fast enough to produce the same auto-tag for two distinct publish operations in integration tests. I.e. it runs two invocations of `cvmfs_server publish` in the same wall-clock second, generating the same auto-tag twice.
This checks if an auto-tag is already in use and adds a running number to the tag name in this case. Perhaps this can only happen with scripted setups, because a human cannot type fast enough. ;-)
=> FIX: Race for Ambiguous Auto Tag Names

test/src/597-libcvmfs/main, test/src/597-libcvmfs/main.cc
This test creates the typical integration test structure and compiles a binary whose source is included in the same folder. This binary actually tests if the repositories contain the required structure, and it is compiled against libcvmfs.a
=> Add libcvmfs integration tests (597)

cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/util.cc, cvmfs/util.h, test/src/597-graft/main
This PR adds support for 'grafted' files - files that are added to the repository without being physically present on the scratch filesystem.
For a given file $FOO in a directory, we denote a grafted file by the presence of .cvmfsgraft-$FOO in the same directory.  The .cvmfsgraft- file is line-oriented with key-value pairs.  Currently, two keys are recognized:
size=<integer size>
checksum=<checksum value>
The checksum must be a valid CVMFS checksum, following CVMFS checksumming conventions (such as having suffixes and being applied to the compressed contents).
If grafting is used, it is the responsibility of the repository maintainer to stage the files into the repository.
See CVM-908 for more information.
=> Support for "grafted" files

cvmfs/cvmfs_server
OverlayFS v22 is the version that went into the 3.18 kernel; it requires a `workdir` specification on mount and uses character devices for whiteouts. Before (like on ubuntu) it used symlinks for whiteouts and doesn't mount when a `workdir` is specified. Hence, we need to distinguish them.
Unfortunate I didn't find a way to get the version number of OverlayFS, hence I use the kernel version as an indicator.
=> FIX: Detect and React on OverlayFS older than V22

cvmfs/cvmfs_server
This has been [recently introduced](https://github.com/cvmfs/cvmfs/pull/1130) when using `cvmfs_server tag` internally in `cvmfs_server publish`. When running the publish command in debug mode like so:
```CVMFS_SERVER_DEBUG=1 cvmfs_server publish```
it produces a (de facto) deadlock, since gdb prompt is opened but connected to `/dev/null`.
It's _not_ a good idea to sub-call `cvmfs_server` commands in other `cvmfs_server` commands! Furthermore it turns out that there already is a helper-function doing the necessary tag existence check.
=> FIX: Deadlock in debug-enabled cvmfs_server publish

cvmfs/sync_union.cc
When recursively deleting directories in `SyncMediator`, `SyncUnion` might check directories for *opaqueness* that are not actually existent anymore. For AUFS this wasn't a problem, since it was anyway checking for existence of a flag file. However, the OverlayFS implementation crashes as it tries to look for an extended attribute on a non-existent path.
=> FIX: Opaque Directory Check Crashes for Non-Existent Dirs

cvmfs/cvmfs_server
Adding another debug mode to `cvmfs_server`. Can be used when `gdb` produces Heisenbugs or if only the verbose debug output is of interest.
```bash
CVMFS_SERVER_DEBUG=3 cvmfs_server XXXX
```
=> Allow for Debugging Runs of cvmfs_server without Attaching gdb 

vagrant/provision_slc6.sh
Two things:
1. update packages before installing AUFS enabled kernel
2. add `libcap-devel` to the game
=> FIX: SLC6 Vagrant Provision

cvmfs/platform_linux.h, cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h, cvmfs/sync_union.cc, cvmfs/sync_union.h
Turns out, that the convenience macro `CAP_IS_SUPPORTED()` is not available in `<sys/capability.h>` on older Linux versions. We'll just skip this sanity-check on these platforms and live with the less descriptive error message if the capability actually is not supported - which is highly unlikely anyways.
**Note:** This builds on [Refactor: SyncItem Factory Method](https://github.com/cvmfs/cvmfs/pull/1149) and [FIX: Hardlink Check and Preprocessing in OverlayFS](https://github.com/cvmfs/cvmfs/pull/1150).
=> FIX: CAP_IS_SUPPORTED is not available on RHEL < 7

cvmfs/platform_linux.h, cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h, cvmfs/sync_union.cc, cvmfs/sync_union.h
This fixes a [code smell](https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/sync_item.h#L64) that was already marked as such since July. Namely, a `SyncItem` has methods `IsWhiteout()` and `IsOpaqueDirectory()` that depend on `SyncUnion` to set these properties for each and every `SyncItem` object. Before they might not return the right value. Now, *OverlayFS* added another such property - namely `HasHardlinks()`. Unfortunately also `SyncMediator` was *silently* creating `SyncItem` objects where non of those properties where actually set correctly by `SyncUnion` which broke the OverlayFS implementation.
Naturally only `SyncUnion` can figure out those properties of the `SyncItem` objects, as they depend on the union file system implementation. Therefore this refactors `SyncItem`, `SyncUnion` …
=> Refactor: SyncItem Factory Method

cvmfs/platform_linux.h, cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h, cvmfs/sync_union.cc, cvmfs/sync_union.h
This fixes a problem with hardlink handling in OverlayFS where certain `SyncItem`s where skipped due to the *silent* creation of `SyncItem` objects inside `SyncMediator`.
*Note:* This depends on the pull request [Refactor: SyncItem Factory Method](https://github.com/cvmfs/cvmfs/pull/1149).
=> FIX: Hardlink Check and Preprocessing in OverlayFS

ci/build_on_docker.sh, ci/docker/opensuse13_x86_64/build.sh, ci/docker/sles11_x86_64/build.sh
Removes the docker containers after they have been finished executing.
=> FIX: use `docker run --rm=true` for cleanup

cvmfs/sync_union.cc
Turns out that `cap_set_flag()` requires a non-const pointer to the flag it should set. Starting from RHEL 6 this changed to `const`.
`int cap_set_flag(cap_t, cap_flag_t, int, cap_value_t *, cap_flag_value_t);`
`int cap_set_flag(cap_t, cap_flag_t, int, const cap_value_t *, cap_flag_value_t);`
=> FIX: Inconsistent const-ness of cap_value_t* in cap_set_flag()

test/src/501-changerepo/main, test/src/503-deletedirrecursive/main, test/src/504-opaquedir/main, test/src/505-createnested/main, test/src/506-removenested/main, test/src/507-removeintermediatenested/main, test/src/516-createsnapshotadvanced/main, test/src/517-touchnested/main, test/src/520-history/main, test/src/521-createmultiplesnapshots/main, test/src/525-bigrepo/main, test/src/541-preloadcache/main, test/src/547-createintermediatenested/main, test/src/548-createintermediatenested2/main, test/test_functions
Picking the low hanging fruits, mainly adapting test cases for the differing hard link semantics of OverlayFS. There are some more failing test cases in the above mentioned range that are either intrinsically failing with OverlayFS and/or need a bit more adaption to the newer httpd on Fedora 22. More to come in other Pull Requests...
=> FIX: Integration Tests 500 to 559 for OverlayFS 

test/src/597-libcvmfs/main
The test cases compiles a small test program but on Fedora 22 one needs to link against `-lcrypto` when doing so (fixed).
Also I've refactored the test case a little, to make it more resilient against failure (i.e. using a cleanup-trap for reliable test repository destruction). Finally I added a couple of debug print outs and return statements to make the test case fail in case of problems.
=> FIX: Integration Test 597 (libcvmfs)

cvmfs/cvmfs_server
Catalin just found a bug in the Stratum1 URL handling when creating a fresh replica on S3, like so:
```bash
cvmfs_server add-replica -w http://path/to/S3 -u S3,/tmp,test.cern.ch@/etc/path/to/s3.conf http://path/to/stratum0 /etc/path/to/pubkey.pub
```
TL;DR: When a custom upstream string (i.e. `-u S3,...`) is specified, the Stratum1 base-URL provided with `-w` is not properly added to the configuration file. The problem is a convoluted if-statement which I fixed and refactored a bit in this Pull Request.
=> FIX: Stratum1 URL Handling

cvmfs/sync_union.cc, cvmfs/sync_union.h
Trying to publish some hardlinks in AUFS since quite a while. Turns out that this was broken by some adaptions done for OverlayFS.
The bug is two-fold:
1. `SyncUnion::SupportsHardlinks()` needs to be declared `virtual`
2. `SyncMediator::RegisterUnionEngine()` must not be called in `SyncUnion`'s c'tor because at this stage the polymorphism for `SyncUnion::SupportsHardlinks()` doesn't work yet as `SyncUnionAufs`'s c'tor didn't run yet.
=> FIX: SyncUnion::SupportsHardlinks() must be called virtually

cvmfs/cvmfs_server, test/src/556-customupstream/main
This is a follow up for [FIX: Stratum1 URL Handling](https://github.com/cvmfs/cvmfs/pull/1174). When revisiting this today I found a similar problem in `cvmfs_server mkfs`. Therefore I added a regression test (no. 556) and found a bug introduced by yesterday's pull request.
Furthermore this applies mild refactorings:
* introducing `mangle_local_cvmfs_url()` analogous to `mangle_s3_cvmfs_url()`
* proper quotation for invocations of `create_config_files_for_new_repository()`
=> FIX: Stratum0/1 Custom URL Handling

cvmfs/sql.h, cvmfs/sql_impl.h, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_migrate.h, test/unittests/t_sqlite_database.cc
This changes `cvmfs_swissknife migrate` to upload nested catalogs only if they have been changed during the migration step. The rationale being that OverlayFS will need a catalog migration when a previous AUFS-based repository is imported.
To figure out if a catalog database has been modified, I've added `Database<>::GetModifiedRowCount()` along with a unit test case that figures out how many databases rows have been changed since the SQLite database has been opened.
Furthermore, the migration code of `cvmfs_swissknife` needs to step over unmodified catalogs which required an adaption in the concurrent processing. In detail, I replaced two individual `Future<>`s in `PendingCatalog` by a new one (cf. `Future<bool> was_modified`) that acts both as a modification flag and a signal for …
=> Refactor: Catalog Migration only Commits Changed Catalogs

test/src/519-importlegacyrepo/main, test/src/550-livemigration/main, test/src/563-garbagecollectlegacy/main, test/src/568-migratecorruptrepo/main, test/test_functions
Since our legacy (2.0.x) guinea-pig repository contains hardlinks these tests fail on OverlayFS. This adds invocations to `cvmfs_server eliminate-hardlinks` accordingly to make the tests succeed. Apart from that their are some other minor tweaks necessary in the OverlayFS case. For example to `grep` for the warning generated by `cvmfs_server import` when importing with OverlayFS.
=> FIX: Test Failures related to OverlayFS and Legacy Imports

cvmfs/cvmfs_server
This modernises the `cvmfs_server migrate` code a little bit. Mainly removing global-state dependency and allowing for `X.Y.Z-B`-style version strings. The latter is needed to distinguish between the 2.2.0-0 prerelease and the upcoming 2.2.0-1 full release.
=> Refactor: Server Migration Code

cvmfs/cvmfs_server
This adds a migration step for CVMFS 2.2.0 stratum0 repositories. I am using the absence of `CVMFS_SERVER_CACHE_MODE` to distinguish between 2.2.0-0 and 2.2.0-1 releases. Hence: The 2.2.0-1 release will detect 2.2.0-0 repositories as 'incompatible'.
**Note:** This builds on top of [Refactor: Server Migration Code](https://github.com/cvmfs/cvmfs/pull/1186)
=> Feature: Stratum0 Migration Path for CVMFS 2.2.0-1

cvmfs/cvmfs_server
Sorry, tiny little follow-up for [Feature: Stratum0 Migration Path for CVMFS 2.2.0-1](https://github.com/cvmfs/cvmfs/pull/1187).
=> FIX: Migration from 2.2.0-0 to 2.2.0-1

cvmfs/cvmfs_server, test/src/582-autorepairmountpoints/main
This fixes a bug in the mountpoint auto-repair feature [found by the ATLAS nightlies repository](https://sft.its.cern.ch/jira/browse/CVM-918). Concretely if `/var/spool/cvmfs/.../rdonly` is not mounted but `/cvmfs/...` is fine, `cvmfs_server` will try to mount CVMFS *underneath* a mounted union file system. Of course this doesn't have the desired effect.
I fix it by first checking both `.../rdonly` and `/cvmfs/...` and temporarily unmounting `/cvmfs/...` in the situation described above. Furthermore this extends integration test case 582 both for detecting this regression and to make it check the actual repository content more resiliently.
Finally this changes the default behaviour of `cvmfs_server` to always try the auto-repair if `CVMFS_AUTO_REPAIR_MOUNTPOINTS` is not explicitly set to …
=> FIX: Mountpoint Auto Repair Failed when only CVMFS was Broken

cvmfs/cvmfs_server
This replaces `fuser` by `lsof` to print a list of processes occupying a mountpoint. The rationale being that `fuser` (for some reason) doesn't print usable information on OverlayFS (kernel 4.2.0), i.e. it claims that the mountpoint is occupied by the kernel itself. O.o
This fixes integration test case 570 for the bleeding edge OverlayFS on Ubuntu 15.10.
=> FIX: Use lsof instead of fuser for Busy Mountpoints

test/src/514-changechunkedfile/main, test/src/533-volatilecacheset/main, test/src/537-symlinkedbackend/main, test/src/554-defragcatalogrowid/main, vagrant/provision_ubuntu.sh
This fixes the integration test 537 for OverlayFS's missing hardlink awareness. Furthermore it adds a couple of opportunistic checks for the availability of the `sqlite3` utility to make those fail gracefully in case it's not installed.
Finally this adds the following missing packages for the Ubuntu vagrant provisioning script:
* sqlite3
* libapache2-mod-wsgi
* bc
* default-jre-headless
=> FIX: Integration Tests and Ubuntu Provisioning for OverlayFS

cvmfs/sql_impl.h
Competing against José's Java implementation I found this little tweak: If an SQLite database is opened read-only, one can set `PRAGMA locking_mode=EXCLUSIVE`. However, I am not entirely sure about the implications - therefore RFC. :-)
Regarding the [SQLite documentation](http://sqlite.org/pragma.html#pragma_locking_mode) this implies that no two processes can access the SQLite file at the same time anymore. In `NORMAL` mode, SQLite acquires and releases a file-lock for every read operation. Now: Do we rely on accessing a single SQLite database file read-only in multiple processes concurrently?
Mini-Benchmark:
* traversing all catalog entries in **boss.cern.ch** (~1.6 million entries)
* only considering the actual traversal (no catalog loading, initialisation, ...)
With …
=> RFC: Improved Database Reading by using Exclusive Locking

cvmfs/cvmfs_config
No integration with autofs on OS X, hence the `cvmfs_config` script shouldn't try to tamper with it.  This problem was introduced by fixing `cvmfs_config` for Arch Linux.
=> FIX: autofs tab handling on os x

packaging/debian/cvmfs/control, packaging/rpm/cvmfs-universal.spec
This adds `lsof` as a package dependency of `cvmfs-server` and fixes a dependency problems on Fedora 22.
=> FIX: Package Dependencies

cvmfs/sync_item.cc
Due to a 'harmless' AUFS bug the CernVM-FS server was misbehaving, when removing (exactly) one file  (creating a whiteout) in a directory and later renaming the very directory (producing a recursive up-copy). 
As discussed in [CVM-880](https://sft.its.cern.ch/jira/browse/CVM-880) and done in #1022 we must ignore whiteouts in newly created (or up-copied) directories to prevent this crash. However, #1149 centralised the creation of `SyncItem`s in a way that this warning fires due to the above-mentioned AUFS bug.
This keeps the warning print-out but removes the `abort()`. At the same time it marks the created `SyncItem` bogus (by setting it's type to `kItemUnknown`) which should crash the publishing down the road if there is actually an inconsistency.
Testing for the win!
=> FIX: Regression of Integration Test 593

test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/common_setup.sh, test/cloud_testing/platforms/common_test.sh, test/cloud_testing/platforms/fedora22_x86_64_setup.sh, test/cloud_testing/platforms/slc5_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/cloud_testing/platforms/ubuntu_x86_64_setup.sh
This adds `cvmfs-devel` to the list of libraries to be tested. Furthermore it installs `g++` on ubuntu to fix integration test 597.
=> TEST: CernVM-FS Library Package

add-ons/tools/download_catalog_graph.py
This fixes `add-ons/tools/download_catalog_graph.py` to work with the latest `python-cvmfsutils` code base (i.e. including [this pull request](https://github.com/cvmfs/python-cvmfsutils/pull/9)).
The idea of the fix is to remove the (deprecated) `Catalog::save_to()` call and replace it by a custom `DownloadingRemoteFetcher`. This `Fetcher` implementation 'wire-taps' into the `Repository`s fetch operations and duplicates all downloaded files into a given destination directory. Therefore, the actual business logic of this script only traverses all catalogs that must be downloaded and closes them immediately.
=> FIX: Catalog Graph Download Python Script

CMakeLists.txt, externals/c-ares/src/configureHook.sh, externals/pacparser/src/makeHook.sh, test/unittests/CMakeLists.txt
This attempts to fix the CernVM-FS build on OS X El Capitan. Notably this *does not* mean that it also works. Furthermore a successful build depends on OpenSSL installed from `brew` and XCode's CLTs:
```bash
brew install openssl
brew link --force openssl
xcode-select --install
```
* Fix CMake Warning regarding OS X rpath
* Fix CMake Warning for unittest build dependency
* Omit test execution of pacparser external on build (fails on OS X El Capitan)
Unit test set works mostly, except three test cases (see below). Likely these failures coincide with the failing c-ares tests. Left for TODO right now.
Failing unittests:
* T_Dns.CaresResolverSearchDomain
* T_Dns.CaresResolverMany
* T_Dns.NormalResolverCombined
=> FIX: OS X El Capitan Build

CMakeLists.txt, cvmfs/CMakeLists.txt, cvmfs/cvmfs_config, cvmfs/platform_linux.h, cvmfs/platform_osx.h, mount/CMakeLists.txt, mount/mount.cvmfs.cc, test/unittests/CMakeLists.txt, test/unittests/t_platforms.cc
This (technically) fixes support for OS X El Capitan with CernVM-FS being installed into `/usr/local` to coexist with Apple's [SIP](https://support.apple.com/en-us/HT204899). For that, some parts of the CernVM-FS client need to become slightly relocatable.
Fixed issues:
* `cvmfs_config` script is aware of it's installation location and takes it into account when looking for other CernVM-FS components
* internal platform abstraction can determine operating system version (OS X version on mac vs. kernel version on Linux)
* mount helper additionally looks into `/usr/local/bin` for `cvmfs2` binary when running on OS X >= 10.11
* `cvmfs_config` can initially load `config.sh` both from `/etc/cvmfs/` and `/usr/local/etc/cvmfs` for bootstrapping the system with `cvmfs_config setup`
* …
=> FIX: OS X El Capitan

CMakeLists.txt, cvmfs/CMakeLists.txt, mount/CMakeLists.txt
This allows most of CernVM-FS's build artefacts to be installed under a user-defined install prefix. We need this, to support OS X El Capitan with enabled [SIP](https://support.apple.com/en-us/HT204899).
Note that this doesn't yet include any production code changes to actually support relocatable installations.
=> Allowing to Install CVMFS outside of /usr

cvmfs/cvmfs_server, test/src/591-importrepo/main
I was struggling with `cvmfs_server import` of a given repository backend directory for more than an hour today. Turns out that the command failed ungracefully because the **/srv/cvmfs/.../data/txn** directory was missing. This extends the sanity checks in `cvmfs_server import` to check more aspects of CernVM-FS backend directories to be imported. In the hope it will save me (and potentially others) time down the road.
Also it comes with an extension to integration test 591 to provoke the added error messages.
=> FIX: `cvmfs_server import` backend sanity check

cvmfs/cvmfs_server, test/src/591-importrepo/main
Same as yesterday, took long enough to figure this out by myself. So let's better make `cvmfs_server` check it when importing legacy repositories.
*Note:* I've done a small refactoring to safe some code lines for the different backend items to be checked.
=> FIX: `cvmfs_server import` Checks for Wrong Backend Directory Ownership

cvmfs/cvmfs_server, test/src/603-automaticgarbagecollectionrace/main
This fixes a garbage collection bug described in [CVM-942](https://sft.its.cern.ch/jira/browse/CVM-942). Under a certain constellation the automatic garbage collection during `cvmfs_server publish` could remove data objects that are referenced in the just-published revision.
The fix performs the actual revision commit (i.e. manifest signing and publishing) in `cvmfs_server publish` before the automatic garbage collection run. An updated manifest is published as soon as the automatic garbage collection has finished. This second "commit" does not increase the repository's revision but only updates the history database.
*Note:* This contains a regression test that reproduces the bug.
=> FIX: Automatic Garbage Collection misses Latest Revision

test/unittests/t_util.cc
Now the comparison is made within a maximum of two seconds between both values
=> FIX T_Util.RfcTimestamp

test/unittests/t_fetch.cc, test/unittests/t_uploaders.cc, test/unittests/testutil.h
This adapts the API changes of both `SpoolerDefinition::SpoolerDefinition()` and `Fetcher::Fetch()` in the unit testing code. That should fix the [latest Jenkins failure](https://phsft-jenkins.cern.ch/view/CVMFS/job/CvmfsFullBuildDocker/67/).
=> Fix api changes

cvmfs/cvmfs_config
This allows CernVM-FS 2.2.0 to be installed into `/usr/local` on older OS X versions. Furthermore it fixes the sudoers file adaption on OS X if CernVM-FS was installed into `/usr/local`.
=> FIX: OS X installation and relocatability

cvmfs/CMakeLists.txt, cvmfs/cvmfs_rsync, packaging/debian/cvmfs/control, packaging/debian/cvmfs/cvmfs-server.install, packaging/rpm/cvmfs-universal.spec, test/src/604-cvmfsrsync/main
As described in [CVM-814](https://sft.its.cern.ch/jira/browse/CVM-814).
Requires that rsync be installed on the test machines.   How do I ensure that?
=> add cvmfs_rsync to cvmfs-server package

cvmfs/swissknife_history.cc, test/src/604-resurrectancientcatalog/main, test/test_functions
This is related to a pretty [ancient known issue](https://sft.its.cern.ch/jira/browse/CVM-252) that after a repository was migrated from 2.0.x-style to 2.1.x-style catalogs, rolling back too far might 'break' the repository. The problem is a bit constructed, but possible like so (see integration test also):
1. take a 2.0.x repository
2. migrate it to 2.1.x-style catalogs (`cvmfs_server import -l ...`)
3. create a tag to an old-style catalog revision (`cvmfs_server tag -a old -h <old clg hash>`)
4. roll back to the **old** tag.
5. Congrats, your 2.1.x repository is now populated by 2.0.x catalogs
6. cry a lot
This patch introduces a check to avoid rolling back to such tags.
=> FIX: Avoid Rollback to Outdated Catalog Schemas

cvmfs/catalog_sql.cc
Just so that our future selves will remember that this bug might need a fix in the far future.
=> Doc: Reminder of CVM-252 (outdated rollback)

externals/python-geoip/src/makeHook.sh
Used this docker container to debug the build:
```bash
host$# sudo docker run --rm -t -i pritunl/archlinux:latest /bin/bash
arch$# pacman -S cmake gcc make patch fuse python unzip
```
The `makeHook.sh` of the geoip external didn't properly find the build result on ArchLinux. Should work now.
=> FIX: Build GeoIP External on ArchLinux

cvmfs/cvmfs_server, packaging/debian/cvmfs/control, packaging/rpm/cvmfs-universal.spec
This erases the use of `sudo` from `cvmfs_server` as requested in [CVM-245](https://sft.its.cern.ch/jira/browse/CVM-245). Impersonating a specific user is now done either by `runuser` or (if this is not available) using `su`. Turns out that older versions of Ubuntu don't provide `runuser`.
Furthermore I found an orphaned un-config command that tried to remove `/etc/sudoers` configuration that was actually not done anymore since the rise of `cvmfs_suid_helper`.
=> FIX: Remove Use of `sudo` in `cvmfs_server`

cvmfs/cvmfs_config, test/src/064-fsck/main, test/test_functions
Adds `cvmfs_config fsck` that runs `cvmfs_fsck` on all cache directories induced by `CVMFS_REPOSITORIES`.  Includes integration test.
Also:
- Print parameters in alphabetical order in `cvmfs_config showconfig`
- Some smallish re-arrangements in `cvmfs_config`
- Fix for `cvmfs_umount` in the integration test utils
=> Add cvmfs_config fsck command (CVM-371)

cvmfs/cvmfs_server, test/src/606-gracefulrmfs/main, test/test_functions
This allows to remove a repository without deleting its backend storage and keychain. They are just left behind and can conveniently be re-imported. Of course it comes with an integration test case.
=> Feature: `cvmfs_server rmfs -p` to Preserve Repository Data

cvmfs/cvmfs_server, test/common/mock_services/http_server.py, test/src/607-noapache/main
This allows to skip the Apache configuration when running `cvmfs_server mkfs`, `import` or `add-replica`. All of those commands can be called with `-p` for that purpose. An integration test is added that uses a minimal python webserver as a backend instead of Apache.
=> Feature: Skip Apache Configuration/Reload if Requested

cvmfs/cvmfs.cc
As a result, if `CVMFS_SERVER_URL` is empty, the error from the downloader is "malformed url" instead of "connection problem".  This leads to immediate failure as it is supposed to be (CVM-892).
=> Don't use localhost as default stratum 1 (CVM-892)

test/unittests/t_util.cc
Another fix for this test, which look pretty problematic.
This time it directly gets the milliseconds from time(NULL), which is the same done in the tested method.
=> FIX: T_Util.Rfctimestamp

cvmfs/cvmfs_server
Apparently there are various different scenarios how mounting both `/var/spool/cvmfs/$repo/rdonly` and `/cvmfs/$repo` on stratum0s can fail during system boot. Usually this results in the boot process being interrupted.
For example:
* `/var/spool/cvmfs` not mounted yet
* Apache not started yet
* mixed up order of mounting `.../rdonly` and `/cvmfs/...`
* ... probably more
I couldn't really wrap my head around what exactly happens in the different scenarios, so this is more of an RFC-Pull Request. Anyway, by just adding **noauto** to the CVMFS `/etc/fstab` entries this issue would be easily (and reliably) fixable. Mounting of both `.../rdonly` and `/cvmfs/...` would happen (pretty much transparently) on the first `cvmfs_server` invocation through the auto-repair-mountpoint feature of CVMFS. …
=> FIX/RFC: Do not Mount CVMFS Stratum0's on system boot

cvmfs/download.cc, test/common/mock_services/http_400.sh, test/src/065-http-400/main, test/test_functions
The Geo-API can return a 400 response code, which should trigger a host fail-over and not a proxy fail-over.  Integration test and mock HTTP server included.
=> FIX: treat HTTP 400 return codes as host failure (CVM-819)

CMakeLists.txt
From the [CMake documentation](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html), `CMAKE_INSTALL_PREFIX` defaults to `/usr/local` on Unix. However, we do not plan to relocate CernVM-FS on Linux. I've seen this behaviour on my Ubuntu machine.
=> FIX: Install Path on Linux Defaults to /usr/local

cvmfs/cvmfs_server
Since we rely on `CVMFS_AUTO_REPAIR_MOUNTPOINT=true` when rebooting a release manager machine since [this pull request](https://github.com/cvmfs/cvmfs/pull/1168), this config is now enforced during migration from previous versions.
=> FIX: Migration to 2.2.0 enforces CVMFS_AUTO_REPAIR_MOUNTPOINT

test/unittests/t_util.cc
The (I hope) last fix for this test. Navigating through the documentation and the own time.h file I've seen there is a variable called timezone that represents the seconds of difference with respect to GMT, which is exactly what was left in the test.
Tested on the ARM fedora machine that was having problems with this issue, and in a standard SLC6. According to http://stackoverflow.com/a/5157134/2352087 this should be a platform-independent solution.
=> FIX: use timezone variable in T_Util.RfcTimestamp

cvmfs/cvmfs_server, test/src/591-importrepo/main
This implements [a feature request](https://sft.its.cern.ch/jira/browse/CVM-865) from @DrDaveD. It allows to create a fresh repository signing key and an associated certificate on `cvmfs_server import` like so:
```bash
cvmfs_server import -r -t atlas.cern.ch
```
Both switches are required for that to work `-t` is enabling the fresh creation of repository signing key and certificate while `-r` will rewrite the repository's whitelist. Note that `-r` can also be used alone (it was already implemented), for example if an expired whitelist needs to be imported. Both cases require the repository's masterkey naturally.
I didn't write a completely new integration test but extended 591 for that purpose.
=> Feature: Create Fresh Repository Signing Keys on `cvmfs_server import`

cvmfs/cvmfs_server
This adds a check for enabled autofs on `/cvmfs` before trying to open a transaction with `cvmfs_server transaction`. Otherwise the (potential) `CVMFS_AUTO_REPAIR_MOUNTPOINT` feature fails with an unspecific error message. Let alone that autofs anyway needs to be switched off for `/cvmfs` on the server.
=> FIX: Check autofs Before Opening Transaction

cvmfs/swissknife_pull.cc
This adds some logic to produce more suggestive error messages when running \`cvmfs_server snapshot\`. The actual content of those is of course up for discussion.
=> FIX: Suggestive Snapshotting Network Errors

ci/docker/sles11_x86_64/build_internal.sh, ci/run_on_docker.sh
Turns out that `zypper` [contains a bug](https://bugzilla.opensuse.org/show_bug.cgi?id=956480) and reports an error code when running in download-only mode. It was fixed recently, but we need to work around it. Furthermore this contains minor fixes for the adaptions done to `run_on_docker.sh`.
=> FIX: SLES 11 Docker Recipe

cvmfs/cvmfs_server
This DRYs up a couple of things in \`cvmfs_server\`. I need those changes for the implementation of [CVM-860](https://sft.its.cern.ch/jira/browse/CVM-860) but want to keep them out of the way, to keep the change set sleek and readable.
=> Refactor: DRY up Some Minor Things in cvmfs_server

cvmfs/cvmfs_config, test/src/066-killall/main
This is supposed to get out of stuck situations, e.g. when `cvmfs_config reload` hangs.  It kills all `cvmfs_config` and `cvmfs2` processes and clears /var/run/cvmfs/
@traylenator @DrDaveD: I'd appreciate a second look on the bash code.
=> Add `cvmfs_config killall` command

ci/docker/cc7_x86_64/Dockerfile, ci/docker/fedora22_x86_64/Dockerfile, ci/docker/slc5_x86_64/Dockerfile, ci/docker/slc6_x86_64/Dockerfile, cvmfs/cvmfs.cc, cvmfs/download.cc, cvmfs/voms_authz/voms_authz.cc, cvmfs/voms_authz/voms_cred.cc, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh, test/src/600-securecvmfs/main, test/src/600-securecvmfs/test600.cvmfs.secure.conf
While working on it I discovered a problem with the alternative catalog path: we have the option to set `CVMFS_ROOT_HASH` to load a very specific catalog.  This circumvents downloading the manifest, so the client doesn't know it should look under a different path for the root catalog.
This feature is used with the clients that provide the read-only branch of a cvmfs server.
We could solve it by introducing another parameter, e.g. `CVMFS_ROOT_CATALOG_PATH`.  Not sure yet if this is the best way to deal with it.
=> FIX: enable HTTPS integration test on CernVM

cvmfs/cvmfs_server
Turns out that my JSON rendering was choking when there is not a single repository and/or replica configured. Oh, I love bash!
=> FIX: Updating JSON File Without Installed Repositories

Vagrantfile, vagrant/provision_osx.sh
Enables the creation of Mac OS X Yosemite as a Vagrant VM
=> Enable OSX in Vagrant

cvmfs/cvmfs_server, cvmfs/swissknife_check.cc, cvmfs/swissknife_check.h, test/src/611-subtreecheck/main
This allows `cvmfs_server check` to only go through a subtree of the repository. The idea is, to allow for quicker turn-around time when debugging problems. Instead of always checking everything, consecutive checks can be done more focussed to the actually affected catalogs.
=> Feature: `cvmfs_server check -s /path/to/nested/catalog` for Partial File System Checks

cvmfs/cvmfs.cc, cvmfs/dns.cc, cvmfs/download.cc, cvmfs/download.h, test/common/mock_services/silent_socket.py, test/src/017-dnstimeout/main
Introduces `CVMFS_DNS_RETRIES` and `CVMFS_DNS_TIMEOUT` (which are only affective for resolving proxies).  Contains also a fix to the download manager when a DNS name cannot be resolved.  Multiple fixes to the DNS timeout integration test.
=> Allow for configuration of dns timeout and retry (CVM-875)

cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/catalog_rw.cc, cvmfs/catalog_rw.h, cvmfs/cvmfs.cc, cvmfs/cvmfs_server, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, test/src/611-idleclient/main, test/src/612-setttl/main, test/test_functions
New catalogs cannot immediately be applied but only after draining the kernel caches.  The alarm signal handler that indicates an expired root catalog now triggers (via another thread for signal safety) looking for a new catalog and, if there is one, starting of the drainout period.  
Previously, the alarm signal would make the first subsequent file system call to start the drainout period and only after the drainout period apply a new catalog.  That did lead to strange situations in which idle mount points continued with an old catalog.
Because it made testing easier, this PR also adds a means to specify the repository ttl during publish.  To do so, the new `CVMFS_REPOSITORY_TTL` from server.conf is parsed.
=> Immediately pick up new catalogs after idle period (CVM-636)

cvmfs/file_processing/processor.cc, test/src/510-filechunks/main, test/unittests/t_chunk_detectors.cc
This fixes [CVM-957](https://sft.its.cern.ch/jira/browse/CVM-957) where a large file has a file size that is exactly a multiple of `CVMFS_MAX_CHUNK_SIZE` and does not contain any XOR32-based chunk cut marks. This is very unlikely to happen but I stumbled over it by accident.
I fix it by checking the output of `ChunkDetector` to be lower than `File::size()`. This is not an optimal solution, since it is more of a patch around the root cause. However, `ChunkDetector` is designed to take a stream and it doesn't know how much data will come. Hence, I cannot easily check for *EOF* inside the `ChunkDetector`.
**Note:** This contains [TEST: Regression in File Chunking](https://github.com/cvmfs/cvmfs/pull/1298).
=> FIX: Publishing Crashes when Large File Does just Fit into Chunk Sizes

test/src/510-filechunks/main, test/unittests/t_chunk_detectors.cc
Found that totally by chance while testing a different thing. Apparently file chunking fails with file sizes that are exactly a power of two. I expect something like an off-by-one error or similar. Possibly also in conjunction with the `CVMFS_MAX_CHUNK_SIZE`. I didn't look into it yet, this is more a TODO regression test.
=> TEST: Regression in File Chunking

cvmfs/CMakeLists.txt, cvmfs/clientctx.cc, cvmfs/clientctx.h, test/unittests/CMakeLists.txt, test/unittests/t_clientctx.cc
This PR is supposed to replace #1309.  Instead of passing the context through the call stack, I'd prefer to store the information in thread local storage at the beginning of a file system callback.  It can then be retrieved by the fetcher when needed.
There is a risk of bugs where mistakenly someone else's context is used but we have only very few, well-known file system callbacks.  So we should be able to get this right.
=> Modified: support for client context

cvmfs/catalog_mgr_rw.cc, cvmfs/file_processing/file.cc, cvmfs/file_processing/file.h, cvmfs/file_processing/file_processor.cc, cvmfs/file_processing/file_processor.h, cvmfs/file_processing/io_dispatcher.cc, cvmfs/swissknife_sign.cc, cvmfs/upload.cc, cvmfs/upload.h, cvmfs/upload_facility.h, cvmfs/upload_local.cc, cvmfs/upload_local.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h, test/unittests/CMakeLists.txt, test/unittests/t_fetch.cc, test/unittests/t_file_processing.cc, test/unittests/t_garbage_collector.cc, test/unittests/t_upload_facility.cc, test/unittests/testutil.h
The `altpath` mechanism has been superseded by the new bootstrapping method, already in devel.  This switches the CVM-904 branch to use the bootstrapping.
=> Remove use of 'altpath'

cvmfs/libcvmfs_int.cc
Without this, both download managers try to register the same
counters and trigger an assert (only when using libcvmfs).
This now initializes the external download manager for libcvmfs and fuse the same way.
=> Initialize external download manager counters.

cvmfs/sync_union.cc
When the union traversal finds a subdirectory, it creates a separate
filesystem crawler to process the new subdirectory.  The latter is
a different object whose code path doesn't set the external data
property.  Move the setting of this property to a common function for
both.
Discovered this when doing some large-scale testing of grafting.  Other than this problem, all is looking well!
=> Fix setting of external data for nested directory creation.

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_mgr.h, cvmfs/catalog_mgr_impl.h, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/catalog_sql.cc, cvmfs/catalog_sql.h, cvmfs/cvmfs_server, cvmfs/logging.cc, cvmfs/logging_internal.h, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, test/unittests/t_catalog.cc, test/unittests/t_object_fetcher.cc
Nothing is plumbed to actually use this on the client side, but
the VOMS authz information is now stored in the database.
Another part of the prep work for CVM-904.
When merged, please merge `devel` back into `CVM-904` so I can prep the next round of PRs.
=> Add infrastructure for storing / fetching VOMS authz.

cvmfs/voms_authz/voms_authz.cc, test/src/600-securecvmfs/main, test/unittests/t_voms.cc
In case two VOs (purposely or accidentally) start using overlapping
group names, require the VOMS authz to explicitly name which VO is
being used.
For example, the LIGO VO issues attributes of the form /ligo; it
appears it's not safe to assume the VO name is part of the group
name.
Includes updated unit and integration tests.
=> CVM-904 - Require explicit VO name

cvmfs/CMakeLists.txt, cvmfs/cvmfs_talk, cvmfs/platform_linux.h, cvmfs/platform_osx.h, cvmfs/quota.cc, cvmfs/quota.h, cvmfs/statistics.cc, cvmfs/statistics.h, cvmfs/talk.cc, test/src/034-cachecleanup/main, test/unittests/t_cache.cc, test/unittests/t_quota.cc, test/unittests/t_statistics.cc
Let the quota manager keep track of cleanup events over time.  
Adds helper to query monotonic time with second resolution.  Monotonic time is platform-specific.
Introduces the new `Recorder` class.  The recorder counts events in certain fixed interval bins and for a certain fixed maximum time window in the past.  Implemented as a ring buffer.  Multiple recorders can be put together with more coarse-grained interval bins as the time window in the past increases.  This way, we can keep track of the last 4 days with ~1.5kB memory that is allocated as a block.
=> Add `cvmfs_talk cleanup rate` command (CVM-270)

packaging/rpm/cvmfs-universal.spec
Turns out that comments in spec files must start at the beginning of a line. Sigh!
=> FIX: Syntax Error in RPM spec file

cvmfs/CMakeLists.txt, test/unittests/CMakeLists.txt
This fixes the `CMake` configuration process when `voms-devel` is not installed.
=> FIX: Don't rely on VOMS Availability

test/unittests/CMakeLists.txt
This is a follow up for #1345 and fixes the build of `cvmfs_unittests` both for installed and not-installed `voms-devel`.
=> FIX: cvmfs_unittests Compile Depends on VOMS

test/unittests/t_compressor.cc
On ARMv7 (32 bit) `size_t` is an `unsigned int` whose pointer cannot be (implicitly) casted to `uint64_t` (aka. `unsigned long long int`). Making this explicit in one of the unit tests, should repair the build.
=> FIX: Build on ARMv7 (due to size_t type mismatch)

cvmfs/compression.cc, cvmfs/compression.h, cvmfs/cvmfs.cc, test/src/597-graft/main, test/src/617-uncompressed/main
It's useful information to know - but more importantly, it makes
writing integration tests involving publishing uncompressed files
easier.
=> Expose the compression algorithm used as an xattr.

cvmfs/CMakeLists.txt
Related to #1351. Fixing a similar link order problem (`libcurl` uses `libssl`) in `cvmfs_swissknife[_debug]`.
=> FIX: swissknife link order on Ubuntu 14.04

ci/docker/cc7_x86_64/build.sh
This uses the latest packages (CentOS 7.2) for docker image bootstrapping right away. That should fix our CentOS 7 build, that failed due to a docker image bootstrapping issue.
In more detail, `build.sh` bootstrapped from outdated CentOS 7 packages and the `Dockerfile` tried to update most of the packages in a second step. Unfortunately the `iputils` package fails to update, thus stopping the docker image bootstrapping and eventually the build.
=> FIX: CentOS 7 Docker Build

cvmfs/cvmfs_server
This fixes the guessing procedure for the OverlayFS version on CentOS. I didn't find a better way to figure this out, yet. :-1:
=> FIX: OverlayFS Version Guessing on CentOS 7

cvmfs/CMakeLists.txt, cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_sql.cc, cvmfs/catalog_sql.h, cvmfs/signature.cc, cvmfs/swissknife_pull.cc, test/src/620-pullmixedrepo/main, test/unittests/t_catalog.cc
External files need to be skipped during replication.  Uncompressed files need to be handled in the preloader.
=> FIX: replication for external files and uncompressed files

cvmfs/catalog.cc, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_sql.cc, cvmfs/garbage_collection/garbage_collector_impl.h
This is a convenience feature for debugging. In a verbose garbage collection run, we now immediately see the `last_modified` timestamp of root catalogs being preserved or swept.
Note that this revealed the necessity for some minor fixes to `Catalog::GetLastModified()` and the bootstrapping of the first catalog in a repository. This particular catalog (revision number 0) didn't have the `last_modified` property set.
=> Feature: Print Catalog Timestamp in verbose GC

cvmfs/swissknife_check.cc
As stated in [CVM-958](https://sft.its.cern.ch/jira/browse/CVM-958) `cvmfs_server check` prints out many lines of status information making it easy to overlook sparse error messages. Even though `cvmfs_server check` returns with non-zero return code this is bad UX.
This patch prints a simple summary as the last line before exiting, stating clearly when `cvmfs_server check` found something. Furthermore it fixes a couple of error messages being logged to `stdout` rather than `stderr`.
=> Feature: `cvmfs_server check` prints summary before termination

cvmfs/cvmfs.cc
If a VOMS authz is required and CVMFS was compiled without VOMS
support, then deny the file access.
(This also centralizes the authorization checks.)
=> CVM-904: Change defaults if VOMS support is not compiled.

cvmfs/cvmfs_server, cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/swissknife_gc.cc, test/src/557-basicgarbagecollect/main, test/src/561-garbagecollectmultihash/main, test/src/576-garbagecollectstratum1/main, test/src/578-automaticgarbagecollection/main, test/unittests/t_garbage_collector.cc
This introduces a [logging mechanism for the garbage collection](https://sft.its.cern.ch/jira/browse/CVM-710) to keep track of deleted files. It is configured with `CVMFS_GC_DELETION_LOG=<file path>` and writes out all deleted object hashes like so:
```
c24c4add5e84de6a4282ebbb949f395ff80e6615
fdd2627ceca191e5eebe36622063013d38e3a9b2C
af4eb9a66975d325cc00a1bea50d70524b0b0700C
14a245b29cb6ee49a9a76de99755857f2f08af24C
```
Furthermore a log can be specified for the (currently not officially supported manual garbage collection) like so: `cvmfs_server gc -L <file path>`. Manually specified log files take precedence over configured ones in that case.
This comes with one new unit test and several adaptions to existing integration tests.
=> Feature: Garbage Collection can log deleted files

cvmfs/cvmfs.cc, cvmfs/download.cc, cvmfs/download.h
The external data hosts are assumed to not be running the GeoAPI
service.  Instead, use the CVMFS Stratum-1 servers listed in CVMFS_URL
to sort the external data hostnames with the GeoAPI.
@DrDaveD - this is the change we discussed earlier today.  Can you take a look at it?
=> Sorted external hosts using CVMFS Stratum-1s.

ChangeLog, cvmfs/bash_completion/cvmfs.bash_completion, cvmfs/cvmfs_server, cvmfs/swissknife_sign.cc, test/src/618-repometainfo/main
This fixes some minor problems with `cvmfs_server repo-metainfo`:
* add missing bash completion (along with `cvmfs_server update-info`)
* typo in `edit_json_unTil_valid()`
* default JSON skeleton wasn't valid JSON
Furthermore I'd like to suggest two things:
1. rename `cvmfs_server repo-metainfo` to `cvmfs_server update-repo-info` to match its name to `cvmfs_server update-info` and show that both are related
2. create the dummy meta info by default on `cvmfs_server mkfs`
=> FIX: Minor improvements to `cvmfs_server repo-metainfo`

cvmfs/compression.cc, cvmfs/compression.h, cvmfs/swissknife_graft.cc, cvmfs/swissknife_graft.h, test/src/624-chunkedexternalgraft/main
When a graft file is sufficiently large, we should automatically generate a chunked version.
Chunked grafts was already merged previously - this simply decreases the barrier of generating them.
Includes an integration test which combines external data, uncompressed files, chunks, and grafts.
=> Have graft generate chunked files.

cvmfs/hash.h, cvmfs/swissknife_scrub.cc
This new hash suffix `M` for repo info files was not known to `cvmfs_swissknife scrub` and produced false-positive alerts. Furthermore I added a reminder comment at a strategic location. Still a code smell, but okay....
=> FIX: `cvmfs_swissknife scrub` didn't know about hash suffix M

cvmfs/upload_s3.cc
This is a fix for a debug print of the S3 uploader. It's simply a scrambled `printf`. Thanks for reporting, Catalin!
=> FIX: Logging of S3 Upload Jobs

ChangeLog, cvmfs/catalog_traversal.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/object_fetcher.h, cvmfs/swissknife_gc.cc, test/src/625-loadfailureduringgarbagecollect/main, test/test_functions, test/unittests/t_object_fetcher.cc, test/unittests/testutil.cc, test/unittests/testutil.h
This fixes the garbage collection bug described in [CVM-966](https://sft.its.cern.ch/jira/browse/CVM-966) and refactors the `ObjectFetcher` classes for better error reporting.
The garbage collection needs to ignore catalog load failures to support consecutive GC runs -- at some point the `CatalogTraversal` reaches an already swept root catalog. Furthermore the previous GC run could have crashed, leaving a condemned root catalog whose nested catalogs are only partially swept. Hence, both nested and root catalog load failures must be handled.
Until now, GC was naïvely ignoring any catalog load failure - even if transient (i.e. network glitch, ...). This can lead to data loss in the worst case or potentially also to leaked hard drive space if a catalog is falsely ignored during the …
=> FIX: Mistakenly Ignoring Catalog Load Failures during GC

cvmfs/cvmfs_server
This is an annoyance on Ubuntu since practically forever. O.o Finally got down to fix it... I can haz better solution?
=> FIX: `cvmfs_server::die()` prints -e Prefix on Dash

test/test_functions
Making `/etc/cvmfs/.../server.conf` only readable by root blocks things like `cvmfs_server list`.
=> FIX: Missing `chmod` in `test_functions` Messes up Environment

cvmfs/swissknife_sync.cc, cvmfs/sync_mediator.cc
This fixes a minor but (to my mind) annoying issue with the publishing output. I.e. placing the newline at the wrong location.
```text
Using auto tag 'generic-2016-01-08T15:40:25Z'
Processing changes...
........Exporting repository manifest
Waiting for upload of files before committing...
Committing file catalogs...
Tagging test.local
Flushing file system buffers
Signing new manifest
Remounting newly created repository revision
```
=> FIX: Logging while Publishing

cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/cvmfs_server, cvmfs/manifest.h, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h
**Note:** This builds on [Refactor: Manifest, Download- and SignatureManager handing in `cvmfs_swissknife`](https://github.com/cvmfs/cvmfs/pull/1380).
This changes the handling strategy of the `Manifest` (i.e. `.cvmfspublished) by using the previous `.cvmfspublished` as an update basis, instead of recreating it from scratch for every `cvmfs_swissknife sync`. The advantage being, that "passive" manifest fields are just carried over and don't need to be recreated every time. It makes the addition of those fields less error prone (see [here](https://github.com/cvmfs/cvmfs/pull/1372) for example).
=> FIX: Handle Manifest Committing as Updates

cvmfs/manifest.cc, cvmfs/manifest.h, cvmfs/swissknife_sign.cc
This adds the CernVM-FS version string in the `.cvmfspublished` manifest for the rationale described in [CVM-817](https://sft.its.cern.ch/jira/browse/CVM-817). The field name will be `V` and is set during manifest signing.
**Note:** This contains [Refactor: Manifest, Download- and SignatureManager handing in `cvmfs_swissknife`](https://github.com/cvmfs/cvmfs/pull/1380/files) and [FIX: Handle Manifest Committing as Updates](https://github.com/cvmfs/cvmfs/pull/1381).
=> Feature: Add CernVM-FS Version String to Repository Manifests

test/unittests/t_fs_traversal.cc, test/unittests/t_garbage_collector.cc, test/unittests/testutil.h
There have been several problematic unit tests partly because of a bug introduced by me and partly on newer platforms. Additionally this fixes a signed/unsigned comparison warning.
=> FIX: Several Unittests

cvmfs/catalog_mgr_impl.h, cvmfs/swissknife_sync.cc
This failed the build on the old SLC 32bit platforms.
=> FIX: missing __STDC_FORMAT_MACROS and #include <inttypes.h>

cvmfs/cvmfs_server, cvmfs/manifest.cc, test/src/030-missingrootcatalog/main, test/src/508-cvmfsdevelopment/main, test/src/538-symlinkedstratum1backend/main, test/src/550-livemigration/main, test/src/554-defragcatalogrowid/main, test/test_functions
This fixes some problems found while running the server integration tests on Fedora 23 (with OverlayFS). One of them was introduced with #1382, causing `manifest::Fetch()` to die with a SEGFAULT when reading pre 2.2.0 manifests. Ooops...
=> FIX: Several Issues with Server Tests on Fedora 23

cvmfs/download.cc
When a file descriptor is ready for _writing_ (POLLOUT), it was incorrectly being marked as ready for _reading_ in `libcurl`.  This caused busy wait loops in the download thread, where `libcurl` would try to read from a specified descriptor and keep getting EAGAIN.
In testing, this gave a respectable 10% speedup in downloads.
=> Fix CURL flags

cvmfs/download.cc, cvmfs/download.h, cvmfs/voms_authz/voms_authz.h, cvmfs/voms_authz/voms_curl.cc
Have the download job cache a pointer the proxy data used by the
SSL context.  Since the SSL context will need to be re-created
after a redirect, we cannot give the memory to the context object
itself - we must manage it explicitly.
Without this, the SSL context created for the redirection target
will drop the user proxy and end up unauthenticated.
Verified use of OpenSSL memory algorithms by running cvmfs2 under valgrind and looking for errors.
@jblomer @reneme @djw8605 @DrDaveD - without this, secure CVMFS breaks on redirection.  Ouch.
=> Cache SSL context info.

cvmfs/cvmfs_server, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sign.h, test/src/563-garbagecollectlegacy/main
Contrary to what I stated in #1381, we need to propagate the state of both `CVMFS_GARBAGE_COLLECTION` and `CVMFS_VOMS_AUTHZ` to `cvmfs_swissknife` so that it can update `.cvmfspublished` accordingly. Thus, I needed to revert the removal of the flags `cvmfs_swissknife sync -g -V` from #1381. However, now they are attached to `cvmfs_swissknife sign` so that any manifest signing operation can trigger the update of those flags, not only `cvmfs_server publish`.
=> FIX: Manifest Updates Need to Propagate

ci/build_cvmfs_sourcetarball.sh
Jenkins (and ecsft.cern.ch/dist/cvmfs) were overflowing with outdated tarballs. This should clean them up properly after each build.
=> FIX: Clean up all old tarballs

cvmfs/download.cc
The refactored `GeoSortServers` function looked at the incorrect vector size (those being sorted instead of those being queried) when determining the number of attempts to perform, leading to a SEGV due to an out-of-bounds access.
Found when testing a `CVMFS_EXTERNAL_URL` with 5 entries but `CVMFS_SERVER_URL` of 1 entry.
=> Fix out-of-bounds SEGV

cvmfs/download.cc
When downloading via HTTPS, there are a few error paths (particularly, when the remote side closes the socket unexpectedly) that can result in a SIGPIPE.
As we instruct curl to not touch our signal handlers, we should explicitly make sure we've disabled SIGPIPE in this thread.
Without this, a user on the host may be able to crash the FUSE process.
=> Avoid potential SIGPIPE when downloading via HTTPS

cvmfs/cvmfs_server, test/src/618-repometainfo/main
This adds `cvmfs_server update-repoinfo -f` that allows for non-interactive updates of the repository's JSON meta data. Simply pass a JSON file path with the `-f`. If `cvmfs_server` finds `jq` in the system, it uses it to validate the passed in JSON file. Furthermore this updates integration test 618 to also use this code path.
=> Feature: Non-Interactive `cvmfs_server update-repoinfo`

test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh, test/run.sh, test/src/618-repometainfo/main, test/test_functions
Repair some issues after the first full iteration of cloud tests.
Most notable:
* enable server integration tests >= 600
* fix server cache directory on fedora
=> FIX: Test Infrastructure Scripts

cvmfs/download.cc
CVMFS currently wakes up once a millisecond to check if libcurl has any ongoing transfers which have timed out.  As the granularity of our timeouts is in seconds, this is overkill: we can back off and save system CPU time.
libcurl actually provides a callback interface where it will inform CVMFS when the next upcoming library timeout will occur.  However, due to the proximity of the release, I simply increase the granularity.
=> Avoid busy-wait when downloading files

packaging/rpm/cvmfs-universal.spec
This allows the resulting RPM-based binaries to be run underneath valgrind.
Note this might break the build on some platforms: I don't have the full range of RPM distros to test on locally.  Any breakage should be relatively easy to fix.
=> Require valgrind-devel in RPM build

cvmfs/cvmfs_server
The `cvmfs_server` script needs to set up `CVMFS_MOUNT_DIR=/cvmfs` for new repositories. Furthermore it has been added to the migration step from 2.1.20 to 2.2.0.
=> FIX: Missing CVMFS_MOUNT_DIR Parameter

cvmfs/cvmfs_server, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sign.h, test/src/610-altpath/main
This fixes integration test 610 (Alternative catalog path) by separating the creation of `.cvmfsalt-` bootstrapping shortcut symlinks from the `CVMFS_VOMS_AUTHZ` server parameter.
Furthermore it does a small refactoring in `cvmfs_server mkfs` moving the creation of  `CVMFS_VOMS_AUTHZ` to `create_config_files_for_new_repository`. Rationale is, that *all* configuration parameters for new repositories are done there centrally.
=> FIX: Integration Test 610

test/src/065-http-400/main, test/test_functions
This fixes a problem with integration test 584 which uses `run_background_service` to start a `cvmfs_server snapshot`. Unfortunately the `sleep 1` [introduced recently](https://github.com/cvmfs/cvmfs/pull/1397) is stepping in the way here. Therefore this implements a proper waiting loop in integration test 065 and removes the `sleep 1` again.
=> FIX: Test 584 + Refactor 065

cvmfs/swissknife_graft.cc
Make sure we initialize `avail_out`; if the memory happened to be 0, this would trigger an infinite loop in `swissknife graft`.
@reneme
=> Avoid using uninitialized output size variable

cvmfs/cvmfs_server
This was to stringent, breaking many test cases...
=> FIX: is_mounted() on missing mount point

test/run.sh, test/test_functions
This bug prevented the autofs restart between test cases, so test cases could screw up with their successors.
=> FIX: query for osx in integration tests

cvmfs/cvmfs_preload, cvmfs/cvmfs_server, cvmfs/sync_union.cc, test/cloud_testing/platforms/fedora23_x86_64_setup.sh, test/cloud_testing/platforms/slc5_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/run.sh, test/src/596-catalogbalancer/main, test/src/598-partialpreload/main, test/src/620-pullmixedrepo/main, test/test_functions, vagrant/provision_fedora.sh
This fixes several things found during tonights cloud testing run:
* `/cvmfs/info/...` API wasn't compliant to SELinux
* improved opportunistic building of `cvmfs_preload` in tests **598** and **620** (dependencies and code-reuse)
* `cvmfs_preload` didn't properly extract on EL5
* race condition in `cvmfs_server mkfs` leading to 5-10% failed server tests using OverlayFS
* other mainly cosmetic changes
=> FIX: Several Issues from the latest Cloud Test Run

cvmfs/cvmfs_server, test/src/608-infofile/main, test/src/609-metainfofile/main
This changes the meta-info API endpoints to:
* `/cvmfs/info/v1/repositories.json`
* `/cvmfs/info/v1/meta.json`
Essentially only adding a .json suffix.
=> FIX: Rename Meta Info Files

cvmfs/cvmfs_server, test/src/626-cacheexpiry/main
This integrates the fix provided by @DrDaveD and described in [CVM-974](https://sft.its.cern.ch/jira/browse/CVM-974) along with a regression test.
RFC: Do you think it is okay to recreate the apache config file from scratch during migration from 2.1.20 instead of doing the `sed`-stunt I pushed in here? Or might that cause issues during operation?
**Note:** Putting this here for discussion. Please don't merge yet, I need to iterate on the config migration step and test it.
=> FIX: Cache Expiry HTTP Headers

cvmfs/cvmfs_server, test/src/626-cacheexpiry/main
This is adding additional migration routines and adding Stratum1s to the migration paths from 2.1.20 (and 2.2.0-0 - prerelease) to 2.2.0. I'll need to give that a [manual dry-run](https://sft.its.cern.ch/jira/browse/CVM-950) as there is no automatic testing for this functionality.
**Note:** This is based on [FIX: Cache Expiry HTTP Headers](https://github.com/cvmfs/cvmfs/pull/1425).
=> FIX: Repository Migration Code

cvmfs/cvmfs_server
Fix an issue with the server migration code and version handling that was [introduced yesterday evening](https://github.com/cvmfs/cvmfs/pull/1430). Newly created Stratum1 repositories were detected as 'incompatible', breaking all Stratum1 related test cases.
This changes the `CVMFS_CREATOR_VERSION` schema in `server.conf` (before: `x.y.z` now `x.y.z-k`) to be able to distinguish between the incompatible versions CernVM-FS 2.2.0-0 and 2.2.0-1. For both Stratum0 and Stratum1 repositories this version jump requires a migration run.
TIL: One does not simply quick-fix something just before calling it a day... :-1:
=> FIX: Version Handling and Migration

cvmfs/cvmfs_server, test/test_functions
Fix a minor problem in `to_syslog()` helper function both in `cvmfs_server` and `test_functions`. The missing quotation marks caused the `logger` utility to choke on certain input strings.
=> FIX: Missing Quotes in `to_syslog()` Helper Function

cvmfs/manifest.cc, cvmfs/manifest.h, cvmfs/swissknife_sign.cc
This reverts the changes done in [Feature: Add CernVM-FS Version String to Repository Manifests](https://github.com/cvmfs/cvmfs/pull/1382/files). The [respective ticket](https://sft.its.cern.ch/jira/browse/CVM-817) is pushed to CernVM-FS 2.3.0.
=> Revert: Addition of Manifest Field 'V'

cvmfs/CMakeLists.txt, test/cloud_testing/platforms/fedora22_x86_64_setup.sh, test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1510_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_setup.sh, test/src/550-livemigration/main, test/test_functions
This mainly fixes things in the test infrastructure for some failed tests. The only 'actual' production fix is the wrong link order of `cvmfs_preload_bin` that becomes apparent on Ubuntu.
=> FIX: Several minor issues of tonight's cloud test run

cvmfs/cvmfs_config
Fixes the usage string and the killing of cvmfs2 processes after a hotpatch from a previous version.
=> Fix for cvmfs_config killall

ci/docker/ubuntu1204_i386/build.sh, ci/docker/ubuntu1204_x86_64/build.sh
Sigh! Didn't update the right field. Hence the image was called Ubuntu 12.04 but internally it was a 14.04.
=> FIX: Docker Images on Ubuntu 12.04

cvmfs/quota.cc
This problem can explain the hang during the migration test.
=> FIX: race when reloading at the same time as evicting data from the cache

test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1510_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_setup.sh
* Add `sftnight` user opportunistically to `fuse` group on Ubuntu
* Disable `006-buildkernel` on newer platforms (FC22, FC23, Ubuntu 15.10)
=> FIX: Minimal Test Setup Changes after Tonight's Cloud Test Run

test/common/mock_services/HTTPRangeServer.py, test/common/mock_services/http_server.py, test/src/607-noapache/main, test/src/615-externaldata/main, test/test_functions
Integration test 615 "External Files" failed on all our platforms - mainly because it assumed to run as a privileged user. Furthermore it contained several code smells that I tried to clean up as good as possible, for example:
* hard coding of **test.cern.ch** repository name and storage paths
* wrong "jargon" usage: "spool area" vs. "backend storage" vs. "cache space"
* unclear comments and log messages
* complicated control flow - making the test hard to read and understand
* many things needed to be DRY-ed up
Since those test cases should also serve as a blue-print how specific features are supposed to be used, we should always try to stay concise and readable when writing them.
Furthermore I added some more checks (in particular for native chunked files) and made use of the …
=> FIX: Cleaning Up and Extending "External Files" Integration Test 

cvmfs/cvmfs_server, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_setup.sh, test/src/571-localbackendumask/main, test/src/598-partialpreload/main, test/src/602-libcvmfs/main, test/src/602-libcvmfs/main.cc, test/src/608-infofile/main, test/src/615-externaldata/main, test/src/616-blacklistconfigrepo/main, test/src/620-pullmixedrepo/main, test/src/621-snapshotall/main, test/src/625-loadfailureduringgarbagecollect/main, test/test_functions
This again fixes several minor things in the test infrastructure both for Ubuntu based tests and S3. On ubuntu there were two packages (i.e. `bc` and `jq`( missing. For S3 I disabled several tests that don't make sense and also I fixes some of the newer tests to work on S3 based repositories.
=> FIX: Tonight's Integration Test run - Focussing on Ubuntu and S3

cvmfs/catalog_sql.cc
Currently, `cvmfs_swissknife pull` tries to replicate all chunks: this causes a failure if the chunk is part of an external file.
=> FIX: Do not replicate external chunks.

cvmfs/download.cc
OpenSSL-induced SIGPIPE can occur on non-VOMS builds if HTTPS is
specified for the CVMFS_EXTERNAL_URL.  So, it must be ignored
unconditionally.
=> FIX: Always disable SIGPIPE.

ChangeLog
We reverted this change as it caused strange behavior in the CI instances.
(To revisit in next version.)
=> Remove mention of libcurl change

cvmfs/download.cc, cvmfs/voms_authz/voms_authz.h, cvmfs/voms_authz/voms_curl.cc
In the case where a user with a X509 proxy accesses a file
then deletes the proxy and tries to download a second file, the
value of CURLOPT_SSL_CTX_DATA would not be overwritten when the
curl handle object was reused.  The X509 chain in-memory *would*
be deleted, however.
On the second use, the OpenSSL context would be given the invalid
pointer to the X509 chain by libcurl, resulting in a segfault.
=> Avoid use-after-free in OpenSSL.

ChangeLog, ci/docker/cc7_x86_64/Dockerfile, ci/docker/fedora21_i386/Dockerfile, ci/docker/fedora21_x86_64/Dockerfile, ci/docker/fedora22_i386/Dockerfile, ci/docker/fedora22_x86_64/Dockerfile, ci/docker/fedora23_i386/Dockerfile, ci/docker/fedora23_x86_64/Dockerfile, ci/docker/slc4_i386/Dockerfile, ci/docker/slc5_i386/Dockerfile, ci/docker/slc5_x86_64/Dockerfile, ci/docker/slc6_i386/Dockerfile, ci/docker/slc6_x86_64/Dockerfile, ci/docker/ubuntu1204_i386/Dockerfile, ci/docker/ubuntu1204_x86_64/Dockerfile, ci/docker/ubuntu1404_i386/Dockerfile, ci/docker/ubuntu1404_x86_64/Dockerfile, packaging/debian/cvmfs/control, packaging/rpm/cvmfs-universal.spec
We should build with VOMS on platforms where VOMS should be available (definitely RHEL and Fedora; not sure about SUSE).  Otherwise, all the secure CVMFS stuff is disabled.
*Note*: I don't know much about the build environment for the nightlies; something else in the package might need to be adjusted to make sure `voms-devel` is available.
=> Build with VOMS on relevant platforms.

cvmfs/cvmfs_server, test/common/mock_services/HTTPRangeServer.py, test/common/mock_services/silent_socket.py, test/src/017-dnstimeout/main, test/src/019-httptimeout/main, test/src/020-emptyrepofailover/main, test/src/610-altpath/main, test/src/615-externaldata/main, test/src/620-pullmixedrepo/main, test/src/624-chunkedexternalgraft/main, test/src/626-cacheexpiry/main, test/test_functions
A problem with SELinux contexts on EL5 (repo meta info files). Furthermore EL5 doesn't know about the mime-type **application/json**, yet. Both fixed in `cvmfs_server`.
Other than that, again mainly test infrastructure improvements, fixes and S3 generalisations. The mock service `silent_socket.py` was producing stack traces and wasn't always cleaned up properly. As a result certain port numbers might have been kept occupied.
=> FIX: Tonight's Integration Test run

.travis.yml, ci/run_cpplint.sh, cvmfs/catalog_sql.cc, test/unittests/t_history.cc, test/unittests/t_object_fetcher.cc, test/unittests/t_uploaders.cc
This PR:
- Includes a .travis.yml file for the synchronization with https://travis-ci.org/ which builds in Linux (Ubuntu 12.04) and OS X (Maveriks) with both gcc and clang. It runs the unit tests only on Linux due to diverse problems on OS X machines.
- Fixes the return value of ci/cpplint.sh in order to stop the build in travis if there are failures.
- Fixes different _static const std::string_ in the unit tests that did not allow the unit tests to pass on travis when compiling with clang
=> Travis integration

test/src/603-automaticgarbagecollectionrace/main
The test 603 this a regression test for [CVM-942](https://sft.its.cern.ch/jira/browse/CVM-942) - thus it tries to exploit a race condition. Turns out that we've lost the race several times when running it on OpenStack. This is supposed to increase the available time margin by a factor of 3.
=> FIX: Increase time margin for integration test 603

cvmfs/cvmfs_server, cvmfs/voms_authz/voms_authz.cc, test/cloud_testing/platforms/common_test.sh, test/src/591-importrepo/main, test/test_functions
Fixing tonights regressions (global `cvmfs_server_hooks.sh` with bogus `CVMFS_UPDATEGEO_URLBASE6`) killing practically all Stratum1 related tests. Remove `try_mount_remount_cycle_overlayfs()` since it makes problems and is not necessary. Furthermore fixing integration test **591** showing an SELinux problem in Fedora 23.
=> FIX: Tonight's Integration Test Run - Hopefully the Last

test/cloud_testing/platforms/slc6_x86_64_test.sh, test/src/578-automaticgarbagecollection/main, test/src/595-geoipdbupdate/main, test/src/597-graft/main
This fixes the S3 compatibility of **597** "Grafting" and disables **610** (Alternative Catalog Path) in S3 tests. Furthermore it increases the tested race condition margin in **578**. Furthermore it contains a general fix for **595** that downloaded the GeoIP database from MaxMind instead of ecsft.cern.ch.
=> FIX: S3 compatibility and GeoIP database download

cvmfs/voms_authz/voms_authz.cc, test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/src/600-securecvmfs/main, test/test_functions, vagrant/provision_slc6.sh
This fixes integration test 600 by changing it's logic slightly and adding some bells and whistles here and there. Also fixes a file descriptor leak in the associated production implementation. Furthermore the test is disabled on all platforms but SL5 and 6.
=> FIX: Overhauling Integration Test 600 (Secure CVMFS)

cvmfs/cvmfs_server, test/test_functions
This checks the version of OverlayFS when it is used in `cvmfs_server`. That is to exclude unsupported incarnations of OverlayFS. Either because it was manually compiled into the kernel (before 3.18) or it's not recent enough and still contains bugs (Details in [CVM-835](https://sft.its.cern.ch/jira/browse/CVM-835)). This explicitly excludes the OverlayFS in CentOS 7.x as it is not viable for CernVM-FS, (yet).
For **testing purposes** this check can be overridden by setting the `CVMFS_DONT_CHECK_OVERLAYFS_VERSION` environment variable.
=> Feature: Check OverlayFS version in cvmfs_server

cvmfs/catalog_balancer_impl.h
Thanks to coverity (http://coverity.cern.ch/reports.htm#v12693/p10002/fileInstanceId=746946182&defectInstanceId=389602431&mergedDefectId=63573) I found this recursive include
=> FIX: recursive include

test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/src/600-securecvmfs/main
Fixing the "Secure CVMFS" test case on SLC6 and disabling it on SLC5. On the latter platform `voms-proxy-fake` crashes with "stack smashing detected". On SLC6 it was missing the `voms` package.
=> FIX: Test 600

cvmfs/cvmfs_config, test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh
Fixes the integration test runs on Fedora (in particular 22) by starting Apache up-front. Furthermore this updates the SELinux sanity check in `cvmfs_config chksetup` to skip on EL5 and work on Fedora.
=> FIX: Last Second Fixes

cvmfs/libcvmfs.h, cvmfs/libcvmfs_int.cc, test/src/602-libcvmfs/main, test/src/602-libcvmfs/main.cc
The problem was introduced by confusing the external fetcher with the native fetcher in libcvmfs.  Integration test coverage added.
=> Fix reading of chunked files in libcvmfs

cvmfs/cvmfs.cc
Unfortunately, libvomsapi doesn't do all the validation we need
for this to function correctly.  For now, we disable VOMS checks and
always assume they fail - we'll fix this up in the next devel series.
This does allow HTTPS to be used for URLs as we blindly pass the
client credential to the remote host and don't need to validate it
in the client.
=> Disable VOMS checks.

ci/docker/slc6_x86_64/Dockerfile
Installation of the necessary dependencies for running gcovr for the test coverage.
It might be necessary to also move/modify the run_on_docker.sh script so that it allows more flexibility
=> Add pip and gcovr to slc6_x86_64 docker image

cvmfs/swissknife.cc, cvmfs/swissknife.h, cvmfs/swissknife_check.cc, cvmfs/swissknife_gc.cc, cvmfs/swissknife_history.cc, cvmfs/swissknife_letter.cc, cvmfs/swissknife_lsrepo.cc, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_pull.cc, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sync.cc
This moves the initialisation of `SignatureManager`s used for signing (rather than verification) to a central place in `cvmfs_swissknife`. Somewhat this is a continuation of a [cleanup campaign a month ago](https://github.com/cvmfs/cvmfs/pull/1380) and DRYs up some code duplications. It is a preparation for further refactorings to introduce a full-featured garbage collection.
Amendment: I've replaced `Spooler*` and `Manifest*` by respective `UniquePtr<>`s to get rid of the `goto fail`.
=> Refactor: swissknife::InitSignatureManager()

CMakeLists.txt
The issue was resolved in binutils 2.26 release and the fix was
backported to RHELSA DP 7.2 and CentOS 7.2.1511.
Resolves errors while building cvmfs-universal.spec on aarch64.
Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>
=> Remove BUILD_LIBCVMFS restriction on AArch64

cvmfs/cvmfs_server, test/src/570-remountrace/main
This is a request for comment!
Recently on **lhcbdev.cern.ch** and a while ago in **geant4.cern.ch** we've been seeing release manager machines in an inconsistent state. The transaction is committed successfully but uounting of `/cvmfs/lhcbdev.cern.ch` fails with 'device busy'. This locks up the release manager machine in an inconsistent state requiring to do the following:
```bash
cvmfs_suid_helper rw_umount lhcbdev.cern.ch
cvmfs_suid_helper rdonly_umount lhcbdev.cern.ch
cvmfs_server abort -f lhcbdev.cern.ch
```
The installed version there is CernVM-FS 2.1.20 but the code path in question has not been touched significantly since then, as far as I can see. I can't tell yet what exactly locks up the mountpoint, unfortunately. Also, there are checks for open file descriptors right before …
=> RFC: Opportunistically Retry umount with Force

test/unittests/t_voms.cc
This fixes a compile error that has been introduced [here](https://github.com/cvmfs/cvmfs/pull/1507). @Moliholy can you comment?
=> FIX: Compile Error in t_voms.cc

ci/run_travis.sh
It's considerably ugly not to see more dots printed in the output. The activity and the "Done" are pretty close. Printing one every 10 seconds instead of 30 would make it prettier
=> Increase the number of dots in travis

cvmfs/catalog.cc, cvmfs/catalog_rw.cc, cvmfs/catalog_sql.cc, cvmfs/catalog_sql.h, cvmfs/swissknife_migrate.cc
This fixes a severe code smell. Namely we've had two implementations of `class Sql`, one residing in the namespace `sqlite` and one (that actually directly inherited from the first) in namespace `catalog`. This renames the latter one to `catalog::SqlCatalog` for clarity and consistency with `history::SqlHistory` and `manifest::SqlReflog` (to come [here](https://github.com/cvmfs/cvmfs/pull/1511)).
=> Refactor: Rename catalog::Sql to catalog::SqlCatalog

cvmfs/libcvmfs_public_syms.txt
This adds three new symbols to `libcvmfs_public_syms.txt`. I have no idea what I'm doing here, but apparently something similar was necessary in mid 2013 to make it compile on 32bit. Google says that `get_pc_thunk` style stuff is used to get the location of the code in relocatable binaries. Frankly I find it a bit troublesome that these "obviously private" symbols need to be declared public to make it link successfully. O.O
=> FIX: 32bit compile of libcvmfs on Fedora 23

cvmfs/catalog_sql.cc, cvmfs/catalog_sql.h, cvmfs/history_sql.cc, cvmfs/history_sql.h, cvmfs/reflog_sql.cc, cvmfs/reflog_sql.h, cvmfs/sql.cc, cvmfs/sql.h, cvmfs/swissknife_migrate.cc
**Work in progress...**
This allows derived `Sql` wrapper classes to opt for lazy initialisation of their prepared statements. We hope to safe memory and CPU cycles this way. For example each catalog opened for writing is preparing 17 SQL statements even though it might only ever need a small subset of them.
Furthermore this changes some low-hanging fruits in *history_sql.cc* to utilise the new `Sql::DeferredInit()` for demoing the API.
More adaptions in other `Sql` subclasses to come...
=> Feature: Lazy Initialisation of SQL statements

cvmfs/cvmfs_server
This fixes the `lsof` output shown to the user if file descriptors are detected by `cvmfs_server publish`. The `lsof` log was also containing open files in directories with a similar name as the repository's mount point (see below):
```
WARNING! There are open read-only file descriptors in /cvmfs/lhcbdev.cern.ch
--> This is potentially harmful and might cause problems later on.
We can anyway perform the requested operation, but this will most likely
break other processes with open file descriptors on /cvmfs/lhcbdev.cern.ch!
The following lsof report might show the processes with open file handles
bash       6666   cvlhcbdev  /var/spool/cvmfs/lhcbdev.cern.ch/cvlhcbdev
bash       7217   cvlhcbdev  /cvmfs/lhcbdev.cern.ch   # <<== ONLY THAT ONE IS VIABLE
bash       9386   cvlhcbdev …
```
=> FIX: False-Positive `lsof` Output

cvmfs/cvmfs_server
That should make sure to run `cvmfs_suid_helper` always in a fresh environment. Amending  `$LD_LIBRARY_PATH` with a path that points into the CVMFS repository being published might make `cvmfs_suid_helper` pick up shared libraries from there. However, `cvmfs_suid_helper` will then not be able to `umount` the repository because it holds open file descriptors on the mount point itself.
That's sort of a quick fix... Better ideas?
=> FIX/RFC: Make Sure that `cvmfs_suid_helper` Runs in Clean Environment

cvmfs/cvmfs_server
We use `grep` to parse the expiry date of a downloaded whitelist. In some environments `grep` treats the whitelist as binary data (because of the attached binary signature) and produces bogus output.
=> FIX: `grep` Treating Whitelist as Binary Data

cvmfs/cvmfs_server
This allows to run `cvmfs_server publish -f` that disables the interactive warning when open file descriptors are found on the repository. In the normal case it doesn't change the behaviour of `cvmfs_server publish`, however if open file descriptors on `/cvmfs/$repo_name` are found, only a warning message is printed and a forceful remount is assumed without interactively asking for permission.
The same is true for `cvmfs_server abort -f` which will also assume a forceful remount in case open file descriptors are detected.
This is potentially useful for testing and potentially cronjobs but shouldn't be over-used.
=> Feature: Add `cvmfs_server publish -f` Disabling Interactive Open File Descriptor Dialog

cvmfs/swissknife_scrub.cc, cvmfs/swissknife_scrub.h, cvmfs/sync_union.cc
Removes an unnecessary `stat()` call for each file system item being processed. It also checked files for the opaque-directory marker, which is useless. Hard to estimate the impact of that tweak, though.
Furthermore this fixes a valgrind warning because an uninitialised mutex gets destroyed under certain circumstances.
=> Low Hanging Fruits for Publishing

cvmfs/cvmfs_server, test/src/628-pythonwrappedcvmfsserver/LbCVMFS/Tools.py, test/src/628-pythonwrappedcvmfsserver/do_install.py, test/src/628-pythonwrappedcvmfsserver/main
This fixes an issue in `cvmfs_server` which prevents it from checking for open file descriptors on `cvmfs_server publish` and `cvmfs_server abort` if `lsof` cannot be found in the `$PATH`. In particular this is crucial for `cvmfs_server` commands that are called through `cron`, as it sets the `$PATH` to something like `/bin:/usr/bin:.`.
Along with `lsof` there have been a handful of other commands from `/sbin` and `/usr/sbin` that might have suffered the same issue.
Along with the fix there is a regression test that closely resembles the release manager setup of **lhcbdev.cern.ch** where the problem was initially found. See `526*/main` for more details.
*Note:* This builds on top of [Feature: Add `cvmfs_server publish -f` Disabling Interactive Open File Descriptor …
=> FIX: `cvmfs_server` Open File Descriptor Check relies on `$PATH` for `lsof`

cvmfs/voms_authz/voms_curl.cc
This fixes missing includes in `voms_curl.cc`. Perhaps missed in #1535 ?
=> FIX: Includes in VOMS

cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/sync_item.cc, cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h, cvmfs/sync_union.cc, cvmfs/sync_union.h, test/src/629-earlynestedcreation/main
This was on my list since a long time: Disentangling the management of nested catalogs from the processing of `.cvmfscatalog` in `SyncMediator`. This might speed up snapshotting significantly in certain situations.
Up to now, a nested catalog was created as soon as `cvmfs_server publish` hit a `.cvmfscatalog` file, and removed when it found a deleted `.cvmfscatalog` file. Conceptually that is fine, but it might lead to *many* unnecessary catalog updates. 
For example: Imagine a user adds a new directory `release` and marks it a nested catalog (i.e. `release/.cvmfscatalog`), furthermore she adds 150.000 files to this new directory. In the worst case, `cvmfs_server publish` would traverse all 150.000 files, adding them to the father catalog of `release`. Only in the end it would find …
=> Optimisation: Create/Remove Nested Catalogs

cvmfs/cvmfs_server, cvmfs/swissknife_gc.cc, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/627-reflog/main
This fixes several issues with the `Reflog` updates during `cvmfs_server snapshot`. In detail:
* legacy `Reflog` was mistakenly downloaded from `Stratum0` instead of `Stratum1`
* missed call to `Uploader::TearDown()` resulting in `assert()`
* `Catalog`s downloaded via *previous*-pointer were not registered
This adds regression checks to the integration test case 577.
=> FIX: Reflog Update During Snapshotting

cvmfs/cvmfs_server, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/swissknife_gc.cc, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/627-reflog/main, test/unittests/t_garbage_collector.cc
This cleans out `Reflog` entries as soon as they are swept by the garbage collection. Note that this is based on [FIX: Reflog Update During Snapshotting](https://github.com/cvmfs/cvmfs/pull/1544).
=> Feature: Reflog cleanup on Garbage Collection

cvmfs/cvmfs_server, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/swissknife.cc, cvmfs/swissknife.h, cvmfs/swissknife_gc.cc, cvmfs/swissknife_impl.h, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/627-reflog/main, test/test_functions, test/unittests/t_garbage_collector.cc
This changes the `Reflog` handling so that a missing `Reflog` can be ignored by most of the `cvmfs_swissknife` commands. In order to do garbage collection, a `Reflog` must be constructed from the available `Catalog` and `History` chains first (TODO).
Both `cvmfs_server mkfs` and an initial `cvmfs_server snapshot` will drop an empty `Reflog` to be filled opportunistically for new repositories and replicas.
=> Feature: Swissknife Ignores Missing Reflog

cvmfs/swissknife_migrate.cc, cvmfs/swissknife_migrate.h, test/src/514-changechunkedfile/main, test/src/519-importlegacyrepo/main, test/src/554-defragcatalogrowid/main, test/src/563-garbagecollectlegacy/main, test/src/589-catalogchown/main, test/src/599-removehardlinks/main, test/test_functions
Turns out that all but the CernVM-FS 2.0.x catalog migrations didn't update the catalog meta information (i.e. previous revision pointer, revision number and last modified timestamp). Hence, catalog revisions generated by `cvmfs_swissknife migrate -v [2.1.7 | chown | hardlink]` logically "replaced" their base revision instead of creating an identical new catalog revision.
Unfortunately this is a bug that made it into production (at least at CERN we've been using `cvmfs_server catalog-chown` when moving to new release manager machines). As far as I can tell, this should not be critical though (apart from a catalog revision that is not garbage collectable anymore). I found this bug by chance when writing an integration test for `Reflog`.
This integrates a few regression checks in …
=> FIX: Catalog Migration not Updating Catalog Metadata

bootstrap.sh, externals/libcurl/src/disable_sslv3.patch
This disables SSLv3 in the `libcurl` version we are currently using. As of OpenSSL 1.0.2g SSLv3 is [disabled on Ubuntu](https://launchpad.net/ubuntu/+source/openssl/1.0.2g-1ubuntu1) 15.10 which prevents a successful build of CernVM-FS. The OpenSSL ABI didn't change, hence this doesn't affect our released binaries. This patch will most likely become obsolete when we update our `libcurl` version.
=> FIX: Remove Usage of SSLv3_client_method() in libcurl

cvmfs/cvmfs_server, cvmfs/cvmfs_suid_helper.cc
This Pull Request is requesting for comments!
After `cvmfs_server publish`-ing a large change set it might take a significant time to clean-out the scratch directory (i.e. `/var/spool/cvmfs/<fqrn>/scratch`). This allows to run this clean-up asynchronously to allow for quicker publishing round-trips. Setting `CVMFS_ASYNC_SCRATCH_CLEANUP=false` disables this and reverts back to the legacy behaviour.
The general idea of this workflow is:
0. create `current` and `wastebin` inside `/var/spool/cvmfs/<fqrn>/scratch`
1. publish as usual (using `.../scratch/current` as union fs scratch directory)
2. umount `/cvmfs/<fqrn>` and `/var/spool/cvmfs/<fqrn>/rdonly`
3. move `.../scratch/current` into `.../wastebin/waste.XXXXXX/current`
4. create a fresh `.../scratch/current`
5. spawn daemon process …
=> Feature: Asynchronous Cleanup of Scratch Directory

cvmfs/CMakeLists.txt, cvmfs/cvmfs_server, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/object_fetcher.h, cvmfs/reflog.cc, cvmfs/reflog.h, cvmfs/reflog_sql.cc, cvmfs/reflog_sql.h, cvmfs/swissknife.cc, cvmfs/swissknife.h, cvmfs/swissknife_gc.cc, cvmfs/swissknife_impl.h, cvmfs/swissknife_info.cc, cvmfs/swissknife_main.cc, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, cvmfs/swissknife_reflog.cc, cvmfs/swissknife_reflog.h, cvmfs/swissknife_sign.cc, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, test/src/563-garbagecollectlegacy/main, test/src/577-garbagecollecthiddenstratum1revision/main, test/src/627-reflog/main, test/src/629-reflogrecreation/main, test/test_functions, test/unittests/t_garbage_collector.cc, test/unittests/t_reflog.cc, test/unittests/testutil.cc, test/unittests/testutil.h
This should be the final building block of the `Reflog` business. It introduces a new `cvmfs_swissknife` command (i.e. `recreate_reflog`) that walks as much of the root `Catalog` and `History` chains as possible to reconstruct the `Reflog`.
The use case is two fold: **1st** it allows for an easy transition from the old-style garbage collection to the `Reflog` driven version and **2nd** it serves as a failure recovery mechanism in case the original `Reflog` has been corrupted. We cannot guarantee that a full `Reflog` is reconstructable from the stored `Catalog` and `History` chains but this gives some best-effort.
Furthermore this contains a [minor syslog logging fix](https://github.com/cvmfs/cvmfs/commit/87bdd4aeb3526c4f5395a6b7307d144da0640374) which I was too lazy to extract. Also it …
=> Feature: Regenerate Reflog from Available Catalog and History Chains

cvmfs/cvmfs_server, test/src/582-autorepairmountpoints/main
This introduces several refactorings to `cvmfs_server` preparing for the integration of the `cvmfs_server mount` command. In detail:
* namespace the `cvmfs_server` command functions (i.e. `mkfs()` --> `cvmfs_server_mkfs()`) to avoid clashes with standard system functions (i.e. `mount()`).
* minor cosmetic fixes and protected methods (i.e. `_migrate_<base>()`)
* Restructuring of `health_check()` to disentangle *status discovery*, *status message printing* and *mount point repairs*
* `health_check()` takes proper command line parameters
* mount point repair must be explicitly requested with `health_check -r`
* Add status messages to syslog
- `Trying to umount /cvmfs/${name}... [success|fail]`
- `Trying to umount ${CVMFS_SPOOL_DIR}/rdonly... [success|fail]`
- `Trying to mount …
=> Refactor: Health Check and Namespacing in `cvmfs_server`

cvmfs/cvmfs_server, test/src/582-autorepairmountpoints/main, test/src/630-servermount/main
This introduces `cvmfs_server mount` that sets up the mount points for a given repository or all repositories (`sudo cvmfs_server mount -a`). Along with it there is integration test 630 testing the functionality.
**Note:** This is based on the adaptions done in [Refactor: Health Check and Namespacing in `cvmfs_server`](https://github.com/cvmfs/cvmfs/pull/1549).
=> Feature: `cvmfs_server mount [-a]`

cvmfs/bash_completion/cvmfs.bash_completion
This is a follow up for "[Feature: `cvmfs_server mount [-a]`](https://github.com/cvmfs/cvmfs/pull/1551)" and adds bash completion accordingly.
=> Add Bash Completion for `cvmfs_server mount`

cvmfs/bash_completion/cvmfs.bash_completion, cvmfs/cvmfs_server, test/src/630-servermount/main
That retrofits the `cvmfs_server mount [-a]` feature to CernVM-FS 2.2. Refactoring of `health_check()` is omitted and the `mount` name clash is worked around rather than doing full `cvmfs_server` subcommand namespacing (#1549). This happens at the expense of a verbose and less concise status/error logging when running `cvmfs_server mount`.
Note that this also cherry-picks and adapts integration test 630 as well as the bash completion.
=> Feature: `cvmfs_server mount [-a]` retrofitted to CernVM-FS 2.2

test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1510_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh
After [this](https://github.com/cvmfs/cvmfs/pull/1547) has been merged the integration tests 577 and 579 should work properly using `.cvmfsreflog`.
=> TEST: Enable 577 and 579 in Cloud Tests

cvmfs/cvmfs_server, packaging/debian/cvmfs/cvmfs-server.preinst, packaging/rpm/cvmfs-universal.spec
This prevents a `cvmfs_server migrate` to run on a repository that is in a transaction. If a user runs into this situation he probably updated the CernVM-FS server software with an open transaction from the previous version. That might result in data loss, depending on what actions the `cvmfs_server migrate` performs (see 2.2.0 --> 2.3.0 step for example).
Furthermore this adds a pre-install check to both RPM and debian package that prevents their install if an open transaction on one of the hosted Stratum0s is detected.
Finally this adds the upcoming CernVM-FS 2.2.2 release version to the migration paths.
=> Block Repository Migration in Transaction

packaging/rpm/cvmfs-universal.spec
This disables the repository open transaction check on EL4 for the `cvmfs-server` RPM. Apparently `%pretrans` is not available on this platform. Since we do not run any CernVM-FS servers on EL4 anyway, this shouldn't hurt, though.
=> FIX: Disable Repo Transaction Check doesn't work on EL4

test/cloud_testing/platforms/fedora23_x86_64_setup.sh
On Fedora 23 `dnf -y update` during platform setup is failing from time to time... apparently due to missing locale warnings. I suppose that we can ignore this and rely on downstream failures.
=> FIX: ignore failing `dnf -y update`

cvmfs/cvmfs_server
On Ubuntu 14.04 `cvmfs_server` detected the availability of `runuser` even though it wasn't there.
=> FIX: runuser detection / proper shell quotation

cvmfs/sqlitemem.cc, cvmfs/sqlitemem.h, test/unittests/t_sqlitemem.cc
There is an obvious, even better solution than `std::min(new_size, old_size)`.  If the old size can accomodate the new size, we don't need to do anything.
The new `xRealloc` stress test could trigger the segfault pretty quickly.
=> Fix reallocations by small deltas

cvmfs/swissknife_pull.cc
This fixes a problem in the retry logic of `cvmfs_server snapshot` that was introduced because of a misunderstood coverity issue.
Some code forensics for the sake of it:
Once upon a time in the old days of CernVM-FS in 2012 @jblomer [implemented some retry logic](https://github.com/cvmfs/cvmfs/commit/f24dd750f14b8c50fe054d06cea82e8f7862744e#diff-cbafdfe20a34afd8120380f2a30f2663R99) (all together with backoff and timeout) directly in `cvmfs_swissknife pull`.
This was [superseded by a retry logic implementation](https://github.com/cvmfs/cvmfs/commit/76bb985aa89743c203b15b19f01289680565bdaf#diff-cbafdfe20a34afd8120380f2a30f2663R104) in an ancient "download module" while leaving parts of the old hard-coded logic in place. Later the "download module" was [replaced by a local `DownloadManager` …
=> FIX: Pull Retry Logic

test/unittests/t_reflog.cc
Copy&Paste no time waste... d'oh!
=> FIX: Copy-Paste Mistake in T_Reflog::ContainsObject

cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/swissknife_gc.cc
When running a dry-run, `cvmfs_server gc` was updating the `Reflog` database (deleting catalog references) without deleting the actual `Catalog` (it's a dry-run after all). Oops!
Fortunately integration test 560 revealed that.
=> FIX: Don't update Reflog on Garbage Collection Dry-Run

cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h
This removes inefficiencies from the catalog update code during publishing. Profiling of these code paths revealed that path lookups and nested catalog discovery happened more often than necessary. Especially for large change sets and many touched nested catalogs we see a significant penalty.
In certain workloads one can expect a 25% speedup for the catalog updates as seen in the chart below (blue = before, green = after). This is meta-data updates per seconds over number of inserted directory entries (measured on my dev machine).
I'll put a more detailed comments into the patch itself.
=> Tuning: Speed up Catalog Updates during Publish

cvmfs/catalog.cc, cvmfs/catalog.h, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/catalog_rw.cc, cvmfs/catalog_rw.h, test/src/631-nestedstresstest/main
This parallelises the catalog committing code that is part of `cvmfs_server publish`. Depending on the size of the published change set and the number of modified catalogs, this can potentially increase the publishing speed significantly.
=> Feature: Concurrent Catalog Committing and Snapshotting

cvmfs/cvmfs_server
This fixes a minor issue with the opportunistic `Reflog` generation when more than one repository is garbage collected simultaneously. Furthermore it removes the *experimental warning* from `cvmfs_server gc`, allowing users to run garbage collection manually whenever it suits them.
=> Remove Experimental Warning From `cvmfs_server gc`

cvmfs/catalog_mgr_impl.h
This can be triggered by simply doing `attr -l /cvmfs/foo.example.com/file`.  Do we not have an integration test that does this?
=> Fix null-pointer-deref

externals/googlebench/src/configureHook.sh
It seems git won't clone into a non-empty directory, so this manually fetches and checks out the desired commit. This lets me configure for microbenchmarks without error
=> Clone googlebench the long way

cvmfs/cache_ram.cc, cvmfs/cache_ram.h, test/unittests/t_cache_ram.cc
I changed the routines for opening/closing file descriptors in the RAM cache to O(1) and switched to fixed allocation of fds. An index of used/free fds is necessary, and each `ReadOnlyFd` needs to know its position in the fd index, increasing the memory use by ~2 `int`s/fd. I was also able to remove some unneeded fields from `ReadOnlyFd`.
=> Feature o1 fds

cvmfs/libcvmfs.cc, cvmfs/libcvmfs.h, cvmfs/libcvmfs_public_syms.txt
I'd like to be able to get statistics when using libcvmfs via Parrot. Per discussion with @jblomer, this PR adds a library function to get counters reported by `cvmfs_talk`
=> Expose statistics counters from libcvmfs

cvmfs/cvmfs_server, test/src/636-autotagstimespan/main, test/test_functions
The parameter `CVMFS_AUTO_TAG_TIMESPAN`, which can be also set during `cvmfs_server mkfs`, allows to set a limit for the age of auto tags.  During every publish, auto tags older than the limit are automatically removed.  Like the garbage collection timespan, this parameter accepts everything that `date` can parse, for instance "4 weeks ago".
=> Allow for removal of old auto tags (CVM-982)

cvmfs/CMakeLists.txt, cvmfs/malloc_heap.cc, cvmfs/malloc_heap.h, test/unittests/CMakeLists.txt, test/unittests/t_malloc_heap.cc
A "heap allocator" for the RAM cache.  It mmap's one large chunk on construction and stays within this chunk.  It is copying (compacting), i.e. when the cache gets cleaned up, the surviving blocks will be compacted.  In effect, this allocator is  supposed to provide optimal utilization.
The cost is that every blocks needs to be prepended with an identifier that allows the user of this allocator to fix the pointers when it comes to a `Compact()`.  For the RAM cache, it means that both content hash and content need to be stored in memory.  For average object sizes of 4k, the waste is still below the percent level.
=> Custom allocator for in-memory object cache

cvmfs/cvmfs_server, cvmfs/swissknife_pull.cc, cvmfs/swissknife_pull.h, test/src/637-snapshottimespan/main
For garbage-collectable repos, stops replicating the "previous root catalog" chain once the catalogs are older than the GC grace period.  Solves one point from the race described in CVM-844.
=> Allow for pruning pf previous catalogs during pull

cvmfs/catalog_traversal.h, cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/garbage_collection/gc_aux.h, cvmfs/garbage_collection/gc_aux_impl.h, cvmfs/reflog.cc, cvmfs/reflog.h, cvmfs/reflog_sql.cc, cvmfs/reflog_sql.h, cvmfs/swissknife_gc.cc, cvmfs/swissknife_pull.cc, cvmfs/swissknife_sign.cc, test/src/637-gcaux/main, test/test_functions, test/unittests/t_garbage_collector.cc, test/unittests/t_reflog.cc, test/unittests/testutil.cc, test/unittests/testutil.h
- Sweep auxiliary files (history, meta info, certificate)
- Use reflog timestamp instead of catalog-inherent one
=> Garbage collection fixes

cvmfs/upload_facility.cc, cvmfs/upload_facility.h, cvmfs/upload_local.cc, cvmfs/upload_local.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h, test/unittests/t_file_processing.cc, test/unittests/t_upload_facility.cc, test/unittests/testutil.h
This centralises some code paths that have been duplicated in concrete implementations of `AbstractUploader`. Especially handling `Job` acquisition and dispatching, `AbstractUploader` event loop and temporary file handling. This is a spin-off of the implementation of the `LevelDbUploader` class.
=> Refactor: Eliminate some Code duplications in `Uploaders`

cvmfs/cache_ram.cc, cvmfs/kvstore.cc, cvmfs/kvstore.h, test/unittests/t_kvstore.cc
Since `KvStore` doesn't expose memory allocation directly to callers anymore, there's no strong reason to include logic for `realloc`. See comments in #1685
=> Remove kvstore realloc

cvmfs/download.cc
This isn't easy to test in a regression test because we don't want to assume that /etc/grid-security/certificates exists on the testing machine.  So I think it's fine to just fix the code.
See [CVM-1083](https://sft.its.cern.ch/jira/browse/CVM-1083) for more details.
=> use default X509_CERT_DIR also if it is empty string

.travis.yml, cvmfs/platform_linux.h, cvmfs/platform_osx.h, mount/mount.cvmfs.cc, test/unittests/t_platforms.cc
* Remove conditional code based on major.minor.path version string
since it's no longer needed for supported versions of macOS
(10.11 and 10.12)
* Removing platform_get_os_version function and its unit test
=> macOS 10.12 - Fixes client failure due to OS version string

cvmfs/sync_item.h, cvmfs/sync_mediator.cc, cvmfs/sync_mediator.h, cvmfs/sync_union.cc, cvmfs/sync_union.h, test/src/639-specialfiles/main
This commit fixes the problem with publishing a transaction
when there are special files added to the repository
and OverlayFS is used as a UnionFS driver.
Whiteout files in OverlayFS are represented as character devices
with both major and minor numbers 0. OverlayFS driver doesn't allow
users to create such files.
Both block and character devices will be ignored with a warning message
printed out.
A new SyncItemType is introduced: kBlockDevice
SyncItem has 4 new methods:
- GetMajor
- GetMinor
- IsBlockDevice
- IsSpecialFile
Handling special files may change in future in the following ways:
- fail by default, enable explicitly in config to ignore with warning
- add special files to the repo
=> Add support for handling special files when using OverlayFS

cvmfs/cvmfs_server
I noticed that all the other traps in cvmfs_server follow this convention.
=> follow trap convention for snapshot -a

cvmfs/cvmfs_server, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, cvmfs/sync_mediator.cc, cvmfs/sync_union.cc, cvmfs/sync_union.h, test/src/639-specialfiles/main
This change preserves old behavior for working with special files (stop publishing by default).
The configuration variable CVMFS_IGNORE_SPECIAL_FILES is introduced.
When this variable is set to true, special files will be ignored with and a warning message will be printed for each of them.
Otherwise, on first encounter of a special file (which is not a whiteout) a warning message will also be printed, but publishing will stop.
=> Add configuration variable to enable ignoring special files

cvmfs/cvmfs_config, cvmfs/download.cc, cvmfs/download.h, cvmfs/loader_talk.cc, test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/fedora24_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64-gcov_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1510_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1604_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh, test/unittests/t_header_lists.cc
Aimed at better resilience against rogue stratum 1s.  Includes also two minor fixes for `cvmfs_config umount`
=> Host failover after no-cache attempt on corrupted data

cvmfs/make_cvmfs_server.sh, cvmfs/server/cvmfs_server_apache.sh, cvmfs/server/cvmfs_server_chown.sh, cvmfs/server/cvmfs_server_coda.sh, cvmfs/server/cvmfs_server_common.sh, cvmfs/server/cvmfs_server_import.sh, cvmfs/server/cvmfs_server_json.sh, cvmfs/server/cvmfs_server_list.sh, cvmfs/server/cvmfs_server_migrate.sh, cvmfs/server/cvmfs_server_mkfs.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/server/cvmfs_server_snapshot.sh, cvmfs/server/cvmfs_server_sys.sh, cvmfs/server/cvmfs_server_util.sh, cvmfs/server/test_cvmfs_server_util.sh
Some refactoring to the cvmfs_server scripts for better maintainability:
1. Split platform dependent functions to `cvmfs_server_sys.sh`, for example: calling the `uname` command, checking for files etc.
2. Updated the rest of the `cvmfs_server_*****` scripts to call the encapsulated functions (instead of calling `uname` directly, call `cmvfs_sys_uname` ...)
3. Added example test script for the `check_overlayfs_version` function, using mocking
4. Updated the `cvmfs_overlay_version` function to accept kernel 3.10.0-493 or newer, on RedHat. This change is required for ticket CVM-835 and will be backported there.
=> Cvmfs server platform functions

cvmfs/cvmfs_server, test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/fedora22_x86_64_test.sh, test/cloud_testing/platforms/fedora23_x86_64_test.sh, test/cloud_testing/platforms/fedora24_x86_64_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1510_x86_64_test.sh, test/cloud_testing/platforms/ubuntu1604_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh, test/src/700-overlayfsvalidation/main
=> Updated OverlayFS for RedHat 7 (CVM-835)

.clang-format, .dir-locals.el, .vscode/settings.json, cvmfs/swissknife_lease.cc, cvmfs/swissknife_lease.h, cvmfs/swissknife_lease_curl.cc, cvmfs/swissknife_lease_curl.h, cvmfs/swissknife_lease_json.cc, test/unittests/CMakeLists.txt, test/unittests/t_swissknife_lease.cc
This contains the implementation of the suggestions from PR #1730.
* Unit tests for JSON parsing (from `swissknife_lease_json.cc`)
* Remove the use of C++ streams
* Use a unique identifier suffix for session token files
* Use "cvmfs" as Curl user agent string
* Repository services API versioning
* Minor additions and fixes
=> CVM-1130 code review suggestions

cvmfs/cvmfs_config
Same as #1759, this time on `devel`
=> cvmfs_config: remove call to load_osxfusefs

cvmfs/cvmfs_config
Fixes error in `cvmfs_config` when calling `load_osxfusefs`. This file no longer exists in more recent versions of OSXFUSE. The `KextManager` API is used instead.
Fixes CVM-1101.
=> Fixing error in cvmfs_config re: load_osxfusefs

test/cloud_testing/platforms/centos7_x86_64_setup.sh
Fixes an error in the integration test platform setup script for CentOS 7. The error was happening on newly provisioned machines, which didn't have `/var/spool/cvmfs`.
=> Fix integration test setup script on CentOS 7

test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/centos7_x86_64_test.sh
This addresses the most recent failures of the integration tests on CentOS 7.
* Don't try to create ephemereal storage for the CVMFS cache on a second block device (`/dev/vdb`). The new flavour of CentOS 7 VM doesn't not have this device.
* Don't create an EXT4 partition for `/var/spool/cvmfs`. The default XFS root partition can be used.
=> Fix integration tests centos7

test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/centos7_x86_64_test.sh
Same as #1777.
Additionally activates the server integration tests on CentOS 7, which were apparently disabled (!?) at a certain point.
=> Fix integration tests centos7 devel

cvmfs/cvmfs_server
Removing the check in `cvmfs_server` for the file system type of `/var/spool/cvmfs`. Previously, only ext4 was allowed, but we should also allow XFS.
I've run the first 10 server integration tests in a CentOS 7 VM. Attached the log file, since there are a few failures.
[integration_log.txt](https://github.com/cvmfs/cvmfs/files/738866/integration_log.txt)
=> CentOS 7 integration tests - remove ext4 check

.travis.yml
Disable the Travis-CI check on Mac OS X for this branch, since we are no longer able to compile `cvmfs-2.3` on any of the Mac OS X images offered by Travis.
=> Disable travis on osx (cvmfs-2.3)

.travis.yml
On the `devel` branch, we are no longer tied to a specific version of Mac OS X. We can use the default image provided by Travis.
=> Use default OS X image on Travis-CI

test/cloud_testing/platforms/ubuntu1204_x86_64_test.sh
Fixes the integration test setup on Ubuntu 12.04. The VM image that we are using no longer has `/dev/vdb`.
=> Integration tests: removing ephemereal storage for Ubuntu 12.04

cvmfs/cvmfs_server, test/cloud_testing/platforms/centos7_x86_64_setup.sh
* Re-enable the check that `/var/spool/cvmfs` is located on an EXT4 partition, when running on CentOS 7.
* In the CentOS 7 integration test setup script, place the `/var/spool/cvmfs` directory on an EXT4 partition.
=> Fix overlayfs check centos7

test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/ubuntu_x86_64_test.sh
* Install `java-1.8.0-openjdk` on CC7 to fix proxy failover integration test
* Disable overlayfs validation test on Ubuntu 14.04: the OS image needs to be update run Linux 3.18+ in order to support overlayfs. Currently running 3.13.
=> Last minute integration test fixes

bootstrap.sh, cvmfs/CMakeLists.txt
* The CMake install command for TBB wasn't installing the libraries with the full name (i.e. `libtbb_cvmfs.so.2` and `libtbbmalloc_cvmfs.so.2`).
* (optimization) Don't build the TBB dependency in `bootstrap.sh` unless `BUILD_SERVER` is enabled.
=> TBB install fixes

cvmfs/pack.cc, cvmfs/pack.h, test/unittests/t_pack.cc
Addresses JIRA ticket CVM-1131
This PR brings some improvement and extensions to the ObjectPack classes, such that they can be used for file serialization with the HttpUploader spooler backend.
* API cleanup of the classes `ObjectPack`, `ObjectPackProducer`, `ObjectPackConsumer`
* Adding support for named files in the object packs, not only content addressed binary blobs.
* Updating producer and consumer classes to serialize/deserialize named files
* Updating unit tests
=> Extend ObjectPack classes

cvmfs/cvmfs_config, packaging/rpm/cvmfs-universal.spec
Uses `cvmfs_config setup` to work around dodgy kill mode in autofs systemd unit on CentOS 7.  See CVM-1200.
=> Work around autofs bug in CentOS 7 systemd unit

test/unittests/t_util.cc
T_Util WaitForChild was failing on macOS due to the following call: `execvp("/bin/true", argv)`. On macOS, the correct path is `/usr/bin/true`.
=> Fixing failing unittest on macOS

cvmfs/server/cvmfs_server_abort.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/server/cvmfs_server_transaction.sh, cvmfs/session_context.cc, cvmfs/session_context.h, cvmfs/swissknife_lease.cc, cvmfs/swissknife_lease.h, cvmfs/swissknife_lease_curl.cc, cvmfs/swissknife_lease_curl.h, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, cvmfs/upload_gateway.cc, cvmfs/upload_gateway.h, cvmfs/upload_spooler_definition.cc, cvmfs/upload_spooler_definition.h, test/unittests/t_gateway_uploader.cc, test/unittests/t_session_context.cc
Addresses [CVM-1191](https://sft.its.cern.ch/jira/browse/CVM-1191) and [CVM-1193](https://sft.its.cern.ch/jira/browse/CVM-1193).
* All the requests (new lease, drop lease, submit payload) made to the HTTP gateway API are now signed with an HMAC computed with a pre-shared secret key.
* The shared key is configured through the `CVMFS_KEY` configuration option, written in the server onfiguration file (`server.conf`) of the repository. Right now the key has a test format - first line is the public key id, second line is the secret - but this can be updated in the future to use standard key formats.
* The gateway services (`cvmfs_services`) checks the HMAC added to all the requests.
=> Use HMAC for signing HTTP gateway API requests

cvmfs/session_context.cc
This is just a small tweak:
When submitting a payload, include the digest of the
payload (ObjectPack) as an additional field of the JSON message
body. The digest can be used to verify the correct transfer of the
payload to the gateway services.
=> Include ObjectPack digest when submitting payload.

cvmfs/CMakeLists.txt, cvmfs/gateway_util.cc, cvmfs/gateway_util.h, cvmfs/server/cvmfs_server_abort.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/server/cvmfs_server_transaction.sh, cvmfs/session_context.cc, cvmfs/swissknife_lease.cc, cvmfs/swissknife_lease_curl.cc, cvmfs/upload_gateway.cc, test/unittests/CMakeLists.txt
This PR brings some improvements to the gateway API:
1. Gateway key handling is now done in a forward compatible manner, which will allow supporting multiple types of keys:
The file with the configuration of the gateway keys of a repo is listed in the `CVMFS_GATEWAY_KEYS` variable, in the repo's `server.conf`. The file mentioned here can have multiple key definitions, one per line, as follows:
`<KEY_TYPE> <KEY_DEFINITION>`
where `<KEY_TYPE>` and `<KEY_DEFINITION>` are separated by a space.
Currently the only key type recognized is:
`test <KEY_ID> <SECRET>`
2. Adding version information to all the gateway API requests.
The API request for a new lease now must include the `api_version` field in the JSON body. In its reply, the gateway services will include the `max_api_version` field, equal …
=> Gateway API cleanup

.vscode/settings.json, cvmfs/cache.cc, cvmfs/cache.h, cvmfs/cache.proto, cvmfs/cache_extern.cc, cvmfs/cache_extern.h, cvmfs/cache_plugin/channel.cc, cvmfs/cache_plugin/channel.h, cvmfs/cache_plugin/cvmfs_cache_null.cc, cvmfs/cache_plugin/cvmfs_cache_ram.cc, cvmfs/cache_plugin/libcvmfs_cache.h, cvmfs/cache_posix.cc, cvmfs/cache_posix.h, cvmfs/cache_tiered.cc, cvmfs/cache_tiered.h, cvmfs/cache_transport.cc, cvmfs/cvmfs.cc, cvmfs/fd_table.h, cvmfs/loader.h, test/src/070-tieredcache/main, test/unittests/t_cache.cc, test/unittests/t_cache_extern.cc
The state of external and tiered cache managers is rescued during fuse module reload.  Also, a supervised plugin does not shutdown itself during the short period where there might be no active connections.
=> Fix reloading of the fuse module with external and tiered cache managers

.vscode/settings.json, cvmfs/CMakeLists.txt, cvmfs/cvmfs.cc, cvmfs/cvmfs.h, cvmfs/duplex_fuse.h, cvmfs/fuse_evict.cc, cvmfs/fuse_evict.h, cvmfs/fuse_inode_gen.h, cvmfs/fuse_remount.cc, cvmfs/fuse_remount.h, cvmfs/glue_buffer.h, cvmfs/libcvmfs.cc, cvmfs/libcvmfs_int.cc, cvmfs/libcvmfs_int.h, cvmfs/loader.cc, cvmfs/loader.h, cvmfs/talk.cc, cvmfs/talk.h, test/src/550-livemigration/main, test/src/633-changedfiles/main, test/unittests/CMakeLists.txt, test/unittests/t_fuse_evict.cc, test/unittests/t_glue_buffer.cc
This PR moves the code for applying new file system snapshots from the fuse main module into a `FuseRemounter` class.  Things are a little bit better documented now and partially unit tested.  We also get rid of the `alarm()` signal handling code.
Invalidating the kernel caches is now being done by a `FuseInvalidator`, which, on modern fuse (2.9 / EL7 and newer), will actively kick out entries from the kernel caches.  In most cases, this gets rid of 1 minute waiting time and results in immediate application of the new file system snapshot.  Along with it, there is a new command `cvmfs_talk remount sync` which only returns once the new file system snapshot is available.
=> Refurbish client remount code, use active cache eviction with modern fuse

cvmfs/mountpoint.cc, cvmfs/mountpoint.h, cvmfs/talk.cc, cvmfs/wpad.cc, cvmfs/wpad.h, test/src/031-cacheautoproxy/main
If resolving auto proxies fails, use last known good configuration from cache.
=> Cache proxy settings in workspace directory

.vscode/settings.json, ChangeLog, cvmfs/cache_posix.cc, cvmfs/mountpoint.cc, cvmfs/mountpoint.h, cvmfs/quota_posix.cc, cvmfs/quota_posix.h, test/cloud_testing/platforms/slc6_x86_64-NFS_test.sh, test/src/032-workspace/main, test/unittests/t_quota.cc
Used for "exotic" settings where the cache directory is not an alien cache but might not support sockets, named pipes, or POSIX locks.  `CVMFS_WORKSPACE` is a dangerous setting as it allows to circumvent necessary locking around access to a cache directory.
=> Fix location of posix quota manager locks with CVMFS_WORKSPACE

cvmfs/swissknife_diff_tool.cc
This should fix the build on SLES 4,5,6, SUSE 11 and 12 etc.
As far as I can tell, the newer compilers are less strict when it comes to the initialization of a super class which is an instantiation of a ckass template.
=> Fix initialization of super class in swissknife::DiffTool

cvmfs/catalog_diff_tool_impl.h
CatalogDiffTool - sort old and new listings before comparing. This instruction was lost during the development of CVM-1268.
=> Fix integration test 641

cvmfs/receiver/catalog_merge_tool_impl.h
Addresses the crash described in [CVM-1298](https://sft.its.cern.ch/jira/browse/CVM-1298).
The crash was caused by dereferencing a pointer to the stack after the value was deallocated.
=> Fix crash in cvmfs_receiver

cvmfs/sanitizer.cc, cvmfs/sanitizer.h, cvmfs/server/cvmfs_server_mkfs.sh, cvmfs/server/cvmfs_server_ssl.sh, cvmfs/util/posix.cc, test/src/500-mkrepo/main, test/unittests/t_sanitizer.cc, test/unittests/t_util.cc
Fixes two issues with long repository names:
- CN in X.509 certificate
- Unix domain sockets with long paths
Enforce a limit of 60 characters.
=> Support for repository names up to 60 characters

.dir-locals.el, cvmfs/platform_linux.h, cvmfs/platform_osx.h, test/unittests/t_platforms.cc
Addresses [CVM-1185](https://sft.its.cern.ch/jira/browse/CVM-1185).
Fixes the warning about the deprecation of `OSSpinLock` on macOS 10.12+. On this version of macOS and newer, `os_unfair_lock` is used instead.
=> Fix deprecation warnings for OSSpinLock on macOS 10.12+

cvmfs/cvmfs_talk
Changes usage message, specifying |-p pipe] instead of |-p socket]
=> fix usage message

cvmfs/mountpoint.cc
See [CVM-1322](https://sft.its.cern.ch/jira/browse/CVM-1322)
It was easy to prevent the inheritance, but now if somebody attempts to use an external server it says "malformed URL" instead of "host returned HTTP error".  It's slightly more informative, but not a lot.  I would like to add an error message saying that the external url was not set, but I can't figure out exactly where to put it.  The debug log shows "failed to fetch Part of ..." but it isn't clear to me where the external fetcher is called from nor how easy it is to check inside of Fetcher::Fetch() for this condition.
=> prevent external server url from inheriting regular server url

cvmfs/server/cvmfs_server_import.sh, cvmfs/server/cvmfs_server_mkfs.sh, cvmfs/server/cvmfs_server_util.sh, cvmfs/server/test_cvmfs_server_util.sh
See [CVM-1186](https://sft.its.cern.ch/jira/browse/CVM-1186)
This also applies the filesystem check to non-redhat systems with kernels >= 4.2.0 which I think was the original intention.
=> improve overlayfs error messages & allow ext3 scratch filesystem

cvmfs/util/shared_ptr.h
Removing the check of `this->value_`, which doesn't make sense in a constructor.
=> Fixing warning in the SharedPtr class

cvmfs/logging.cc, cvmfs/logging_internal.h, cvmfs/receiver/catalog_merge_tool_impl.h, cvmfs/receiver/commit_processor.cc, cvmfs/receiver/payload_processor.cc, cvmfs/receiver/reactor.cc, cvmfs/receiver/receiver.cc, test/unittests/t_reactor.cc
This addresses [CVM-1337](https://sft.its.cern.ch/jira/browse/CVM-1337) on the `cvmfs_receiver` side.
`cvmfs_receiver` now does all logging into syslog. The syslog and logrotate configurations for `cvmfs_receiver` are installed by the storage gateway application in its own set up script.
=> CVM-1337 Unified logging for storage gateway

test/src/641-diff/main
The output of the `cvmfs_server diff` command has changed and the output
expected in the test was out of date.
=> Fixing integration test 641-diff

test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_test.sh, test/test_functions
Addresses [CVM-1354](https://sft.its.cern.ch/jira/browse/CVM-1354).
This can be merged after the 2.4.0 release is branched.
Reactivates the integration tests for the repository services application, now that building the repo services tarball has been integrated with Jenkins CI.
* Update integration test scripts to pick up the repo services tarball from it's new location (where it is placed by the CvmfsBuildRepoServices Jenkins job)
* Re-enable integrations tests 80x for Ubuntu 1604, SLC6, CC7
=> Reactivate integration tests for CVMFS Repository Services

cvmfs/receiver/params.cc
The new CVMFS_ENFORCE_LIMITS parameter is made optional for the
cvmfs_receiver application.
=> Fixing server parameter parsing in cvmfs_receiver app

test/test_functions
This fixes the GW services integration tests on RedHat platforms.
=> Fixing pkgmap names in test_functions::set_up_repository_services

cvmfs/catalog_diff_tool_impl.h, cvmfs/server/cvmfs_server_abort.sh, cvmfs/swissknife_lease.cc, test/src/800-repository_services/main, test/src/801-repository_services_slow/main, test/src/802-repository_services_nested_catalogs/main
This addresses [CVM-1359](https://sft.its.cern.ch/jira/browse/CVM-1359).
* Fixes memory error in swissknife_lease.cc causing crash during `cvmfs_server abort`.
* Fixes recursion bug in `CatalogDiffTool` causing catalog corruption when directories were deleted
* Adds more tests cases and checks to the repository service integrations tests.
=> Fix some issues discovered during large publications with GW backend

cvmfs/catalog_mgr_rw.cc
Addresses [CVM-1364](https://sft.its.cern.ch/jira/browse/CVM-1364).
Spooler::ProcessCatalog should be used to submit catalogs, instead of Spooler::Upload, to ensure that the catalogs are properly handled as content-addressed files by the receiver process on the gateway.
=> Fix catalog processing and uploading with gateway backend

cvmfs/session_context.cc
Add error logging when a submission error is encountered in the gateway uploader and abort the process.
=> Gateway uploader: abort on payload submission error

cvmfs/receiver/commit_processor.cc, cvmfs/receiver/params.cc, cvmfs/receiver/params.h, cvmfs/receiver/payload_processor.cc, cvmfs/receiver/payload_processor.h, cvmfs/upload_gateway.cc, test/test_functions, test/unittests/t_payload_processor.cc, test/unittests/t_reactor.cc
Addresses [CVM-1264](https://sft.its.cern.ch/jira/browse/CVM-1264).
Removes all hardcoded values for temporary directories (i.e. /srv/cvmfs/<REPO_NAME>/data/txn) and Stratum0 URL from the `cvmfs_receiver` application. All values are now read from the repo's `server.conf` file and all files are transfered to/from the repository upstream storage using the appropriate objects (`DownloadManager`, `Uploader` etc.).
The `cvmfs_receiver` tool now also responds to an optional configuration parameter in `server.conf`: `TEST_CVMFS_RECEIVER_UPSTREAM_STORAGE` - this is only useful for integration tests where the release manager and the gateway are running on the same machine, and allows specifying the upstream storage string for the `cvmfs_receiver` (in this test configuration, `cvmfs_server` needs …
=> Enable the use of the CVMFS gateway services with S3 storage backend

cvmfs/swissknife_graft.cc
Previously, a new chunk would be emitted after `N+(buffer size)` bytes when the user requested N bytes for chunk size.  So, if the user wanted a 24MB chunk, CVMFS would create `24MB+16KB` chunks.
This corrects the issue; 24MB chunks are created when 24MB chunks are requested for grafts.
=> Fix off-by-one error for chunk size.

cvmfs/options.cc, test/unittests/t_raii_temp_dir.cc
Currently, `YES`, `ON`, or `1` indicate truth for a boolean option; this also allows `TRUE`.
=> Make `true` to be a valid boolean option.

test/test_functions
This PR (finally) fixes the platform distro detection part of the `set_up_repository_services` function in `test/test_functions`.
The gateway service integration test are now run during the integration tests, on Ubuntu 16.04, SLC6 and CC7, all on x86_64.
[Integration test results with this PR](https://epsft-jenkins.cern.ch/view/CVMFS/job/CvmfsCloudTesting/218/).
=> Fix test functions setup repo services

cvmfs/catalog_diff_tool_impl.h, cvmfs/receiver/catalog_merge_tool_impl.h, test/src/802-repository_services_nested_catalogs/main
Summary:
* Fixes issues regarding the deletion of nested catalogs in the `cvmfs_receiver` tool used by the gateway service application.
* Ensures the early termination of recursion in the `CatalogDiffTool` class, in the case that unchanged nested catalogs are encountered.
* Adds test cases to the gateway services integration tests to check the creation of nested catalogs with `.cvmfsdirtab`.
=> Fix nested catalog handling in gateway services / cvmfs_receiver

cvmfs/authz/authz_fetch.cc, cvmfs/authz/authz_fetch.h, test/src/632-authzhelpers/main
Although I haven't quite figured out why, we have a few crashing `cvmfs_x509_helper` processes on one of the OSG sites.
In order to avoid permanent black-hole nodes, this allows the CVMFS authz helper to restart after `kChildTimeout` seconds (I considered an immediate restart, but I am worried about continuously churning processes).
=> Restart authz_helper process after a cool-off period.

cvmfs/cache_posix.cc, cvmfs/cache_posix.h, cvmfs/mountpoint.cc, test/unittests/t_cache.cc
Allows for placing an alien cache on BeeGFS where the `rename()` and `link()` calls have to be on files in the same directory.
=> Create temporary files in final directory on BeeGFS / alien cache

cvmfs/CMakeLists.txt, cvmfs/receiver/catalog_merge_tool.h, cvmfs/receiver/catalog_merge_tool_impl.h, cvmfs/receiver/commit_processor.cc, cvmfs/receiver/lease_path_util.cc, cvmfs/receiver/lease_path_util.h, cvmfs/receiver/payload_processor.cc, cvmfs/server/cvmfs_server_health_check.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/swissknife_sync.cc, test/quickcheck/CMakeLists.txt, test/unittests/CMakeLists.txt, test/unittests/t_lease_path_util.cc
Addresses [CVM-1393](https://sft.its.cern.ch/jira/browse/CVM-1393).
* Corrects the sanity checks in the `CatalogMergeTool` class.
* When publishing to a repository with a gateway upstream, do not trigger an error when local and remote root hashes differ.
=> Fixes some issues encountered in the benchmark with multiple release managers

cvmfs/catalog_diff_tool_impl.h, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/catalog_rw.cc, cvmfs/catalog_rw.h, cvmfs/receiver/catalog_merge_tool_impl.h
Addresses [CVM-1405](https://sft.its.cern.ch/jira/browse/CVM-1405).
Performance optimization.
Adds a parameter to the `WritableCatalogManager::RemoveNestedCatalog` function to allow removing the nested catalog including its contents. By default, the behaviour of the function is unchanged (i.e. the nested catalog is removed and its contents are merged into its parent).
For the moment, the new functionality is only be used on the repository gateway, in the `CatalogMergeTool` class.
Nested catalog handling in  `CatalogMergeTool` is already tested in the integration test `802-repository_services_nested_catalogs`.
=> Remove a nested catalog's subtree in constant time

packaging/debian/config-default/control, packaging/debian/config-none/control, packaging/debian/cvmfs/control
https://sft.its.cern.ch/jira/browse/CVM-1420
I have tested this on my Debian machine with cvmfs-config-default and cvmfs-config-none in a local apt repository, works as expected.
=> Turn cvmfs-config into Debian virtual package, default cvmfs-config-default

cvmfs/cache.h, cvmfs/cache_posix.h, cvmfs/cache_tiered.cc, cvmfs/cache_tiered.h, cvmfs/catalog_mgr_client.cc, cvmfs/mountpoint.cc, cvmfs/options.cc, cvmfs/stratum_agent/stratum_agent.cc, cvmfs/swissknife_check.cc, cvmfs/swissknife_diff.cc, cvmfs/swissknife_gc.cc, cvmfs/swissknife_lsrepo.cc, cvmfs/swissknife_pull.cc, cvmfs/util/posix.cc, cvmfs/util/posix.h, test/unittests/t_cache_extern.cc, test/unittests/t_cache_tiered.cc, test/unittests/t_mountpoint.cc, test/unittests/t_quota.cc, test/unittests/t_util.cc
A cache manager can now indicate a backing directory, which is currently only used for the cvmfschecksum file.  It could be used for other, non CAS objects which are tightly coupled to the cache.
There is not yet a means for cache plugins to pass a backing directory back to the client.
=> Introduce cache "backing directory" for checksum

cvmfs/server/cvmfs_server_fix_permissions.sh, cvmfs/server/cvmfs_server_util.sh, cvmfs/swissknife_sync.cc, cvmfs/swissknife_sync.h, test/src/649-zeropermission/main
The CAP_DAC_READ_SEARCH capability is necessary to publish containers, in particular the /etc/shadow files in containers with mode 000.
=> Add dac_read_search capability to publish forbidden files

cvmfs/server/cvmfs_server_abort.sh, cvmfs/server/cvmfs_server_common.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/server/cvmfs_server_transaction.sh, test/src/800-repository_services/main, test/src/801-repository_services_slow/main, test/src/802-repository_services_nested_catalogs/main
Addresses [CVM-1445](https://sft.its.cern.ch/jira/browse/CVM-1445).
With these changes, you no longer need to supply the "-e" parameter for `cvmfs_server {transaction,publish,abort}` when working with a repository gateway upstream.
=> Remove "-e" parameter from cvmfs_server {transaction,publish,abort} (GW)

cvmfs/gateway_util.cc, test/test_functions
Related to [CVM-1427](https://sft.its.cern.ch/jira/browse/CVM-1427).
Only modifies the set up function of the repository gateway integration tests.
=> Fix integration tests for gateway key subpath permissions

cvmfs/server/cvmfs_server_gc.sh
This typo happens to have no effect because the calling function's correctly-spelled variable is in the environment of the called function, but it is both passed incorrectly and set incorrectly inside the function, with an appended 's'.
=> fix typo in preserve_timestamp variable

cvmfs/cvmfs.cc, cvmfs/file_watcher.cc, cvmfs/file_watcher.h, cvmfs/mountpoint.cc, cvmfs/mountpoint.h, test/unittests/t_file_watcher.cc
Related to [CVM-496](https://sft.its.cern.ch/jira/browse/CVM-496).
This addresses the issue where the background thread of the `FileWatcher` object responsible for reacting to changes in the `/etc/resolv.conf` file was spawned too early, before the main client process forks to background.
=> FileWatcher background thread should be spawned after process fork

cvmfs/wpad.cc
This situation is normal now that WLCG WPAD is returning backup proxies with openhtc.io servers, and this PR removes the big ugly syslog messages.
=> Do not put message about wpad alt proxies in syslog

cvmfs/CMakeLists.txt, cvmfs/swissknife_sync.cc, cvmfs/sync_union.cc, cvmfs/sync_union.h, cvmfs/sync_union_aufs.cc, cvmfs/sync_union_aufs.h, cvmfs/sync_union_overlayfs.cc, cvmfs/sync_union_overlayfs.h
I splitted the the sync_union implementation into different files.
Then I made it compile and change the dependences of swissknife_sync.
Moreover, I remove useless (I believe) includes (shouldn't they big catch at compile time?)
Finally I apply the standard google formatter, overall I like the formatter but somewhere, made questionable choices. (Eg line: 682-685 of cvmfs/swissknife_sync.cc)
=> Splitting sync union

test/test_functions
Addresses [CVM-1470](https://sft.its.cern.ch/jira/browse/CVM-1470).
The repository gateway application is now using JSON configuration files
=> Updating initialization of repository gateway integration tests

test/test_functions
This fixes the issues with Apache being unavailable during repository (re)creation, part of the integration tests.
=> Fedora26+: Force restart of Apache when recreating test repo in integration tests

cvmfs/CMakeLists.txt
On macOS (maybe also on Linux?), the libtool command can be used
instead of the "combine_libs" script to create a stand-alone
libcvmfs_cache.a library.
=> Fix the creation of libcvmfs_cache.a on macOS

test/test_functions
The repository gateway is simpler to set up after the changes to `cvmfs_gateway` introduced in  [PR #47](https://github.com/cvmfs/cvmfs_gateway/pull/47).
=> Updating the set up function for the repository gateway integration tests

packaging/debian/cvmfs/control, test/cloud_testing/platforms/ubuntu_test.sh, test/src/641-diff/main, test/src/800-repository_gateway/main
Fixing integration tests:
* 641: `cvmfs_server diff` output has changed
* 800: Force the grep command to interpret the output of "cvmfs_server tag -l" as text
* Make the `cvmfs-server` package depend on `libcap2-bin` on Ubuntu/Debian. This package wasn't previously installed on Ubuntu 12.04, causing all the server integration tests to fail due to `setcap` not being available.
* Fix the list of excluded integration tests for Ubuntu 12.04 and 14.04
=> Fix integration tests

cvmfs/swissknife_pull.cc, test/src/610-altpath/main
When replicating a repository with bootstrapping symlinks (.cvmfsalt-...), create these links on the replica, too.
=>  Place bootstrapping symlinks on replica storage 

cvmfs/server/cvmfs_server_gc.sh, test/src/652-gctimespan/main
This check [has been introduced](https://github.com/cvmfs/cvmfs/commit/2b053d996570044239c46d56296e93e5d474fc72) for the old, time-based garbage collection.  It is not necessary anymore for the reflog based garbage collection.
=> Fix garbage collection of idle repositories

cvmfs/fuse_remount.cc, cvmfs/fuse_remount.h, test/src/078-offlinemode/main
This PR also fixes the following two problems
- Failure to load the manifest would not apply the short term TTL. Now it does.
- `cvmfs_talk remount` with a fixed catalog would crash the client.  Now it remounts.
=> Send offline mode enter/recover events to syslog 

cvmfs/server/cvmfs_server_mkfs.sh
Addresses [CVM-1503](https://sft.its.cern.ch/jira/browse/CVM-1503).
The private repository keys aren't needed on the release manager when the upstream is a repository gateway.
=> cvmfs_server mkfs - don't try to import private repo keys in GW config

cvmfs/fuse_remount.cc
Reverting "increase robustness of remount trigger thread management", which was causing a crash in the remount loop, due to a broken implementation of `poll` on macOS:
https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/
=> Fix macOS crash in remount loop

cmake/Modules/cvmfs_compiler.cmake, cmake/check_inotify_init1.c, cvmfs/CMakeLists.txt, cvmfs/platform_linux.h, get_redhat_version.sh, test/unittests/CMakeLists.txt
This patch selectively enables the `FileWatcherInotify` class and its associated tests based on the availability of `inotify_init1`.
Jenkins build is green:
https://epsft-jenkins.cern.ch/job/CvmfsFullBuildDocker/663/
=> Fix compilation on SL4 and SLC5

cvmfs/server/cvmfs_server_mkfs.sh
If `cvmfs_server mkfs` isn't run as root, `modprobe` fails quietly and the script prints `neither AUFS nor OverlayFS detected on the system!` even if those modules exist.
=> Improve error message in cvmfs_server_mkfs

packaging/debian/cvmfs/control, packaging/debian/cvmfs/copyright, packaging/debian/cvmfs/cvmfs.lintian-overrides, packaging/debian/cvmfs/cvmfs.postinst, packaging/debian/cvmfs/rules
I'd like to spend a little time cleaning up the Debian packaging process to better conform with [Debian policy](https://packages.debian.org/search?keywords=debian-policy). I have updated the policy for the `cvmfs` package (but not others) to identify itself as in compliance with 3.9.6.1, which corresponds to Debian 8 and has the effect of eliminating the warning `W: cvmfs source: ancient-standards-version 3.9.3.1 (current is 3.9.8)`.
I have rebuilt the package successfully and believe the changes I have made are harmless. I'm happy to go through all the other packages and make similarly harmless modifications if you accept this pull request.
At that point, there will be some real issues to consider. For example, [static compilation of …
=> Eliminate the following Debian packaging warnings or errors

cvmfs/util_concurrency.cc
Signal is now SingleShot.
Once Wakeup is called, every successive call to Wait will simply not wait.
Wakeup set fired_ to true and the next invocation of Wait will acquire the lock but it will not enter the main loop.
This PR reset the Wait to false so that we are forced to have a sequence of Wait -> Wakeup -> Wait -> Wakeup
I believe we could discuss if we want another class that has the MultiShot behaviour and leaving signal SingleShot, however, this one, is a quite tricky API to manage and I figure out this SingleShot behaviour only by chance...
=> Make Signal multi shot

cvmfs/history_sqlite.h, cvmfs/swissknife_migrate.cc, cvmfs/swissknife_migrate.h, test/src/653-migratemanifest/main
Fixes a long-standing bug where catalog migration (including chown, eliminate-hardlinks) would create a new minimal manifest and ignore the existing manifest and history.
=> Update existing manifest/history on catalog migrate

cvmfs/upload.h
`util_concurrency.h` define `Observable` which is the public parent of
the `Spooler` the main class of the file.
=> Add missing header util_concurrency.h

cvmfs/receiver/payload_processor.cc, cvmfs/receiver/payload_processor.h, cvmfs/receiver/reactor.cc, test/unittests/t_payload_processor.cc, test/unittests/t_reactor.cc
Addresses [CVM-1545](https://sft.its.cern.ch/jira/browse/CVM-1545).
The PayloadProcessor should detect any Spooler errors and return an error code. The cvmfs_receiver worker process can notify its supervisor process (the cvmfs-gateway application) of this error and the publication process is stopped, without going forward with the commit phase.
=> PayloadProcessor - check for Spooler upload errors

cvmfs/session_context.cc
This prevents running out of memory when publishing very large payloads to a repository gateway.
=> SessionContext - reduce max job queue size

cvmfs/receiver/catalog_merge_tool_impl.h
Addresses [CVM-1542](https://sft.its.cern.ch/jira/browse/CVM-1542).
When using the repository gateway:
* For new files, linkcount is always set to 1 (hardlinks are split).
* Removing files with linkcount > 1 is not supported.
The cvmfs_receiver will abort in this case.
=> Hardlink handling in CatalogMergeTool

cvmfs/catalog_diff_tool_impl.h, cvmfs/swissknife_check.cc
Partially addresses [CVM-1549](https://sft.its.cern.ch/jira/browse/CVM-1549).
* `CatalogDiffTool` - abort if any entry with `linkcount == 0` is encountered
*  `swissknife_check` - check that entries have `linkcount > 0`
=> Handle linkcount == 0 for catalog entries

cvmfs/receiver/payload_processor.cc, cvmfs/receiver/payload_processor.h
Addresses [CVM-1548](https://sft.its.cern.ch/jira/browse/CVM-1548).
* Make use of `Spooler::Peek` in `PayloadProcessor` to avoid redundant writes into the repository storage
* Use a larger buffer for `ObjectPack` consumers
* Use incremental hashing of payload to avoid re-reading temporary files.
=> Improved temporary file handling in PayloadProcessor

test/src/800-repository_gateway/main, test/src/801-repository_gateway_slow/main, test/src/802-repository_gateway_nested_catalogs/main, test/src/803-repository_gateway_large_files/main, test/test_functions
The `cvmfs-gateway` application is now installed into `/usr/libexec/cvmfs-gateway` and its database into `/var/lib/cvmfs-gateway`.
This PR updates the integration tests scripts, which were still referencing the old installation prefix (`/opt/cvmfs-gateway`).
=> Update cvmfs-gateway install dirs in integration tests

cvmfs/cvmfs_config
Addresses [CVM-1550](https://sft.its.cern.ch/jira/browse/CVM-1550).
* Not finding the /dev/osxfuse0 character device should be a warning not an error
* If /Library/Filesystems/osxfuse.fs doesn't exist, OSXFUSE hasn't been installed. This should be an error.
=> cvmfs_config - modify checks for OSXFUSE

cvmfs/swissknife_reflog.cc
Helpful for the cernvm-prod.cern.ch repository
=> Less agressive database checks on reflog reconstruction

test/cloud_testing/platforms/centos7_x86_64_s3_test.sh, test/cloud_testing/platforms/centos7_x86_64_setup.sh, test/cloud_testing/platforms/centos7_x86_64_test.sh, test/cloud_testing/platforms/common.sh, test/cloud_testing/platforms/common_setup.sh, test/cloud_testing/platforms/common_test.sh, test/cloud_testing/platforms/slc5_x86_64_test.sh, test/cloud_testing/platforms/slc6_x86_64-gcov_setup.sh, test/cloud_testing/platforms/slc6_x86_64-gcov_test.sh, test/cloud_testing/platforms/slc6_x86_64_s3_test.sh, test/cloud_testing/platforms/slc6_x86_64_setup.sh, test/cloud_testing/platforms/slc6_x86_64_test.sh, test/cloud_testing/platforms/ubuntu_s3_test.sh, test/cloud_testing/platforms/ubuntu_setup.sh, test/cloud_testing/platforms/ubuntu_test.sh, test/src/800-repository_gateway/main, test/src/801-repository_gateway_slow/main, test/src/802-repository_gateway_nested_catalogs/main, test/src/803-repository_gateway_large_files/main, test/test_functions
Addresses [CVM-1554](https://sft.its.cern.ch/jira/browse/CVM-1554).
This PR brings back the server integration tests using S3-backed repository storage. The "fake_s3" Ruby gem was replaced with a real S3 implementation - Minio - which is run on the same node as the tests. 
Also included is a cleanup of the setup phase of the repository gateway integration tests, allowing them to be run with local or S3 storage.
The S3-backed test suite is activated for SCL6, CC7 and Ubuntu x86_64.
=> Re-enable integration test suite with S3-backed repositories

CONTRIBUTING.md
The old link was broken, now it works.
=> Updated Google C++ style guide link.

cvmfs/server/cvmfs_server_util.sh
Reading tarball from STDIN works only with a single '-' after -t
=> fix help for the ingest command

test/unittests/t_libcvmfs.cc
The issue appears to be that the tester instance was being destructed, leaving the d0_hash pointing to nothing. This could be resolved in a number of ways (strdup the c_str, keep a reference of d0_hash as a shash::Any or string). To make it more uniform with the other two hash lookup, strdup was used. This also added some code to remove warnings about comparing signed and unsigned values for length.
I think that this only occurred on some of the systems depending on how aggressive the garbage collector is.
@jblomer take a look when you get a chance. This was tested on Fedora 26, Fedora 27, and Ubuntu 16.04 using docker.
=> Fix Libcvmfs test for Fedora and Ubuntu

cmake/Modules/cvmfs_compiler.cmake, cvmfs/CMakeLists.txt
Removes unnecessary compiler flag fixes and adds `-fwrapv` to avoid optimizations to change the Xor32 chunk detector behavior.
=> Fixes for compiler flags

cvmfs/s3fanout.cc, cvmfs/upload.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h
New S3 configuration parameters: `CVMFS_S3_MAX_RETRIES` and `CVMFS_S3_TIMEOUT`
=> S3: Improve logging and make network timeout configurable

cvmfs/directory_entry.h, cvmfs/libcvmfs.cc, cvmfs/libcvmfs.h, cvmfs/libcvmfs_int.cc, cvmfs/libcvmfs_int.h, test/common/catalog_test_tools.cc, test/common/catalog_test_tools.h, test/unittests/t_libcvmfs.cc
This addition to libcvmfs provides a functions for retrieving not only the stat information, but also information specific to CVMFS like checksum and the stored names. This also adds tests for stat and ext_stat in t_libcvmfs.
Note: this coincides with #2155 so one will need to be rebased off the other prior to merging.
=> Add extended cvmfs stat call to libcvmfs

cvmfs/receiver/commit_processor.cc, cvmfs/receiver/commit_processor.h, cvmfs/receiver/reactor.cc, cvmfs/reflog.cc, cvmfs/reflog.h, cvmfs/server_tool_impl.h, cvmfs/signing_tool.cc, cvmfs/signing_tool.h, cvmfs/swissknife_check.cc, cvmfs/swissknife_gc.cc, cvmfs/swissknife_pull.cc, test/src/805-repository_gateway_reflog/main, test/unittests/t_reflog.cc
Addresses [CVM-1560](https://sft.its.cern.ch/jira/browse/CVM-1560).
When publishing through a repository gateway, in the case of a missing reflog, the `cvmfs_server publish` command will now return an error and mention the missing reflog, instead of `abort()`-ing.
=> Fix crash of cvmfs_receiver when reflog is missing

cvmfs/mountpoint.cc
When setting up a cache workspace we set the cache_path to the cwd as it is assumed we had moved to the directory earlier in setup. This only occurs if the type is Fuse, but if the type is Library we don't `chdir`. This checks if the type is Fuse before assuming we are in the cwd for the cache.
=> Only assume workspace is cwd if in FUSE

cvmfs/statistics_database.cc
If `CVMFS_STATISTICS_DB` is not set then `Missing parameter %s in repository configuration file.` message should **not** be printed in `kLogSyslogErr` because `CVMFS_STATISTICS_DB` is an **optional** parameter.
=> Fixed log message if missing parameter CVMFS_STATISTICS_DB

cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_rw.cc, cvmfs/sync_mediator.cc
This fix is necessary when we are ingesting a tarball with hardlinks, if
there are already file with the same name and content of the hardlink
(basically only when we are ingesting twice the same tarball) we would
try to add twice the same unique hash, which produce a runtime error
violating the UNIQUE constraint in SQLite.
With this PR we simply check if the file is already there and if it is,
we eliminate it.
=> Allow to ingest tarballs with hardlink multiple times

cvmfs/sync_item_dummy.h
When ingesting a tarball we allow the user to ingest it into a specific directory, suppose `tar/foo`
Unfortunately, with the current permission, only the same owner of the repository will be able to see what files have been ingested, which is not very ergonomic.
I believe we should allow everybody to see the content of those folders.
=> add permission for other to read and execute files

cvmfs/upload_local.cc, test/src/659-print_publish_statistics/main, test/src/660-store_publish_statistics/main
I noticed that I was counting uploaded_bytes for duplicated files too, so I fixed it:
In `StreamedUpload()` I was using the `bytes_written` variable, but I couldn't tell if those bytes were actually duplicated or not.
In `FinalizeStreamedUpload()` function I can count only the real uploaded bytes, but I have to use a system call - `stat`.
I need to make this change for [#2180](https://github.com/cvmfs/cvmfs/pull/2180)'s integration tests.
=> Fix uploaded bytes count

cvmfs/hash.h, cvmfs/upload_local.cc
Count uploaded_bytes for large files splitted into smaller pieces with 'P' suffix.
=> Added a case for large files ('P' suffix)

cvmfs/garbage_collection/garbage_collector.h, cvmfs/garbage_collection/garbage_collector_impl.h, cvmfs/statistics_database.cc, cvmfs/statistics_database.h, cvmfs/swissknife_gc.cc, cvmfs/swissknife_main.cc, cvmfs/sync_mediator.cc, cvmfs/upload_facility.h, cvmfs/upload_gateway.cc, cvmfs/upload_gateway.h, cvmfs/upload_local.cc, cvmfs/upload_local.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h, test/src/660-store_publish_statistics/main, test/src/661-garbage_collector_statistics/main, test/src/662-merge_stats_tool/main, test/unittests/c_mock_uploader.h, test/unittests/t_garbage_collector.cc, test/unittests/t_upload_facility.cc
Addresses [CVM-1569](https://sft.its.cern.ch/jira/browse/CVM-1569).
- Added one counter for gc: `sz_condemned_bytes` which is used only if `CVMFS_EXTENDED_GC_STATS` variable is set to on/true/yes/1 value in `server.conf` file.
- Write garbage collector counters values in database statistics file into `gc_statistics` table
- Added two new integration tests: `662-merge_stats_tool` and `661-garbage_collector_statistics`
- Check if `repo_name` was found. (`swissknife_main.cc`)
=> Add GC metrics to release manager statistics

test/unittests/t_suid_util.cc
Using `/usr` for testing `ResolvePath`, since `/etc` is a symlink to `/private/etc` on macOS
=> Fix T_SuidUtil on Mac

ci/build_incremental_multi.sh
The GEOAPI component seems to fail to build on RedHat 4 and 5 due to the very old version of Python shipped with the system.
This PR disables building the GEOAPI component in the incremental build script on these platforms.
However, I haven't yet understood why the full build is passing.
=> Disable GEOAPI in incremental build script on Red Hat older than 6

cvmfs/sync_union_tarball.cc, cvmfs/sync_union_tarball.h
Some docker layers have this peculiar structure of having the whole content inside the `.` folder.
Basically the `.` folder is the root of the tarball, and inside it, the filesystem tree develops.
This shows up as two characters `./` prefix when we are working with the file path that breaks some ingestion.
This PR fix the issue by removing the two char if present.
Given the semantic of the two particular characters, I believe that there would no issues. But I could be wrong.
=> check for files that start with `./` and remove the prefix

test/cloud_testing/platforms/fedora_test.sh
Disable the integration test involving a symlinked `/var/spool/cvmfs` directory on Fedora.
=> Disable integration test 539 on Fedora

cvmfs/authz/authz_curl.cc
This PR fixes a segfault introduced by @djw8605 in the SciTokens patch - the wrong `void*` was being cast to an `sslctx_info` pointer.
Additionally, I took the opportunity to free up X509 data structures as soon as we hand them off to OpenSSL.
=> X509 Authentication Fixes

python/send_stats_to_graphite.py, send_stats_to_graphite.py
Addresses [CVM-1571](https://sft.its.cern.ch/jira/browse/CVM-1571).
This script sends stats to a carbon server ([graphite](https://graphiteapp.org/)) using the [pickle protocol](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-pickle-protocol) .
Usage: `send_stats_to_graphite.py [-h] <db_file> <carbon_server_IP> <carbon_server_PORT>`
This script uses  `last_timestamp_sent` file to send only the new stats data form the `db_file`.
Format of the `last_timestamp_sent` file:
- First line: last start_time sent for publish_statistics table
- Second line: last start_time sent for gc_statistics table
If the `last_timestamp_sent` file does not exist in the same directory as `db_file`, this script will create one and it will write the current UTC timestamp in the it.
=> Script for submitting publisher statistics to a Carbon server

test/unittests/t_libcvmfs.cc
Tiny changes that fix a not-critical warning of tests
=> fix small warning on a test case comparing size_t to off_t

test/quickcheck/CMakeLists.txt
This should fix the build of just the quickgen test.
As reported in CVM-1637
=> Fix build for QG

cvmfs/server/cvmfs_server_ingest.sh, cvmfs/swissknife_ingest.cc, cvmfs/swissknife_ingest.h, cvmfs/sync_union_tarball.cc, cvmfs/sync_union_tarball.h, test/src/654-tarball_ingest_special_files/main, test/unittests/t_sync_union_tarball.cc
Following the discussion on https://github.com/cvmfs/cvmfs/pull/2215 here is another implementation.
It use a fake file `$tarball_root/.cvmfscatalog` that is piped into the regular process.
=> Add option to create catalog during ingestion using a fake file

test/unittests/t_libcvmfs.cc
The variable was spelled incorrectly ("CVMFS_DEBUG_LOG") in a unittest.
This had no impact on test correctness, but the variable should be
consistently named, to avoid confusion when searching through the
project.
=> Fix typo CVMFS_DEBUG_LOG -> CVMFS_DEBUGLOG

cmake/Modules/cvmfs_compiler.cmake, cmake/Modules/cvmfs_options.cmake, cvmfs/preload.cc, cvmfs/receiver/commit_processor.cc, cvmfs/receiver/receiver.cc, cvmfs/swissknife.h, cvmfs/swissknife_main.cc, cvmfs/swissknife_pull.cc
* Adds a new CMake option `ENABLE_ASAN`
* Fixes a memory leak in `cvmfs_swissknife` parameter handling. This memory leak was reported by ASAN, but is benign, as `cvmfs_swissknife` commands are not long running.
=> Add CMake option to enable AddressSanitizer

ChangeLog, cvmfs/s3fanout.cc, cvmfs/s3fanout.h, test/cloud_testing/platforms/centos7_x86_64_s3_test.sh, test/cloud_testing/platforms/slc6_x86_64_s3_test.sh, test/cloud_testing/platforms/ubuntu_s3_test.sh, test/src/608-infofile/main
Actively set the cache-control header for immutable content-addressed objects under data to 3 days (previously: no setting) and for the .cvmfs... files to 61 seconds to avoid running into the Squid bug where "no cache" objects are cached forever.
=> Fix cache control headers for S3 backend

test/test_functions
This fixes a configuration error in the gateway integration tests with S3 backend: the CVMFS server tools were not configured with the gateway upstream address, but directly the S3 backend.
Most tests were finishing correctly, except the ones which involve acquiring a lease on a repository subpath. Trying to write files outside of this subpath should fail when a gateway is mediating the transaction, but succeeds when publishing directly to the backend, which doesn't have the concept of lease.
=> Fix gateway integration tests with S3 backend

cvmfs/server/cvmfs_server_transaction.sh, cvmfs/server/cvmfs_server_util.sh
Addresses [CVM-1611](https://sft.its.cern.ch/jira/browse/CVM-1611).
Allow setting the initial and max retry delays, and the maximum
number of retries.
The retry loop starts with the initial delay and doubles it at each
retry, until the max delay is reached.
=> Implement retry support for "cvmfs_server transaction"

cvmfs/server/cvmfs_server_abort.sh, cvmfs/server/cvmfs_server_publish.sh, cvmfs/swissknife_lease.cc, cvmfs/swissknife_lease.h, test/src/800-repository_gateway/main
Addresses [CVM-1601](https://sft.its.cern.ACch/jira/browse/CVM-1601).
In the presence of a repository gateway, the lease subpath
(i.e. repo.cern.ch/some/path/to/lock) only needs to be given to the
cvmfs_server transaction command. The abort and publish commands
can find and use the session token of the current lease.
This PR allows the following workflow:
```
$ cvmfs_server transaction repo.cern.ch/some/path
$ cvmfs_server publish repo.cern.ch
or
$ cvmfs_server abort repo.cern.ch
```
As per the existing convention, if there is a single repository configured on the machine, even the repository name can be omitted.
=> Simplify the use of cvmfs_server {abort,publish} with repository gateway

cvmfs/receiver/payload_processor.cc
The temp dir was created with permissions 666, making it only accessible
to the root user. Changing permissions to 770.
=> Fixing permissions on the temp dir used by cvmfs_receiver

cvmfs/gateway_util.cc, cvmfs/swissknife_lease.cc, cvmfs/swissknife_lease_json.cc, cvmfs/swissknife_lease_json.h, test/unittests/t_swissknife_lease.cc
Addresses [CVM-1626](https://sft.its.cern.ch/jira/browse/CVM-1626).
* Refactor error reporting in "cvmfs_swissknife lease".
* Bumping API version number to 2, matching the one used by cvmfs-gateway 0.3.1.
=> Refactored version checks between gateway and release manager

cvmfs/authz/authz_session.cc, cvmfs/authz/authz_session.h, cvmfs/mountpoint.cc, test/unittests/t_authz_session.cc
Replaces #2263 
@DrDaveD Can you test whether this change behaves as expected?
=> Clear authz session cache when upstream membership requirement changes

cvmfs/authz/authz_session.cc
See [CVM-1658](https://sft.its.cern.ch/jira/browse/CVM-1658)
=> Log to syslog when session authorization disappears

.gitattributes
Fixes the reported language for the repository on GitHub: previously was falsely reported as C due to the large number of C files in the `externals` dir. Explicitly marking `externals` as a directory for vendored dependencies makes the `linguist` tool properly report the project language as C++.
=> Adding linguist-vendored override

cvmfs/sync_item.h, cvmfs/sync_item_dummy.h, cvmfs/sync_item_tar.h, cvmfs/sync_union_tarball.cc, test/src/654-tarball_ingest_special_files/main
The first important fix is about the test.
The final `$` is necessary to tell grep to match a new line. Without it,
grep match the few catalogs that have been normally added in the test.
(The catalog under /a and /a/b)
Then we simply fix the logic, adding a new empty file called
.cvmfscatalog into the repository. Earlier it was a file called as the
base_directory where the tar is ingested.... No idea why, but the
failure of the test I believe was shadowing the error.
Finally to make everything work I had to implement a method on the
DummyDirectory. Without the implementation it would call a method in a
base class that simply assert(false), it is not bad to implement that
method for the Dummy, otherwise we would have too re-structure a lot of
code for benefits that I fail to see.
Also …
=> Enable creation of nested catalogs during ingestion

cvmfs/s3fanout.cc, cvmfs/s3fanout.h, cvmfs/upload_s3.h, test/unittests/t_s3fanout.cc, test/unittests/t_uploaders.cc
Throttles the S3 uploader for a maximum of 10 seconds on HTTP 429.  The default are 250ms, but if exists, the values of `retry-after` and `x-retry-in` headers are applied.  The last header wins.  Currently only supports only second values in these headers.
=> [S3] Handle HTTP 429 replies

cvmfs/sync_item_dummy.h
During ingestion this permision are applied when the directory we are ingesting into does not exists yet.
```
cvmfs_server ingest --tarball - --base_dir /foo/bar/fuzz
```
If any of either `foo`, `bar` or `fuzz` don't exist they have applied the permission we are changing now. It makes sense to give to the group at least the same permission level of others.
=> change permision for dummy directory from 0705 to 0755

cvmfs/ingestion/ingestion_source.h, cvmfs/upload_local.cc
Moving the removal of the cache invalidation on the correct side of the pipeline.
Performances tests are coming.
=> Move kernel cache on the correct side of the pipeline

cvmfs/ingestion/task_read.cc, cvmfs/upload_local.cc
=> invalidate kernel cache on the correct side of the pipeline

externals/c-ares/src/configureHook.sh, externals/libcurl/src/configureHook.sh, externals/pacparser/src/makeHook.sh
This fixes compilation issue on macOS Mojave, without requiring the extra header package to be installed (` /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`)
Ensure /usr/bin/clang is used for c-ares,curl,pacparser. The way it works is that `/usr/bin/clang` will call the compiler from the current active toolchain (either Xcode or Xcode Commandline Tools) with the proper include and library paths for the system SDK.
A bug in the configuration scripts of c-ares, curl and pacparser require forcing the use of `/usr/bin/clang`.
=> Build fix for macOS Mojave

cvmfs/shrinkwrap/fs_traversal.cc, cvmfs/shrinkwrap/fs_traversal.h, cvmfs/shrinkwrap/shrinkwrap.cc, test/unittests/shrinkwrap/t_fs_traversal_interface.cc
Add/clarify several stat fields for Shrinkwrap. 
The stat print cycle was move to the main loop to avoid unresponsive periods when retraversing existing repositories.
Also removed unused retries option/variable.
=> Improve shrinkwrap statistics output

cvmfs/swissknife_lease_json.cc
The output message was missing the unit of measure for the numeric value (seconds).
=> GW: Fix lease path busy message

ducc/CMakeLists.txt
The `-mod=vendor` flags force the go compiler to use only dependencies from the `vendor/` folder.
=> Forbid golang compiler to download dependencies

ci/run_unittests.sh
Revert previous change, is not necessary and breaks our tests.
=> revert use of readlink

cvmfs/sync_item_tar.cc, test/src/654-tarball_ingest_special_files/main
Overlayfs use char devices with number 0/0 to mark whiteouts.
In the previous implementation, every char device was assigned 0/0 as number.
I fix the issue assigning the correct dev numbers.
Still running the tests.
=> Fix issues with char device and overlayfs

cvmfs/server/cvmfs_server_ingest.sh
As discussed in the mail list the lock should be taken on the directory and not on the tarfile ingested.
=> fix transaction lock, use base_dir instead of tar_file

cvmfs/authz/authz_session.cc, cvmfs/catalog.cc, cvmfs/cvmfs.cc, cvmfs/cvmfs_fsck.cc, cvmfs/download.cc, cvmfs/fetch.cc, cvmfs/nfs_maps_leveldb.cc, cvmfs/nfs_maps_sqlite.cc, cvmfs/s3fanout.cc, cvmfs/shrinkwrap/fs_traversal.cc, cvmfs/swissknife_pull.cc, cvmfs/sync_mediator.cc, cvmfs/tracer.cc, cvmfs/util/plugin.h, cvmfs/util/posix.cc, cvmfs/util/posix.h, test/unittests/t_util.cc
Trying to address https://sft.its.cern.ch/jira/projects/CVM/issues/CVM-694?filter=allopenissues&orderby=cf%5B11250%5D+ASC%2C+priority+DESC%2C+updated+DESC
All almost done, the raw locks that are in the code base are better to leave in. IMHO.
The only file that I was not able to clean up is: cvmfs/logging.cc
It gives some problem when importing "util_concurrency.h" and it necessitate more investigation, nevertheless I would suggest to merge it.
=> Remove raw mutex and use MutexLockGuards

cvmfs/server/cvmfs_server_snapshot.sh
Currently it attempts to do snapshot on all files in the current working directory, expanding '*'.
=> Do nothing in snapshot -a if there are no replicas

cvmfs/manifest.cc, cvmfs/manifest.h, cvmfs/signing_tool.cc, cvmfs/swissknife_check.cc, test/src/805-repository_gateway_reflog/main
Addresses [CVM-1732](https://sft.its.cern.ch/jira/browse/CVM-1732).
* This PR makes the hash of the repository reflog available as an optional member of the manifest. This is needed for cases where `/var/spool/cvmfs/<REPO>/reflog.chksum` is not available, such as on publisher machines connected to a repository gateway.
* The manifest signing tool (`signing_tool.cc`) now obtains the reflog hash from the manifest, if the name of a file on disk containing the hash is not given.
* The `cvmfs_server check` command now falls back to the reflog hash contained in the manifest, if the "reflog.chksum" file is not present, for validating the reflog.
=> Include reflog checksum in the repository manifest

cvmfs/cache.h, cvmfs/cache.proto, cvmfs/cache_extern.cc, cvmfs/cache_extern.h, cvmfs/cache_plugin/channel.cc, cvmfs/cache_plugin/channel.h, cvmfs/cache_plugin/cvmfs_cache_null.cc, cvmfs/cache_plugin/cvmfs_cache_ram.cc, cvmfs/cache_plugin/libcvmfs_cache.cc, cvmfs/cache_plugin/libcvmfs_cache.h, cvmfs/cache_posix.cc, cvmfs/cache_posix.h, cvmfs/cache_tiered.cc, cvmfs/cache_tiered.h, cvmfs/cache_transport.cc, cvmfs/catalog_mgr_client.cc, cvmfs/manifest.cc, cvmfs/manifest.h, cvmfs/swissknife_pull.cc, test/unittests/CMakeLists.txt, test/unittests/cache_plugin/t_cache_plugin.cc, test/unittests/t_cache_extern.cc, test/unittests/t_cache_tiered.cc, test/unittests/t_manifest.cc, test/unittests/t_mountpoint.cc
The .cvmfschecksum files are used to remember the last good root catalog in a local cache.  This is now wrapped in the Breadcrumb abstraction and part of the cache manager interface.  It should fix various corner cases with uncommon cache manager configurations, where previously it was unclear where to store/load the .cvmfschecksum data.
=> Add breadcrumb abstraction for .cvmfschecksum files

cvmfs/loader.cc, mount/mount.cvmfs.cc
Something like this is needed along with pr #2361 in order for an unprivileged user to not have to select a specific CVMFS_NFILES matching their ulimit -Hn.
=> Turn failure to set requested CVMFS_NFILES into a warning

cvmfs/dns.cc, cvmfs/dns.h
ParseHostFile accessed out-of-bounds index of a string in case of
trailing blanks in parsed hosts file.
Remake the hosts file parsing.
=> dns.cc: fix ParseHostFile

cvmfs/webapi/cvmfs-api.wsgi
As of Fedora 30, shebangs with unspecified python versions are
forbidden. Let's explicitly set the shebang to python2
=> Explicitly specify python2 in webapi/cvmfs-api.py shebang

cvmfs/s3fanout.cc
When using dns-style buckets, resolve the correct hostname with
bucket prefix.
=> s3fanout: resolve the correct $(bucket).$(hostname) DNS

cvmfs/server/cvmfs_server_add_replica.sh, cvmfs/server/cvmfs_server_snapshot.sh, cvmfs/server/cvmfs_server_util.sh, test/src/621-snapshotallgcall/main
See [CVM-1779](https://sft.its.cern.ch/jira/browse/CVM-1779).
Note that the original of the test script I modified here [fails](https://sft.its.cern.ch/jira/browse/CVM-1780) in the base cvmfs-2.6 branch.  I tested this by using the modified cvmfs_server with a regular 2.6.0 install, without the branch's cvmfs_swissknife.
=> Add -g snapshot group option to cvmfs_server add-replica and snapshots -a

cvmfs/CMakeLists.txt, cvmfs/swissknife_filestats.cc, cvmfs/swissknife_filestats.h, cvmfs/swissknife_main.cc, test/src/669-filestats/main
New swissknife subcommand 'filestats'. Traverses the catalog tree and exports useful information into sqlite db:
- catalogs table (number of entries, file size)
- objects table (hash, size)
- symlinks table (string length)
- N-to-N files-objects relation (useful for deduplication stats, N-to-N relation useful for chunked files)
=> Swissknife filestats feature

cvmfs/s3fanout.cc, cvmfs/s3fanout.h, cvmfs/upload_facility.h, cvmfs/upload_s3.cc, cvmfs/upload_s3.h, test/unittests/t_s3fanout.cc
Refactor:
- move S3 server info (hostname, port, bucket, ...) from JobInfo into S3Fanout
- construct DNS-style bucket hostname in constructor of S3Fanout 
Improvements:
- use pipes instead of jobs_todo_ and thread_upload_run_ variables to communicate jobs and termination between S3Uploader and S3Fanout
- in poll function, use timeout suggested by curl instead of default 100ms
=> S3fanout: a few improvements + refactor

python/parser.py
Additional data are now being dumped into the *.data benchmark result files. 
Parse counters from the data files only after encountering the header line.
=> Statistics collector: fix parsing of the *.data benchmark results

cvmfs/cache_extern.cc, cvmfs/cache_extern.h, cvmfs/catalog_mgr_client.cc, test/src/674-alienupdate/main
Adresses stale cvmfs clients on CSCS.  This happens when
- Clients share a writable alien cache
- Clients have network access
=> Fix detection of new root catalogs on shared alien cache

mount/domain.d/egi.eu.conf, mount/domain.d/opensciencegrid.org.conf, packaging/rpm/cvmfs-config-default.spec
Revert #2403 which thankfully had not been released in a cvmfs-config-default rpm.  The problem with the change is that frontier-squid hasn't yet added cvmfs01.nikhef.nl to its acl list of known CVMFS stratum 1s.  Once that has changed, it will take a while until all the squids that are using the acl list are updated.
=> revert change of klei.nikhef.nl to cvmfs01.nikhef.nl

cvmfs/cache.cc, cvmfs/cache.h, cvmfs/cache_extern.cc, cvmfs/cache_extern.h, cvmfs/cache_plugin/channel.cc, cvmfs/cache_posix.cc, cvmfs/cache_posix.h, cvmfs/cache_tiered.cc, cvmfs/cache_tiered.h, cvmfs/cvmfs.cc, cvmfs/fd_table.h, cvmfs/mountpoint.cc, cvmfs/mountpoint.h, cvmfs/sqlitevfs.cc, cvmfs/sqlitevfs.h, test/unittests/t_cache.cc
As discovered in the integration tests, the external cache manager can mix-up file catalog file descriptors if
- the file system client gets reloaded
- after the root file catalog got updated/remounted
This is due to the fact that during reload and restore of the previous cache manager file system table, the file descriptor for the newly attached root file catalog is lost. With this fix, the root catalog's file descriptor gets remapped into the restored file descriptor table.
=> Fix potential file descriptor mix-up of external cache manager

ci/run_unittests.sh, cvmfs/CMakeLists.txt, cvmfs/cache_plugin/cvmfs_cache_posix.cc, cvmfs/cache_posix.cc, cvmfs/cache_posix.h, cvmfs/manifest.cc, cvmfs/manifest.h
Add executable 'cvmfs_cache_posix', which acts as an external
CVMFS cache plugin and uses CVMFS PosixCacheManager.
Currently, it does NOT use QuotaPosixManager, so it does not
support object listing and cache shrinking. User can still clean
cache manually.
=>  External POSIX cache plugin

cvmfs/cache_plugin/cvmfs_cache_posix.cc
Do not use INT64_MAX constant, which is not
available on all platforms.
=> cvmfs_cache_posix: minor bugfix

cvmfs/cvmfs.cc, cvmfs/loader.cc, cvmfs/loader.h, cvmfs/mountpoint.cc, cvmfs/mountpoint.h, cvmfs/talk.cc, test_mount.sh
- Make use of batch forget (libfuse >= 29, e.g. EL7)
- Cache readdir results on the same directory handle (fuse3, kernel >= 4.20)
=> Performance improvements for modern fuse/libfuse

test/unittests/CMakeLists.txt, test/unittests/c_file_sandbox.h, test/unittests/c_http_server.cc, test/unittests/c_http_server.h, test/unittests/t_download.cc, test/unittests/t_uploaders.cc
Implement a simple HTTP server class. Then use this class to implement simple mock HTTP servers (proxy, redirect, file serving) in t_download.cc. These will be further used for writing additional tests for DownloadManager.
WIP: rewrite t_download.cc using FileSandbox and write more tests.
=> MockHTTPServer & new tests for DownloadManager

cvmfs/download.cc, cvmfs/download.h, test/unittests/t_download.cc
When a host redirects to another failing URL, DownloadManager
incorrectly does not switch to next host. This is caused by
assuming that CURLINFO_EFFECTIVE_URL variable does not change
after a redirect, when it actually does.
Rewrite the 'do_switch' condition in SwitchHost() without the
help of CURLINFO_EFFECTIVE_URL variable.
=> DownloadManager fix: switch hosts after redirect

cvmfs/server/cvmfs_server_coda.sh
This is to help comply with the new license requirement of 30 days for updates.  Also adds mention in the comment of overriding via /etc/cvmfs/server.local.  See [CVM-1833](https://sft.its.cern.ch/jira/browse/CVM-1833).
=> Reduce the minimum and maximum days for geo db updates

ducc/cmd/convert.go, ducc/cmd/loop.go, ducc/cmd/root.go, ducc/go.mod, ducc/lib/conversion.go, ducc/lib/image.go, ducc/lib/utils.go, packaging/rpm/cvmfs-universal.spec, test/src/400-ducc-ingest_images/main, test/src/401-ducc-convert_singularity/main, test/src/402-ducc-ingest-temp-dir/main
This PR add the possibility to specify a temporary directory that DUCC can use in lieu of /tmp.
There are some other minor changes as well addressing: https://sft.its.cern.ch/jira/projects/CVM/issues/CVM-1840
=> Ducc temp directory

ci/run_cpplint.sh
cpplint.py outputs its result to stderr.
To save the results to a file, stderr needs to be
captured (stdout is blank in this case).
=> ci/run_cpplint.py: trivial bugfix

cvmfs/webapi/test_cvmfs_geo.py, test/unittests/t_mountpoint.cc
- 32-bit images on 64-bit hosts: T_MountPoint: explicit RAM cache size
- SLES11, SLES12: geoapi unittests: IPv4 fallback on old systems
=> Fix unittests on newly tested platforms

ducc/cmd/garbage_collection.go, ducc/docker-api/util.go, ducc/lib/garbage_collection.go
A rewrite of the GC in DUCC.
The new version is a little less smart than the old one, however it is much simpler and more complete in functionality.
It scans the whole tree and delete the layers and paths that are not in use anymore.
An upgrade to this would be to provide a grace period before to eliminate the files.
A possible implementation of this grace period would be to touch a `.last_used` file in the metadata folders of the layers and of the images once a day.
Eventually we would delete only the layers/images whose `.last_used` file is older than the grace period.
=> Ducc gc better version

ci/common.sh
We require at least go 1.12 for `strings.ReplaceAll`.
This, along with https://github.com/cernvm/ci-scripts/commit/30ddff2c97628938c647dcb3d06fb86897d9694e should fix our compilation problems at least on fedora.
=> upgrade minum required golang to 1.12

cvmfs/catalog_mgr.h, cvmfs/catalog_mgr_impl.h, cvmfs/catalog_mgr_rw.cc, cvmfs/catalog_mgr_rw.h, cvmfs/xattr.h, test/common/catalog_test_tools.cc, test/common/catalog_test_tools.h, test/common/testutil.cc, test/common/testutil.h, test/unittests/CMakeLists.txt, test/unittests/t_catalog_merge_tool.cc, test/unittests/t_catalog_mgr_rw.cc, test/unittests/t_dns.cc, test/unittests/t_libcvmfs.cc
Adds a `CloneTree()` method to the catalog manager that can copy an entire subtree to a new location. This is a meta-data only operation.  A first test with cloning /cvmfs/cms.cern.ch/slc7_ppc64le_gcc530 results in at least 50k file system entries per second.
Cloning is supposed to provide the core functionality for "fast flattening" of container images. Given that the chain directory for layers 1..n-1 already exists, one can create the chain for layers 1..n by cloning the chain[1..n-1] and then publishing only the last delta layer. See CVM-1801
=> Add feature to clone directory subtrees

packaging/rpm/cvmfs-universal.spec
/usr/sbin/hardlink -> /usr/bin/hardlink in cvmfs-universal.spec
=> Packaging: fix broken path for Fedora 31

cvmfs/session_context.cc
Instead of comparing the reply JSON to a hardcoded value,
decode the reply and look for the "status" field value.
=> BUGFIX: GW SessionContext: more flexible GW reply JSON evaluation

cvmfs/statistics_database.cc, cvmfs/statistics_database.h
Delete old records to keep the statistics DB small.
Maximum age of records to keep can be configured by
CVMFS_STATS_DB_DAYS_TO_KEEP and is 365 by default.
=> Statistics DB: prune old records

test/common/mock_services/http_400.py, test/common/mock_services/http_server.py, test/common/mock_services/make_repo.py, test/common/mock_services/silent_socket.py, test/migration_tests/001-hotpatch/tarsum, test/src/030-missingrootcatalog/main, test/src/065-http-400/main, test/src/081-shrinkwrap/main, test/src/628-pythonwrappedcvmfsserver/main, test/src/639-specialfiles/main, test/src/647-bearercvmfs/cvmfs-scitokens-helper.py, test/src/647-bearercvmfs/cvmfs_scitoken_helper.py, test/test_functions
Fix shebangs in all related files.
Make a switch between python/python2 for tests
running on macOS, too.
=> Explicit python2 in integration tests

cvmfs/util/exception.h
it use to print the literal __FILE__ and __LINE__ instead of the
actual file and line of the panic.
Double macro from: https://stackoverflow.com/questions/19343205/c-concatenating-file-and-line-macros
Found this while working on the GC
=> fix panic macro

packaging/rpm/cvmfs-universal.spec
Fixes: 
- different path for `hardlink` command on Fedora 31
- renamed `python` to `python2` command on Fedora31
=> 2.7: RPM spec file fixup for Fedora31

cvmfs/receiver/commit_processor.cc, cvmfs/signing_tool.cc, cvmfs/signing_tool.h, test/src/800-repository_gateway/main, test/test_functions
New (intermediary) root catalog should also be added to reflog,
so the catalog tree can be garbage collected as well.
=> CommitProcessor: add intermediary root catalog to reflog

cvmfs/cvmfs_talk.cc, cvmfs/mountpoint.h, cvmfs/talk.cc, cvmfs/talk.h, cvmfs/util/algorithm.cc, cvmfs/util/algorithm.h, test/unittests/t_util.cc
Quantiles are useful for performance and regression tests on the
client side.
This was suppose to be one of the first tasks of the summer student. Nevertheless I believe it is important to keep this development line open as well.
It would be interesting to have a command to spit out just this numbers so that we can compare the performance on the client programmatically from different installation and user bases.
At the moment the output produced is somehow like this:
```
Readdir                                                                                                                                  
nsec |   count |           distribution |                                                                            
0 ->          1 :       0 |                        | …
```
=> Add quantiles computation to Log2Histogram

ducc/cmd/convert.go, ducc/cmd/loop.go, ducc/lib/conversion.go, ducc/lib/cvmfs.go, ducc/lib/image.go, ducc/lib/recipe.go, ducc/lib/wish.go
Checking if an image is already in DUCC / unpacked is an IO bound task.
We need to fetch the manifest from the registry.
Before this PR the fetch of manifest was done sequentially, in a synchronous way.
Now we pre-fetch the manifest asynchronously.
We replace a standard vector with a go channel and we use goroutines to actually get the manifests.
Improvements in time are significant, from ~5min to ~20second.
=> Make fast check for images

ducc/lib/conversion.go, ducc/lib/image.go, ducc/lib/wish.go
A channel can be read from only once, so while we try to read
from the same channel twice (once for the layer conversion and
another time for the flat conversion) the second read will be
empty.
Different solutions might work but I find simpler to just use
two different channels.
=> use different channels for layers and flat conversion

cvmfs/server/generate_stats_plots.C
`start_time` and `finish_time` fields in statistics database are precise to one second. If the operation takes less than one second, the duration (`finish_time` - `start_time`) would be 0. If this happens, add 0.5 second so we do not divide by 0.
=> BUGFIX: div by 0 in generate_stats_plots.C ROOT macro

cvmfs/server/cvmfs_server_common.sh
Fix variable name bug that caused .cvmfs_status.json updates to not preserve old entries.  [CVM-1887](https://sft.its.cern.ch/jira/browse/CVM-1887).
=> Fix reading of an item from a repository

cvmfs/json_document.cc, cvmfs/json_document.h, cvmfs/json_document_write.h, cvmfs/receiver/reactor.cc, cvmfs/receiver/reactor.h, cvmfs/session_context.cc, cvmfs/statistics.cc, test/unittests/t_json.cc, test/unittests/t_reactor.cc, test/unittests/t_statistics.cc
The gateway tests showed a small mistake on the statistics manager. It didn't handle correctly the case of no statistics while generating the JSON.
The JSON was generated by hand, but we do have an interface to generate valid JSON, hence I decided to let the statistics use the already present interface.
In doing so, however I would have introduced some dependencies (`util/pointer.cc` and `json_document.cc`) to  all the code that use the statistic class.
So I refactor our own JSON generation in a separate, header only, file.
I transition from a struct + function to a simple class, and rename in what I believe is more appropriate.
Also I modified the interface in something more ergonomic.
In modifying the interface, however, I broke the `receiver/reactor.h` interface. It was relying on raw …
=> Fix generation of JSON snippets

cmake/Modules/cvmfs_compiler.cmake
The version check wouldn't pass with GCC 10 because the `.*` necessary when using `gcc -v` eats the 1. By using `-dumpfullversion`, the `.*`s can be avoided.
=> Enable GCC 10 to pass version check

cvmfs/server/cvmfs_server_add_replica.sh, cvmfs/server/cvmfs_server_apache.sh, cvmfs/server/cvmfs_server_gc.sh, cvmfs/server/cvmfs_server_json.sh, cvmfs/server/cvmfs_server_snapshot.sh, cvmfs/server/cvmfs_server_util.sh, test/src/621-snapshotallgcall/main, test/test_functions
The new `cvmfs_server replica -P` command to create a proxy passed replica.  Such a replica will be marked by `CVMFS_PASSTHROUGH=true` in the replica.conf file and by the `pass-through` boolean flag in the repositories.json
=> Add option to create pass-through replicas

test/cloud_testing/platforms/centos8_x86_64-CONTAINER_setup.sh, test/cloud_testing/platforms/centos8_x86_64-CONTAINER_test.sh, test/cloud_testing/platforms/common.sh, test/container/001-unpacked/main, test/container/002-singularity/main, test/container/004-runc/main, test/container/005-csi/Dockerfile, test/container/005-csi/csi-cvmfsplugin-attacher.yaml, test/container/005-csi/csi-cvmfsplugin.yaml, test/container/005-csi/csi-provisioner-rbac.yaml, test/container/005-csi/logs.sh, test/container/005-csi/main, test/container/container_common.sh, test/test_functions
Adds a new EL8 based platform to test various container runtime integration scenarios with a new suite of tests.  This should serve both as a regular integration test suite and as a documentation on how to use cvmfs with containers.
=> Create container integration tests
