cvmfs/cvmfs

- ci/installrpm.sh
- mount/domain.d/opensciencegrid.org.conf
- packaging/debian/config-egi/Makefile
- packaging/debian/config-egi/control
- packaging/rpm/cvmfs-config-egi.spec
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
- test/cloud_testing/platforms/common_setup.sh
- test/cloud_testing/platforms/slc5_i386_setup.sh
- test/cloud_testing/platforms/slc5_x86_64_setup.sh
- test/cloud_testing/platforms/slc6_i386_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-NFS_setup.sh
- test/cloud_testing/platforms/slc6_x86_64_setup.sh
- test/cloud_testing/platforms/ubuntu_x86_64_setup.sh
- test/cloud_testing/steering/remote_setup.sh
In particular: added opensciencegrid configuration to cvmfs-config-egi and allow for multiple config packages in the cloud testing scripts.
> Fix: various fixes for the config packages

- cvmfs/cvmfs_config
- cvmfs/platform_linux.h
- cvmfs/quota.cc
- packaging/debian/cvmfs/control
- packaging/rpm/cvmfs-universal.spec
Fixes the following problems:
- `cvmfs_config setup` ensures that autofs is running
- Rebuilding the cache database on XFS
- Spurious syslog error about ptrace() permissions
> Fix several problems on CentOS 7

- cvmfs/s3fanout.cc
- cvmfs/s3fanout.h
- cvmfs/upload_s3.cc
Fixes to coverity found defects in S3 code.
> Fix s3 coverity bug fixes

- test/unittests/t_local_uploader.cc
Another nasty GCC 4.8 compiler warning...
> FIX: Compiler Warning C++11 ill-formed

- cvmfs/s3fanout.h
One more missing variable initialisation.
> Fix (CID 59459): initialise one more variable in constructor

- test/src/017-dnstimeout/main
> FIX: Syntax Error in Integration Test 017

- test/src/581-snapshotgarbagecollectedrepo/main
This tests a `cvmfs_server snapshot` after the associated stratum 0 was garbage collected.
> TEST: Snapshot Stratum 1 from GC'ed Stratum 0

- test/cloud_testing/steering/remote_run.sh
- test/cloud_testing/steering/run.sh
- test/migration_tests/001-hotpatch/main
- test/migration_tests/common.sh
This integrates the upgrade from `cvmfs-keys` to `cvmfs-config-...` into the hot-patch migration test. Testing this will be a bit of a pain, but this is the first attempt... keeping my fingers crossed.
> FIX: First Attempt to Fix the Migration Test

- test/migration_tests/001-hotpatch/main
Fixing what has been found wrong with the first run. (Merging myself...)
> Fix: Migration Test Adaptions

- test/cloud_testing/steering/remote_run.sh
- test/cloud_testing/steering/remote_setup.sh
- test/cloud_testing/steering/run.sh
- test/migration_tests/001-hotpatch/main
Lets keep our fingers crossed...
> Fix: Migration Test

- test/cloud_testing/steering/run.sh
Shell scripts.... I will never learn to love them! NEVER!
> FIX: Shell Variable Quotation in Migration Test

- cvmfs/cvmfs.cc
- cvmfs/download.cc
- cvmfs/download.h
- test/src/583-httpredirects/main
This pull request add support for http redirects, including a regression test.   More background is in https://github.com/cvmfs/cvmfs/pull/537 and https://sft.its.cern.ch/jira/browse/CVM-766.
> Add support for http redirects

- test/unittests/t_garbage_collector.cc
Unfortunately I broke one garbage collection unit test while [changing](https://github.com/cvmfs/cvmfs/pull/733) the `CatalogTraversal<>` yesterday. Should have seen that before, as it was the only thing that went wrong on ubuntu during the cloud test run last night.
> FIX: Adapt GC Unit Test for Unreachable Nested Catalog

- test/cloud_testing/platforms/slc5_x86_64_test.sh
- test/cloud_testing/platforms/slc6_i386_test.sh
- test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_test.sh
- test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_test.sh
- test/cloud_testing/platforms/slc6_x86_64-NFS_test.sh
- test/cloud_testing/platforms/slc6_x86_64_test.sh
> FIX: Restore SELinux Context after Mounting /var/lib/cvmfs

- cvmfs/cvmfs.cc
> Add host_list to the list of extended attributes

- test/cloud_testing/platforms/slc6_x86_64-EXCLCACHE_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-INFOHEADER_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-NFS_setup.sh
- test/run.sh
- test/src/048-exportfqrn/main
- test/src/049-cdconf/main
Among other things: re-enable special cvmfs client flavor tests.
> FIX: several improvements to test cases

- test/test_functions
Follow-up: Sorry... clicked a bit too fast...
> FIX: Use sudo to Actually Copy Everything

- AUTHORS
Added Jose Molina Colmenero to the Author's file
> Adding myself to the AUTHOR list

- ci/multiplatform_build.sh
> FIX: Make Build Script Abort on Failure

- externals/pacparser/src/makeHook.sh
Might not be enough... still debugging.
> Fix: Build of libpacparser on Mac OS X

- externals/pacparser/src/makeHook.sh
> Add printf-debugging Print Outs for Pacparser Building

- ci/README
- ci/README.md
> Doc: Description of CI Build Scripts

- cloc-1.62.pl
The version of cloc in the repository produced 'deprecated' warnings. Updated to latest release...
> Update cloc: 1.56 -> 1.62

- packaging/rpm/cernvm.repo
- packaging/rpm/cvmfs-release.spec
- Remove dist tag
- Remove cernvm-ng, add cernvm-config
> Fix release rpm

- ci/build_cvmfs_deb.sh
- ci/build_cvmfs_pkg.sh
- ci/build_cvmfs_rpm.sh
- ci/common.sh
This resurrects the creation `pkgmap` in the new build scripts used in Jenkins.
> CI: Create pkgmap for Individual Platforms

- test/unittests/t_catalog_traversal.cc
> FIX: fixed a small mistake in t_catalog_traversal.cc

- test/src/587-serverhooks/main
This makes sure that the server hooks in `/etc/cvmfs/cvmfs_server_hooks.sh` are properly executed. We might actually need them to work around [CVM-818](https://sft.its.cern.ch/jira/browse/CVM-818) so they'd better work properly.
> TEST: Server Hooks

- test/cloud_testing/platforms/slc6_x86_64_setup.sh
> FIX: Missing Sudo

- cvmfs/CMakeLists.txt
- cvmfs/sqlitevfs.cc
- cvmfs/statistics.cc
- cvmfs/statistics.h
- cvmfs/talk.cc
Changes:
1) statistics.h (removing the TryInc function) (removing the statistics counter repetition) statistics.cc sqlite-classes
2) remove the counter repetition. There was an assert when trying to register twice a counter with the same name
3) CMakeLists.txt (all of them)
4) talk.cc as-is (changing the ShortString class)
> First Statistics set of changes

- ci/build_cvmfs_release_rpm.sh
> Add Build Script for cvmfs-release.rpm

- cvmfs/download.h
Just a small typo in two counters
> FIX: counter names in download.h

- CMakeLists.txt
- ChangeLog
- bump_version.sh
- packaging/mac/cvmfs.pmdoc.template/01cvmfs-contents.xml
- packaging/rpm/cvmfs-universal.spec
Updates to MAJOR.MINOR.PATCH versioning.  Heads-up: there might be hickups in the ci-scripts
> bump version to 2.2.0, adjust bump_version script

- cvmfs/file_processing/file_processor.h
- cvmfs/swissknife_history.h
This fixes the issue described in [CVM-840](https://sft.its.cern.ch/jira/browse/CVM-840).
> FIX: Forward Declaration of Class and Struct

- cvmfs/smalloc.h
Jenkins found its first actual cpplint quirk. Olé.
> FIX: cpplint cosmetics

- test/unittests/t_fs_traversal.cc
- test/unittests/t_util.cc
After this small fix it works in my mac
> FIX: T_FsTraversal.BlockDevice now compiles on Mac OX

- cvmfs/cvmfs_suid_helper.cc
- cvmfs/loader.cc
- cvmfs/sanitizer.cc
- cvmfs/sanitizer.h
- test/unittests/t_sanitizer.cc
Added a test for `IntegerSanitizer` and fixed its implementation to allow for negative numbers.
> TEST: IntegerSanitizer

- cvmfs/catalog_sql.cc
- cvmfs/file_processing/chunk.cc
- cvmfs/file_processing/file_processor.cc
- cvmfs/swissknife_pull.cc
- test/unittests/t_uid_map.cc
> FIX: CppLint complaints

- test/unittests/t_fs_traversal.cc
> FIX: use platform_lstat in T_FsTraversal

- python/cvmfs/test/file_sandbox.py
Amend for the [previous pull request](https://github.com/cvmfs/cvmfs/pull/943).
> FIX: add missing file 'file_sandbox.py'

- ci/common.sh
- ci/run_python_unittests.sh
- ci/run_unittests.sh
- python/cvmfs/test/__main__.py
This prepares a minor refactoring of the unit test running logic in Jenkins. Furthermore it adds a script to conveniently run the python library unit tests through the CI and retrieve XML test reports.
> CI: Python Unittests

- ci/run_python_unittests.sh
> FIX: Check for dateutil and requests

- python/cvmfs/_common.py
- python/cvmfs/repository.py
- python/cvmfs/test/whitelist_test.py
- python/cvmfs/whitelist.py
This puts the pieces of the recent python related pull requests together and allows to verify a repository's authenticity using a public key. In code this looks like the following:
```python
import cvmfs
repo = cvmfs.open_repository("http://cvmfs-stratum-zero.cern.ch/cvmfs/atlas.cern.ch",
"/etc/cvmfs/keys/cern.ch/cern.ch.pub")
repo = cvmfs.open_repository("http://cvmfs-stratum-zero.cern.ch/cvmfs/atlas.cern.ch")
repo.verify("/etc/cvmfs/keys/cern.ch/cern.ch.pub")
```
> Python: Check Repository Authenticity

- ci/build_python-cvmfsutils_rpm.sh
- python/ChangeLog
- python/README
- python/buildrpm.sh
- python/setup.py
This does some cleanup work, updates the README and ChangeLog files and adds an RPM build script for Jenkins.
> Python: Build RPM package

- test/unittests/t_catalog.cc
It fixes a recent error in t_catalog.cc related to file metadata creation
> FIX: t_catalog error with file owners

- test/run.sh
> TEST: Use bash for Integration Testing

- test/src/002-probe/main
Memo to myself: Don't ever do `git commit -am`!
> FIX: Revert Inadvertently Added Debug Code

- ci/docker/el5_x86_64/Dockerfile
- ci/docker/el6_x86_64/Dockerfile
- ci/docker/el7_x86_64/Dockerfile
That actually works a lot more smoothly than I dreamt. Will require some changes in our build procedures, but I think its totally worth it, since it should put virtually everything of the process under version control and into brain-dead automation.
> CI: Add Dockerfiles for EL5, 6, 7

- ci/build_on_docker.sh
- ci/docker/el4/Dockerfile
Fixes a problem with running docker containers without a TTY and adds some more details for EL4.
> CI: Docker Enhancements

- ci/build_on_docker.sh
Follow up for [#1085](https://github.com/cvmfs/cvmfs/pull/1085/files).
> FIX: Run Docker Containers as non-interactive

- ci/docker/common.sh
> FIX: remove gpg key check (doesn't work with non-root)

- ci/docker/opensuse13_x86_64/Dockerfile
- ci/docker/opensuse13_x86_64/build.sh
- ci/docker/opensuse13_x86_64/build_internal.sh
This adds a recipe for bootstrapping an OpenSUSE 13.2 build container.
> CI: Add Build Container for OpenSUSE 13.2

- python/statistics_collector.py
Fixed a small error introduced in https://github.com/cvmfs/cvmfs/pull/1108
> FIX: statistics_collector retrieves now the average of the counter

- ci/docker/ubuntu1404_i386/Dockerfile
- ci/docker/ubuntu1404_i386/build.sh
- ci/docker/ubuntu1404_x86_64/build.sh
- ci/docker/ubuntu_common/build.sh
This refactors the already added 64bit version to reuse most of the bootstrapping code and adds a 32bit ubuntu flavour.
> CI: Ubuntu 14.04 32bit Docker Recipe

- ci/docker/common.sh
- ci/docker/rhel_common/build.sh
In fact it was not only re-enable but also a minor fix. -.-
> FIX: Re-enable GPG Check for RHEL based Docker Images

- vagrant/provision_fedora.sh
> Vagrant: add mod_wsgi and lsof to fedora vagrant box

- Vagrantfile
- vagrant/provision_ubuntu.sh
Missing bits:
* starting Apache
* automatically starting Apache on reboot
* installing and setting up OverlayFS or AUFS
> Vagrant: Add Rudimentary Ubuntu Provisioning Script

- test/src/501-changerepo/main
- test/src/560-garbagecollectpreservehistory/main
- test/src/595-geoipdbupdate/main
- test/test_functions
- test/wiremock_wrapper.sh
This fixes several minor things to make the integration test set compatible to both OverlayFS and Fedora 22.
> FIX: Integration Tests for OverlayFS and Fedora

- vagrant/provision_ubuntu.sh
> FIX: Add libcap-dev for Vagrant Ubuntu Provisioning

- test/run.sh
This enables run.sh to execute tests through Parrot. It doesn't mean all tests can now be executed with Parrot, but that they "could" if they don't use fuse (or sudo, in any case).
An idea to identify the tests that can run with parrot would be to manually include a variable, say CVMFS_PARROT_ALLOWED=true, in those tests that can actually run it, and set it to false by default.
Note: when running with Parrot the variable PARROT_ENABLED is set to TRUE
> Allow Parrot execution of integration tests

- packaging/debian/cvmfs/control
- packaging/rpm/cvmfs-universal.spec
> FIX: Package Dependencies for libcap

- ci/build_on_docker.sh
Up to now, docker images on a build machine would not have been automatically been rebuilt if a docker recipe in the repository had changed.
> CI: Auto Rebuild Docker Image on Updated Recipe

- cvmfs/cvmfs_server
Forgot to set a `$`... minimal thing, merging myself...
> FIX: OverlayFS post-v22 detection

- test/src/598-partialpreload/main
- test/test_functions
Just minor fixes and refactorings for some (admittedly undocumented) consistency conventions.
> FIX: Test Preload for Fedora 22

- cvmfs/catalog_sql.cc
It's surprisingly fun to dig down in your code base's history and see how it looked like three years ago.... O.O
> FIX: Add Catalog Schema ChangeLog

- ChangeLog
Actually this has a Jira-ticket... Just for reference...
> FIX: Changelog

- test/src/500-mkrepo/main
Somewhat I missed that test case when going through all recently. Oddly enough it's the first one. :-)
> FIX: Integration Test 500 on OverlayFS

- test/cloud_testing/platforms/common.sh
- test/cloud_testing/platforms/fedora22_x86_64_setup.sh
- test/cloud_testing/platforms/fedora22_x86_64_test.sh
This is a first shot. Lets see if it works. :o)
> Test: Cloud Test Platform for  Fedora 22

- add-ons/README
> FIX: Typos

- externals/python-geoip/src/makeHook.sh
Minimal change with large effect, hopefully. :-)
> FIX: look for GeoIP.*.so on ArchLinux

- externals/python-geoip/src/makeHook.sh
Understood the control flow wrongly... meh.
> FIX: remove misplaced else-branch

- cvmfs/cvmfs_server
**Note:** This pull request will be amended with more messages. Opening it early to allow for discussion.
This adds several syslog messages for common CernVM-FS server actions as requested in [CVM-812](https://sft.its.cern.ch/jira/browse/CVM-812) and [CVM-861](https://sft.its.cern.ch/jira/browse/CVM-861).
> Feature: CernVM-FS Server logs Events to Syslog

- test/unittests/t_shash.cc
- test/unittests/t_uploaders.cc
**Note:** Work in progress... doesn't work for S3 yet.
This is a follow up for the prematurely merged #1291. Adding some unit tests.
> TEST: Some Unit Tests as a Follow-up

- cvmfs/webapi/cvmfs_geo.py
- test/src/614-geoservice/main
As documented in https://sft.its.cern.ch/jira/browse/CVM-722
> Change geoapi to use passed-in proxy name as priority source address

- cvmfs/voms_authz/cred_fetcher.cc
- cvmfs/voms_authz/voms_authz.cc
- cvmfs/voms_authz/voms_cred.cc
Fix some issues that popped up when building branch on RHEL7.
> Fix compiler issues.

- cvmfs/CMakeLists.txt
- cvmfs/catalog_balancer.h
- cvmfs/catalog_balancer_impl.h
- cvmfs/catalog_mgr.h
- cvmfs/catalog_mgr_client.cc
- cvmfs/catalog_mgr_client.h
- cvmfs/catalog_mgr_impl.h
- cvmfs/catalog_mgr_ro.cc
- cvmfs/catalog_mgr_ro.h
- cvmfs/catalog_mgr_rw.cc
- cvmfs/clientctx.h
- cvmfs/cvmfs.cc
- cvmfs/cvmfs_server
- cvmfs/libcvmfs_int.cc
- cvmfs/swissknife_sync.cc
- test/unittests/t_catalog_mgr.cc
- test/unittests/testutil.cc
- test/unittests/testutil.h
Switch CVM-904 to new TLS-based client context.
> Rewrite client context usage

- cvmfs/CMakeLists.txt
- cvmfs/logging.cc
- cvmfs/logging_internal.h
- cvmfs/voms_authz/cred_fetcher.cc
- cvmfs/voms_authz/voms_authz.cc
- cvmfs/voms_authz/voms_authz.h
- cvmfs/voms_authz/voms_cred.cc
- cvmfs/voms_authz/voms_cred.h
- cvmfs/voms_authz/voms_curl.cc
- test/unittests/CMakeLists.txt
- test/unittests/t_voms.cc
This is the core of the VOMS work; added to the build but not integrated into the FUSE process.
Does the following:
- Fetch and cache credentials from the user process
- Enable curl handles to use cached credentials.
- Implements callouts to libvomsapi to parse credentials.
- Implements authz logic (given an authorization, checks to see if the current credential is acceptable).
> Infrastructure to fetch credentials and check VOMS credentials.

- cvmfs/cvmfs.cc
- cvmfs/libcvmfs_int.cc
- cvmfs/options.h
- cvmfs/signature.cc
- cvmfs/signature.h
- test/src/047-blacklist/main
- test/src/616-blacklistconfigrepo/main
- test/test_functions
If a config repository is configured, appends the blacklist from there to the local blacklist.
> Read blacklist from config repository (CVM-901)

- cvmfs/cvmfs_server
- cvmfs/hash.h
- cvmfs/manifest.cc
- cvmfs/manifest.h
- cvmfs/swissknife_info.cc
- cvmfs/swissknife_pull.cc
- cvmfs/swissknife_sign.cc
- cvmfs/swissknife_sign.h
- cvmfs/upload.cc
- cvmfs/upload.h
- test/src/609-metainfofile/main
- test/src/618-repometainfo/main
Contains also some re-arrangements for the JSON editing in `cvmfs_server`.  Integration test is a bit hacky due to forced interactivity of JSON edits.
> Add editable repository meta info (CVM-804)

- cvmfs/compression.cc
- cvmfs/compression.h
- cvmfs/swissknife_graft.cc
- cvmfs/swissknife_graft.h
- test/src/606-graft/main
This adds `cvmfs_swissknife graft` CLI support for calculation of graft files of uncompressed files.
> CVM-964: Uncompressed graft support for swissknife graft command

- cvmfs/download.cc
- cvmfs/download.h
- test/unittests/t_download.cc
@reneme: that should give you the necessary information for the GC fix.
> Parse http return code to numeric variable

- cvmfs/cvmfs_server
- test/src/621-snapshotall/main
- test/test_functions
Refer to pr #1315 and [CVM-813](https://sft.its.cern.ch/jira/browse/CVM-813)
> Add cvmfs_server snapshot -a option

- test/src/054-geoapi/main
@bbockelm note that I included unl.edu.  Will you now add tests for external urls?
> support running 054-geoapi test at fnal.gov or unl.edu

- cvmfs/sync_mediator.cc
- test/unittests/t_util.cc
- test/unittests/testutil.h
> FIX: Several Compile Errors/Warnings

- packaging/rpm/cvmfs-universal.spec
> FIX: Fedora 23 RPM Dependency

- test/cloud_testing/platforms/fedora22_x86_64_setup.sh
- test/cloud_testing/platforms/fedora22_x86_64_test.sh
- test/cloud_testing/platforms/fedora23_x86_64_setup.sh
- test/cloud_testing/platforms/fedora23_x86_64_test.sh
This is kind of a first shot in added Fedora as test platforms for the cloud testing. We'll need to iterate with those soon...
> Test: Add Fedora 23 to test platform + fix Fedora 22

- ci/build_cvmfs_sourcetarball.sh
> FIX: Follow Up for Tarball Build

- cvmfs/cvmfs_server
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
Repairs for CentOS 7 test setup and minor UX fixes.
> FIX: Test Infrastructure and UX

- Vagrantfile
- vagrant/provision_fedora.sh
> Vagrant: Switch to Fedora23 dev box

- vagrant/provision_fedora.sh
> Vagrant: add `vim` to Fedora machine

- cvmfs/tracer.cc
According to the man pages, `pthread_cond_signal` and `pthread_cond_broadcast` work the same no matter if the associated mutex is being held or not.  According to Helgrind and empirical observation on ARM64, it very much does matter.
> FIX: deadlock on arm64

- cvmfs/cvmfs.cc
Lingered around since a while: on unmount, the catalog manager is removed while the unpin listener from the quota manager might still use it.  This can run into a deadlock although only in rare cases.
> FIX: deadlock on unmount

- ci/docker/ubuntu1204_i386/Dockerfile
- ci/docker/ubuntu1204_i386/build.sh
- ci/docker/ubuntu1204_x86_64/Dockerfile
- ci/docker/ubuntu1204_x86_64/build.sh
- ci/run_on_docker.sh
This adds Ubuntu 12.04 as a docker build platform.
> CI: Ubuntu 12.04 Build Platform

- cvmfs/cvmfs_server
- test/cloud_testing/platforms/common_test.sh
- test/common/migration_tests/common.sh
- test/migration_tests/001-hotpatch/main
- test/src/065-http-400/main
- test/src/595-geoipdbupdate/main
- test/test_functions
Download GeoIP database from a copy located at CERN, as download directly from MaxMind failed transiently. Fix: Several minor things for the hotpatching test.
> FIX: Tonight's Integration Tests

- cvmfs/voms_authz/voms_authz.cc
- test/src/600-securecvmfs/main
- test/src/620-pullmixedrepo/main
+ some logging behaviour tweaks
> FIX: DRY-up integration test 600 "secure cvmfs"

- .travis.yml
- ci/run_travis.sh
- cvmfs/cvmfs.cc
This PR:
- Hides the complexity of .travis.yml by calling a custom script that passes the cpplint, builds and (if on linux) runs the unit tests.
- Fixes a small error that makes cpplint fail so that when this PR is approved it directly successes.
An example of the results can be found here: https://travis-ci.org/Moliholy/cvmfs/jobs/105384291
> Travis integration

- .travis.yml
- ci/run_travis.sh
This PR:
- Collects the output of cmake and make in a single command
- Turns off email notifications
> Travis integration: email notifications

- cvmfs/cvmfs_server
This removes some code paths to support pre-upstream OverlayFS versions.
> Remove (theoretical) non-upstream OverlayFS support

- ci/run_travis.sh
Small fix when displaying the results
> FIX: run_travis.sh

- cvmfs/cvmfs.cc
- cvmfs/fetch.h
- cvmfs/file_processing/chunk.cc
- cvmfs/libcvmfs_int.cc
- cvmfs/s3fanout.cc
- cvmfs/swissknife_graft.cc
- cvmfs/voms_authz/cred_fetcher.cc
- cvmfs/voms_authz/voms_authz.cc
- cvmfs/voms_authz/voms_cred.cc
- cvmfs/voms_authz/voms_curl.cc
- test/unittests/t_buffer.cc
- test/unittests/t_compressor.cc
- test/unittests/t_file_chunk.cc
- test/unittests/t_fs_traversal.cc
- test/unittests/t_uploaders.cc
- test/unittests/t_voms.cc
Just showing the progress so far fixing the coverity issues. There are a few that belong to voms, but perhaps you wouldn't be interested in them. I'll remove these fixes if necessary
> Coverity extra fixes

- cvmfs/upload.h
> TODO: Spooler Refactoring Suggestion

- ci/run_travis.sh
Fixes an error when running on travis, which concretely complains on mac machines because there is no output after ten minutes. This way there will be output every 30 seconds
> FIX: lack of output on travis

- cvmfs/catalog_mgr_impl.h
- cvmfs/clientctx.h
- cvmfs/cvmfs.cc
- cvmfs/file_chunk.h
- cvmfs/swissknife_gc.cc
- cvmfs/swissknife_info.cc
- cvmfs/swissknife_migrate.h
- cvmfs/swissknife_pull.cc
- cvmfs/swissknife_sync.cc
- test/unittests/t_compressor.cc
- test/unittests/t_util.cc
Deals with several coverity alerts. Most of them are leaked FDs and/or memory in error cases. Nothing particularly severe.
> FIX: Coverity Issues

- cvmfs/options.cc
- test/src/050-configrepo/main
More info in [CVM-992](https://sft.its.cern.ch/jira/browse/CVM-992)
> Add default.conf in config repo

- cvmfs/cvmfs_server
- test/src/621-snapshotall/main
Details in [CVM-997](https://sft.its.cern.ch/jira/browse/CVM-997)
> fix cvmfs_server snapshot -a not noticing failed snapshots

- cvmfs/CMakeLists.txt
- test/unittests/CMakeLists.txt
That should reduce the number of merge conflicts when new source code files are added.
> Sort sources lists in CMakeList files alphabetically

- cvmfs/swissknife_reflog.cc
Fixes an issue that prevents older compilers from successfully compiling.
> FIX: Compile on Older Compilers

- cvmfs/cvmfs_rsync
- test/src/604-cvmfsrsync/main
Details are in [CVM-1004](https://sft.its.cern.ch/jira/browse/CVM-1004).
Please merge this also for cvmfs-server-2.2.2.
> Update cvmfs_rsync to handle source dirs changed into symlinks

- test/src/050-configrepo/main
pair programming... you know what happened...
> FIX: Wrong Assumptions in Test Case 050

- cvmfs/cvmfs_server
Shell script's global state is just horrible!
> FIX: health_check() Parameter Parsing

- cvmfs/reflog.h
Adding a few words of documentation to the `Reflog` implementation.
> Doc: Add Reflog Description

- ci/run_cpplint.sh
- cvmfs/download.cc
- cvmfs/sqlitemem.cc
- cvmfs/sqlitemem.h
- packaging/rpm/cvmfs-universal.spec
- test/cloud_testing/platforms/ubuntu1604_x86_64_test.sh
- test/unittests/t_sqlitemem.cc
Also: addition of Ubuntu 16.10 as a test platform
> Several fixes discovered during incremental builds

- cvmfs/compat.cc
- cvmfs/compat.h
- cvmfs/cvmfs.cc
- cvmfs/file_chunk.cc
- cvmfs/file_chunk.h
- cvmfs/loader.h
- test/src/633-changedfiles/main
Details in the [JIRA ticket](https://sft.its.cern.ch/jira/browse/CVM-1017).
> Fix stale chunked files (CVM-1017)

- ChangeLog
- cvmfs/cvmfs_server
- cvmfs/doc/README-spooler
- cvmfs/object_fetcher.h
- cvmfs/reflog.cc
- cvmfs/reflog.h
- cvmfs/swissknife.h
- cvmfs/swissknife_check.cc
- cvmfs/swissknife_check.h
- cvmfs/swissknife_gc.cc
- cvmfs/swissknife_impl.h
- cvmfs/swissknife_pull.cc
- cvmfs/swissknife_pull.h
- cvmfs/swissknife_reflog.cc
- cvmfs/swissknife_sign.cc
- cvmfs/swissknife_sign.h
- cvmfs/swissknife_sync.cc
- cvmfs/swissknife_sync.h
- test/src/528-recreatespoolarea/main
- test/src/634-reflogchecksum/main
- test/unittests/t_object_fetcher.cc
- test/unittests/t_reflog.cc
- test/unittests/testutil.cc
- test/unittests/testutil.h
Maintain /var/spool/cvmfs/$repo_name/reflog.chksum on stratum 0 and stratum 1 servers in order to verify data integrity of the reflog.
> Add local reflog checksum (CVM-1006)

- cvmfs/cvmfs_server
Please apply to both devel and cvmfs-2.3 branch.
> fix problems with migration to 2.3.0-1

- cvmfs/cvmfs_server
- test/src/557-basicgarbagecollect/main
- test/src/558-garbagecollectnestedcatalogs/main
- test/src/559-garbagecollectnamedtags/main
- test/src/560-garbagecollectpreservehistory/main
- test/src/561-garbagecollectmultihash/main
- test/src/573-garbagecollecttimestamp/main
- test/src/575-disablegarbagecollection/main
- test/src/576-garbagecollectstratum1/main
- test/src/577-garbagecollecthiddenstratum1revision/main
- test/src/578-automaticgarbagecollection/main
- test/src/579-garbagecollectstratum1legacytag/main
- test/src/580-automaticgarbagecollectionstratum1/main
- test/src/581-snapshotgarbagecollectedrepo/main
- test/src/625-loadfailureduringgarbagecollect/main
- test/src/629-reflogrecreation/main
Also: changes default threshold for manual gc to 3 days ago.
> Add gc command to cvmfs_server help text

- cvmfs/cvmfs_talk
- cvmfs/talk.cc
- cvmfs/talk.h
- test/src/615-externaldata/main
This is for devel, I will have a separate pull request for the cvmfs-2.3 branch
> Fix up cvmfs_talk external commands (CVM-981)

- cvmfs/mountpoint.cc
- test/src/615-externaldata/main
This is for the devel branch only, there will be a separate pull request for the cvmfs-2.3 branch.
> Prevent fallback proxies from interfering with external data (CVM-1058)

- cvmfs/cvmfs_talk
- cvmfs/talk.cc
- test/src/615-externaldata/main
See [CVM-1126](https://sft.its.cern.ch/jira/browse/CVM-1126)
> add cvmfs_talk external host switch

- cvmfs/cvmfs_talk
- cvmfs/talk.cc
- test/src/615-externaldata/main
> add cvmfs_talk external host switch -- cvmfs-2.3

- cvmfs/server/cvmfs_server_common.sh
- cvmfs/server/cvmfs_server_publish.sh
- cvmfs/server/cvmfs_server_util.sh
- test/src/534-interleavingpublishes/main
Also allow for the lock file to be empty.  See [CVM-1146](https://sft.its.cern.ch/jira/browse/CVM-1146).
> Change publishing to not ignore stale locks

- cvmfs/cvmfs_server
- test/src/534-interleavingpublishes/main
This is the backport of pr #1735 to cvmfs-2.3.  See [CVM-1146](https://sft.its.cern.ch/jira/browse/CVM-1146).
> Change publishing to not ignore locks -- cvmfs-2.3

- cvmfs/cvmfs_server
- test/src/584-interleavingsnapshot/main
Same as #1737 for cvmfs-2.3 branch.
> use common locking with snapshot and with gc on stratum1 - cvmfs-2.3

- cvmfs/server/cvmfs_server_common.sh
- cvmfs/server/cvmfs_server_gc.sh
- cvmfs/server/cvmfs_server_snapshot.sh
- cvmfs/server/cvmfs_server_util.sh
- test/src/584-interleavingsnapshot/main
See [CVM-1108](https://sft.its.cern.ch/jira/browse/CVM-1108)
> use common locking with snapshot and with gc on stratum1

- cvmfs/cvmfs_server
- test/src/621-snapshotall/main
> Avoid expanding command line repo wildcards too early (CVM-1151) - 2.3

- cvmfs/server/cvmfs_server_compat.sh
- cvmfs/server/cvmfs_server_migrate.sh
> Port CVM-1159 fix for cvmfs-2.3 to devel branch

- test/cloud_testing/platforms/slc5_x86_64_test.sh
- test/cloud_testing/platforms/slc6_x86_64_test.sh
- test/cloud_testing/platforms/ubuntu_x86_64_setup.sh
- test/migration_tests/001-hotpatch/main
- test/src/036-cacheoverload/main
- test/src/559-garbagecollectnamedtags/main
- test/src/584-interleavingsnapshot/main
- test/src/607-noapache/main
- test/src/625-loadfailureduringgarbagecollect/main
- test/src/636-autotagstimespan/main
- test/test_functions
> Fixes for integration tests

- cvmfs/server/cvmfs_server_publish.sh
- test/cloud_testing/platforms/ubuntu_x86_64_setup.sh
- test/src/004-davinci/main
- test/src/007-testjobs/main
- test/src/010-du/main
- test/src/567-mkfswithlegacykeys/main
- test/src/636-autotagstimespan/main
> Fix integration tests

- cvmfs/catalog_mgr_rw.cc
> Fix potential deadlock when uploading catalogs (CVM-1165)

- cvmfs/catalog_mgr_rw.cc
> Fix potential deadlock when uploading catalogs

- cvmfs/server/cvmfs_server_util.sh
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
Same as #1792 , this time on `devel`.
> Fix overlayfs check centos7 devel

- cvmfs/path_filters/dirtab.h
- cvmfs/path_filters/relaxed_path_filter.cc
- cvmfs/path_filters/relaxed_path_filter.h
- test/unittests/t_relaxed_path_filter.cc
> Fix dirtab parsing in cvmfs_preload -- devel

- ChangeLog
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
> Integration test fixes devel

- cvmfs/cache.proto
- cvmfs/cache_extern.cc
- cvmfs/cache_plugin/libcvmfs_cache.cc
- cvmfs/cache_plugin/libcvmfs_cache.h
- cvmfs/cache_tiered.cc
- cvmfs/cache_tiered.h
- cvmfs/mountpoint.cc
- test/src/070-tieredcache/main
- test/unittests/cache_plugin/t_cache_plugin.cc
- test/unittests/t_cache_extern.cc
- test/unittests/t_cache_tiered.cc
> Allow for read-only lower cache layer

- cvmfs/CMakeLists.txt
- externals/libgeoip/src/configureHook.sh
https://phsft-jenkins.cern.ch/view/CVMFS/job/CvmfsFullBuildDocker/387/
> Fixes CI CvmfsFullDockerBuild

- cvmfs/cvmfs_config
- packaging/rpm/cvmfs-universal.spec
> Work around autofs bug in CentOS 7 systemd unit

- cvmfs/server/cvmfs_server_migrate.sh
> Fix /etc/fstab migration from 2.1.20 for trailing whitespaces -- devel

- cvmfs/server/cvmfs_server_publish.sh
> Fix auto tag cleanup for very long tag lists -- devel

- cvmfs/swissknife_pull.cc
> Fix snapshot logging for large tag lists -- devel branch

- cvmfs/server/cvmfs_server_util.sh
- cvmfs/swissknife_check.cc
- cvmfs/swissknife_check.h
- cvmfs/swissknife_gc.cc
- cvmfs/swissknife_lsrepo.cc
- cvmfs/swissknife_pull.cc
- cvmfs/swissknife_pull.h
- test/src/638-stratum1keysdir/main
> Allow for keys directory in stratum 1 commands -- devel

- cvmfs/quota_posix.cc
- test/src/072-rmemptyfilesrebuild/main
- test/unittests/t_quota.cc
> Unlink empty files during cache db rebuild -- devel

- cvmfs/cvmfs.cc
- test/src/073-rawlink/main
> Fixes `sudo attr -Rg rawlink /cvmfs/path/to/link` -- devel

- cvmfs/server/cvmfs_server_publish.sh
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
- test/src/072-rmemptyfilesrebuild/main
- test/src/508-cvmfsdevelopment/main
- test/src/584-interleavingsnapshot/main
> Several smaller fixes after 2.3.4 integration test run

- cvmfs/server/cvmfs_server_abort.sh
- cvmfs/server/cvmfs_server_publish.sh
- cvmfs/server/cvmfs_server_transaction.sh
Renamed CVMFS_KEY to CVMFS_GATEWAY_KEY.
> A more descriptive and less ambiguous name for the gateway API var name

- ChangeLog
- packaging/rpm/cvmfs-universal.spec
> Install systemd/autofs patch configuration where necessary -- devel

- cvmfs/CMakeLists.txt
- cvmfs/catalog.h
- cvmfs/catalog_counters.cc
- cvmfs/catalog_counters.h
- cvmfs/catalog_mgr.h
- cvmfs/catalog_mgr_impl.h
- cvmfs/catalog_rw.cc
- cvmfs/directory_entry.h
- cvmfs/make_cvmfs_server.sh
- cvmfs/server/cvmfs_server_diff.sh
- cvmfs/server/cvmfs_server_util.sh
- cvmfs/swissknife_diff.cc
- cvmfs/swissknife_diff.h
- cvmfs/swissknife_main.cc
- test/src/641-diff/main
- test/unittests/t_catalog_counters.cc
- test/unittests/t_catalog_mgr.cc
- test/unittests/testutil.cc
- test/unittests/testutil.h
Adds a diff viewer to compare the contents of two snapshots.
> Add cvmfs_server diff command

- cvmfs/cvmfs_rsync
See [CVM-119](https://sft.its.cern.ch/jira/browse/CVM-1199)
> use rsync "perishable" feature instead of cvmfs_server list-catalogs

- packaging/debian/cvmfs/cvmfs-server.install
- packaging/rpm/cvmfs-universal.spec
See [CVM-1261](https://sft.its.cern.ch/jira/browse/CVM-1261)
> add cvmfs_receiver to packaging

- cvmfs/authz/authz_curl.cc
- cvmfs/duplex_ssl.h
- cvmfs/encrypt.cc
- cvmfs/loader.cc
- cvmfs/signature.cc
@bbockelm the changes in authz_curl.cc are untested at the moment, perhaps you'd like to take a second look.
> Fixes for OpenSSL 1.1 interface changes

- cvmfs/catalog_diff_tool_impl.h
This should have been part of PR #1870
> Fixing CPPLINT warning

- cvmfs/swissknife_graft.cc
- cvmfs/swissknife_graft.h
- test/src/020-emptyrepofailover/main
- test/src/615-externaldata/main
- test/src/620-pullmixedrepo/main
- test/src/624-chunkedexternalgraft/main
See [CVM-1291](https://sft.its.cern.ch/jira/browse/CVM-1291)
> change default graft size from 32 to 24 MB

- cvmfs/util/posix.cc
See [CVM-1304](https://sft.its.cern.ch/jira/browse/CVM-1304)
> change usage of getgrnam_r and getpwnam_r to follow man page API

- cvmfs/cvmfs_config
See [CVM-1300](https://sft.its.cern.ch/jira/browse/CVM-1300)
> eliminate shell errors when required config repo cannot be mounted

- test/src/569-nonzeroreturncode/main
I forgot to commit this change for pr #1863 before it got merged, please include right away
> update test for cvmfs_server resign -w instead of -n

- add-ons/check_cvmfs.sh
- cvmfs/cvmfs.cc
Comes with the new `ncleanup24` extended attribute.
> Add check for cache cleanup rate to nagios probe

- cvmfs/server/cvmfs_server_abort.sh
- cvmfs/server/cvmfs_server_common.sh
- cvmfs/server/cvmfs_server_mkfs.sh
- cvmfs/server/cvmfs_server_publish.sh
- cvmfs/server/cvmfs_server_rmfs.sh
- cvmfs/server/cvmfs_server_transaction.sh
- test/src/800-repository_services/main
Addressed [CVM-1326](https://sft.its.cern.ch/jira/browse/CVM-1326).
> Simplify set up of repositories on a release manager machine with GW upstream

- cvmfs/catalog.h
- cvmfs/swissknife_sync.cc
- test/src/612-setttl/main
See [CVM-1336](https://sft.its.cern.ch/jira/browse/CVM-1336).
A comment in this PR assumes that the PR for [CVM-992](https://sft.its.cern.ch/jira/browse/CVM-992) has been merged.
> Reduce default TTL to 4 minutes

- cvmfs/file_processing/async_reader.cc
- cvmfs/file_processing/async_reader.h
- cvmfs/upload_facility.h
There is more to do here... but not in this release
> Fix potential deadlock

- cvmfs/receiver/catalog_merge_tool.h
- cvmfs/receiver/catalog_merge_tool_impl.h
- cvmfs/receiver/commit_processor.cc
- cvmfs/receiver/params.cc
- cvmfs/receiver/reactor.cc
- cvmfs/server/cvmfs_server_publish.sh
- test/src/800-repository_services/main
A review of the code making up the `cvmfs_receiver application`:
* More error logging
* Fixing some bugs related to the acquisition of leases on repository subpaths
* Some new integration test cases for subpath leases
> Receiver review

- cvmfs/server/cvmfs_server_resign.sh
- test/src/569-nonzeroreturncode/main
See [CVM-1358](https://sft.its.cern.ch/jira/browse/CVM-1358)
Please commit to both devel and cvmfs-2.4 branches.
> do not do health check on resign

- cvmfs/server/cvmfs_server_migrate.sh
See [CVM-1357](https://sft.its.cern.ch/jira/browse/CVM-1357)
> ignore stderr in _is_generated_apache_conf

- cvmfs/swissknife.h
- cvmfs/swissknife_diff.cc
- cvmfs/swissknife_diff_tool.cc
- cvmfs/swissknife_diff_tool.h
- cvmfs/swissknife_main.cc
Trivial patch to display the size of the entries being added or removed as well as the names.
> Trivial patch to display file sizes in swissknife diff command

- ci/run_travis.sh
- cvmfs/CMakeLists.txt
- cvmfs/server/cvmfs_server_apache.sh
- cvmfs/server/cvmfs_server_compat.sh
- cvmfs/server/cvmfs_server_migrate.sh
- cvmfs/server/cvmfs_server_util.sh
- cvmfs/webapi/cvmfs_geo.py
- cvmfs/webapi/test_cvmfs_geo.py
- packaging/debian/cvmfs/cvmfs-server.install
- packaging/rpm/cvmfs-universal.spec
- test/src/614-geoservice/main
Replacement for #1949 against the cvmfs-2.4 branch.  See [CVM-1349](https://sft.its.cern.ch/jira/browse/CVM-1349).
> Cache geoapi DNS lookups in a threaded shared wsgi python interpreter

- cvmfs/receiver/commit_processor.cc
- cvmfs/receiver/payload_processor.cc
- cvmfs/receiver/payload_processor.h
- cvmfs/session_context.cc
- cvmfs/swissknife_lease_curl.cc
- cvmfs/swissknife_sync.cc
- test/unittests/t_payload_processor.cc
- test/unittests/t_reactor.cc
This addresses [CVM-1375](https://sft.its.cern.ch/jira/browse/CVM-1375).
In the process of debugging this JIRA issue, a series of race conditions and swallowed errors were fixed in the part of the code related to the gateway backend, while logging in this parts was improved.
> Fix gateway backend submission errors 

- cvmfs/server/cvmfs_server_util.sh
This is the same as #1994 only based on the cvmfs-2.4 branch.
> Expand XFS checks in cvmfs_server_util.sh

- cvmfs/server/cvmfs_server_apache.sh
See [CVM-1349](https://sft.its.cern.ch/jira/browse/CVM-1349)
> use AliasMatch instead of RewriteRule for webapi

- cvmfs/webapi/cvmfs_geo.py
- test/src/614-geoservice/main
See [CVM-1442](﻿﻿https://sft.its.cern.ch/jira/browse/CVM-1442)
> Have geoapi try $REMOTE_ADDR if $HTTP_X_FORWARDED_FOR has no geoinfo

- cvmfs/gateway_util.cc
- test/test_functions
Addresses [CVM-1444](https://sft.its.cern.ch/jira/browse/CVM-1444).
> Renaming gateway key type: "test" -> "plain_text"

- cvmfs/cvmfs.cc
- cvmfs/swissknife_diff.cc
- cvmfs/swissknife_diff.h
Also: Fix client crash if DNS roaming is turned off
> Allow for raw hashes being used in repository diff

- cvmfs/webapi/cvmfs_geo.py
- test/src/614-geoservice/main
See [CVM-1468](https://sft.its.cern.ch/jira/browse/CVM-1468)
> Add Cloudflare support to the geoapi

- cvmfs/download.cc
Addresses [CVM-1480](https://sft.its.cern.ch/jira/browse/CVM-1480).
> Fix large CPU time in cvmfs2 when network bandwidth is limited

- cvmfs/download.cc
Addresses [CVM-1482](https://sft.its.cern.ch/jira/browse/CVM-1482?filter=13271).
> Fix potential missed events in DownloadManager::MainDownload

- cvmfs/receiver/commit_processor.cc
- cvmfs/receiver/commit_processor.h
- cvmfs/receiver/payload_processor.cc
- cvmfs/receiver/payload_processor.h
- cvmfs/receiver/reactor.cc
- test/unittests/t_payload_processor.cc
- test/unittests/t_reactor.cc
Addresses [CVM-1540](https://sft.its.cern.ch/jira/browse/CVM-1540).
> Put cvmfs_receiver temp dirs under <SPOOLER_TEMP_DIR>/receiver

- cvmfs/session_context.cc
- cvmfs/session_context.h
- test/unittests/t_session_context.cc
Addresses [CVM-1555](https://sft.its.cern.ch/jira/browse/CVM-1555).
This fixes a potential deadlock in the `SessionContext` class, which was introduced in PR #2122.
> Fixes potential deadlock when uploading to repository gateway

- mount/domain.d/cern.ch.conf
- packaging/rpm/cvmfs-config-default.spec
See [CVM-1556](https://sft.its.cern.ch/jira/browse/CVM-1556)
> Use OSG aliases for U.S. stratum 1s in cern.ch.conf

- cvmfs/sync_item_tar.cc
- cvmfs/sync_union_tarball.cc
- test/src/654-tarball_ingest_special_files/main
With this pull request we manage Symslink, pipes and sockets
> Add support for symlinks inside tarballs

- cvmfs/directory_entry.h
- cvmfs/sync_item.cc
- cvmfs/sync_item.h
- cvmfs/sync_item_dummy.h
- cvmfs/sync_item_tar.cc
- cvmfs/sync_item_tar.h
- cvmfs/sync_union.cc
This PR supersedes #2139 
I made some mistake in git and it seems like the old one got entangled with different PR
The PR is very similar, we create a different Interface SubClass SyncItem from which SyncItemNative inheritance.
> Remove kItemTar

- test/common/catalog_test_tools.cc
- test/common/catalog_test_tools.h
- test/unittests/t_catalog_merge_tool.cc
- test/unittests/t_mountpoint.cc
Consolidation of catalog_test_tools and the repository created in `t_mountpoint`.
> Consolidation of catalog_test_tools and the repository created in t_mountpoint

- cvmfs/server/cvmfs_server_publish.sh
Addresses [CVM-1559](https://sft.its.cern.ch/jira/browse/CVM-1559).
> Fix tag name when publishing through gateway with CVMFS_AUTO_TAGS=false (CVM-1559)

- cvmfs/server/cvmfs_server_publish.sh
- test/src/804-repository_gateway_autotags/main
This is a duplicate of PR #2166 , which was made against the `devel` branch by mistake.
> Fix tag name when publishing through gateway with CVMFS_AUTO_TAGS=false

- cvmfs/server/cvmfs_server_ssl.sh
See [CVM-1604](https://sft.its.cern.ch/jira/browse/CVM-1604)
> Verify the signature made by masterkeycard

- cvmfs/server/cvmfs_server_common.sh
See [CVM-1598](https://sft.its.cern.ch/jira/browse/CVM-1598)
> Fix snapshot -t to override stale update lock

- cvmfs/statistics_database.cc
- cvmfs/statistics_database.h
- cvmfs/swissknife_main.cc
- test/src/660-store_publish_statistics/main
Changed `timestamp` column to `start_time`.
Added `finished_time` column.
> Add start/finished time in statistics database.

- cvmfs/statistics_database.cc
- test/src/660-store_publish_statistics/main
Added 'publish_id INTEGER PRIMARY KEY'.
See this [PR](https://github.com/cvmfs/cvmfs/pull/2187) .
> Added unique counter as primary key for publish_statistics

- cvmfs/server/cvmfs_server_merge_stats.sh
- test/src/660-store_publish_statistics/main
Now merge-stats tool:
- works with different tables.
- works with tables that have the first column a integer primary key (publish_statistics, gc_statistics)
> Improved merge-stats tool

- test/src/614-geoservice/main
See [CVM-1496](https://sft.its.cern.ch/jira/browse/CVM-1496)
> Fix geoservice integration test

- ChangeLog
- cvmfs/s3fanout.cc
- cvmfs/s3fanout.h
- cvmfs/upload_s3.cc
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
- test/cloud_testing/platforms/common.sh
- test/cloud_testing/platforms/fedora_setup.sh
- test/cloud_testing/platforms/ubuntu_setup.sh
- test/src/626-cacheexpiry/main
> Fix HTTP header integration test for S3 + content-type header fix

- cvmfs/server/cvmfs_server_apache.sh
- cvmfs/server/cvmfs_server_compat.sh
- cvmfs/server/cvmfs_server_migrate.sh
- cvmfs/server/cvmfs_server_util.sh
See [CVM-1655](https://sft.its.cern.ch/jira/browse/CVM-1655)
> Update apache config to ignore If-Modified-Since

- cvmfs/server/cvmfs_server_util.sh
- test/src/595-geoipdbupdate/main
See [CVM-1647](https://sft.its.cern.ch/jira/browse/CVM-1647)
> Restrict lazy downloads of geodb to once a day

- cvmfs/download.cc
- cvmfs/download.h
- cvmfs/object_fetcher.h
- cvmfs/swissknife_pull.cc
Replaces #2220.  See [CVM-1662](https://sft.its.cern.ch/jira/browse/CVM-1662).
> Log more details for host and proxy connection errors

- cvmfs/upload_local.cc
Now in this file is not necessary anymore to have the platform include.
Sorry about that!
> remove useless dependencies

- cvmfs/server/cvmfs_server_ingest.sh
- cvmfs/swissknife_ingest.cc
- cvmfs/swissknife_ingest.h
- test/src/806-repository_gateway_ingest/main
@radupopescu I am not sure I understand.
This PR seems to work but I never invoke 
```bash
__swissknife lease -a acquire -u $repo_services_url -k $gw_key_file -p $name"/"$base_dir
```
In a similar PR I invoke it, but it was like it was invoked twice... and so never completed...
> Lease on ingest

- ci/common.sh
- ci/cvmfs/deb.sh
- ci/cvmfs/pkg.sh
- ci/cvmfs/rpm.sh
- packaging/rpm/cvmfs-universal.spec
This PR add ducc to the standard building of cvmfs using the universal.spec
> Add ducc to the build procedure via rpm

- test/src/500-mkrepo/main
- test/src/654-tarball_ingest_special_files/main
I add few test cases to check that UTF-8 paths are supported.
The tests pass out of the box.
> Add test for UTF-8 file paths

- cvmfs/gateway_util.cc
- cvmfs/gateway_util.h
- test/unittests/CMakeLists.txt
- test/unittests/t_gateway_key_parser.cc
Addresses [CVM-1693](https://sft.its.cern.ch/jira/browse/CVM-1693).
> Make gateway key parser more robust

- cvmfs/swissknife_scrub.cc
- test/src/800-repository_gateway/main
- test/src/801-repository_gateway_slow/main
- test/src/802-repository_gateway_nested_catalogs/main
- test/src/803-repository_gateway_large_files/main
Addresses [CVM-1704](https://sft.its.cern.ch/jira/browse/CVM-1704).
> Whitelist data/txn/receiver in swissknife scrub

- cvmfs/manifest.cc
- cvmfs/manifest.h
- cvmfs/signing_tool.cc
- cvmfs/swissknife_check.cc
- test/src/805-repository_gateway_reflog/main
Same as #2352 but reopened against the cvmfs-2.6 branch.
> Include reflog checksum in the repository manifest

- packaging/rpm/cvmfs-universal.spec
[CVM-1744](https://sft.its.cern.ch/jira/browse/CVM-1744)
> build fuse3 on rhel >= 6

- ducc/lib/image.go
Reopening #2368 on the correct branch.
> Add --force flag and $PATH to singularity build on DUCC

- cvmfs/CMakeLists.txt
- cvmfs/webapi/cvmfs_geo.py
- cvmfs/webapi/cvmfs_globals.py
- cvmfs/webapi/test_cvmfs_geo.py
- test/src/614-geoservice/main
See [CVM-1739](https://sft.its.cern.ch/jira/browse/CVM-1739).
Also move stratum1 used in the service test back from unl to fnal.
> Reload geodb after a new one is downloaded

- cvmfs/CMakeLists.txt
- cvmfs/webapi/cvmfs_geo.py
- cvmfs/webapi/cvmfs_globals.py
- cvmfs/webapi/test_cvmfs_geo.py
- test/src/614-geoservice/main
Redo of #2364 against 2.6 branch.
>  Reload geodb after a new one is downloaded (for 2.6 branch)

- cvmfs/catalog_mgr_client.cc
Same as #2360, but on branch cvmfs-2.6.
> fix root catalog reload logic

- cvmfs/webapi/cvmfs_geo.py
- test/src/614-geoservice/main
See [CVM-1774](https://sft.its.cern.ch/jira/browse/CVM-1774)
> Fix cloudflare geo api with proxy name

- cvmfs/server/cvmfs_server_ssl.sh
Addresses [CVM-1746](https://sft.its.cern.ch/jira/browse/CVM-1746).
> Use mode 0400 for gateway keys in cvmfs_server import_keychain

- cvmfs/webapi/cvmfs_api.py
- cvmfs/webapi/cvmfs_geo.py
- test/src/614-geoservice/main
See [CVM-1777](https://sft.its.cern.ch/jira/browse/CVM-1777)
> Fix geo api locking

- cvmfs/server/cvmfs_server_masterkeycard.sh
See [CVM-1788](https://sft.its.cern.ch/jira/browse/CVM-1788)
> Use pkcs11-tool for masterkeycard signing

- externals/c-ares/src/configureHook.sh
> Fix syntax error in c-ares configureHook.sh script

- externals/pacparser/src/makeHook.sh
> Fix syntax error in pacparser makeHook.sh script

- cvmfs/util/algorithm.cc
- cvmfs/util/algorithm.h
- test/unittests/t_util.cc
Hello, Jakob!
Please, review the pull request and let me know your comments.
Regards,
Shahnur
> Added log2 histogram data structure and unit tests

- cvmfs/cvmfs.cc
- cvmfs/mountpoint.cc
- cvmfs/mountpoint.h
- cvmfs/talk.cc
- cvmfs/util/algorithm.cc
- cvmfs/util/algorithm.h
- test/unittests/t_util.cc
Hello, Jakob.
Please, review the code and let me know your feedback! :) 
Now we can measure the latencies of the CVMFS calls and visualize their distribution via cvmfs_talk comand. 
Many thanks,
Shahnur
> Feature syscall latency

- mount/domain.d/egi.eu.conf
- mount/domain.d/opensciencegrid.org.conf
- packaging/rpm/cvmfs-config-default.spec
I want to get this merged before I forget but there's no hurry to release a new cvmfs-config-default package version.  It can wait for another reason.
> change klei.nikhef.nl to cvmfs01.nikhef.nl

- cvmfs/swissknife_filestats.cc
Instead of opening a transaction for every processed catalog, do the whole processing in one transaction in output database. This speeds up the command significantly (~10x).
> Swissknife filestats speedup: global transaction for output db

- cvmfs/catalog.h
- cvmfs/catalog_mgr_rw.cc
- cvmfs/catalog_mgr_rw.h
- cvmfs/catalog_rw.cc
- cvmfs/catalog_rw.h
- cvmfs/catalog_sql.cc
- cvmfs/catalog_sql.h
- cvmfs/catalog_virtual.cc
- cvmfs/cvmfs.cc
- cvmfs/loader.cc
- cvmfs/mountpoint.cc
- cvmfs/mountpoint.h
- cvmfs/receiver/catalog_merge_tool_impl.h
- cvmfs/swissknife_check.cc
- cvmfs/sync_mediator.cc
- cvmfs/sync_mediator.h
- test/cloud_testing/platforms/centos7_x86_64_s3_test.sh
- test/cloud_testing/platforms/centos7_x86_64_setup.sh
- test/cloud_testing/platforms/centos7_x86_64_test.sh
- test/cloud_testing/platforms/fedora_setup.sh
- test/cloud_testing/platforms/slc6_x86_64-gcov_setup.sh
- test/cloud_testing/platforms/slc6_x86_64_s3_test.sh
- test/cloud_testing/platforms/slc6_x86_64_setup.sh
- test/cloud_testing/platforms/slc6_x86_64_test.sh
- test/cloud_testing/platforms/ubuntu_setup.sh
- test/cloud_testing/platforms/ubuntu_test.sh
- test/common/catalog_test_tools.cc
- test/src/585-xattrs/main
- test/src/673-acl/main
As a precondition, the PR enables extended attribute support for directories.
> Enables POSIX ACL support on fuse3 platforms

- cvmfs/platform_linux.h
- cvmfs/platform_osx.h
- cvmfs/receiver/commit_processor.cc
- cvmfs/util/posix.cc
- cvmfs/util/posix.h
Not sure if this refactor is worth to do.
Feel free to merge or discard
> Use millisecond precision for generic tags in gateway

- ducc/lib/cvmfs.go
Address [CVM-1817](https://sft.its.cern.ch/jira/projects/CVM/issues/CVM-1817)
> Use relative symbolic links in DUCC

- test/cloud_testing/platforms/fedora_test.sh
- test/cloud_testing/platforms/ubuntu_s3_test.sh
- test/cloud_testing/platforms/ubuntu_test.sh
Jakob, these are the test we have excluded to work with fuse3.
> Disable fuse3 tests

- cvmfs/wpad.cc
See [CVM-1818](https://sft.its.cern.ch/jira/browse/CVM-1818)
> Delete empty "auto" from proxy list

- cvmfs/swissknife_pull.cc
- cvmfs/util/exception.h
Sup #2416 while keeping the benefits of being easy to integrate in the old code.
Just replace calls to Log + Abort to a call to the PANIC macro.
> add function to panic and either log + abort or thrown an exception

- packaging/mac/resources/conclusion.rtf
- packaging/mac/resources/welcome.rtf
> Add reboot info catalina

- packaging/mac/resources/conclusion.rtf
- packaging/mac/resources/welcome.rtf
I add a note, twice in the welcome and in the conclusion about the necessity of rebooting the system.
The note is:
```
Please note that from MacOS 10.15 Catalina is necessary to reboot your system after the installation in order to create the /cvmfs directory.
```
> Add note about rebooting the system after installation in Catalina

- cvmfs/notify/cmd_sub.cc
- cvmfs/notify/publisher_http.h
- cvmfs/publish/settings.h
Remove death code.
Everything seems to compile just fine without.
> remove death code

- ducc/cmd/convert.go
- ducc/cmd/convert_singularity_image.go
- ducc/cmd/loop.go
- ducc/lib/conversion.go
- test/src/401-ducc-convert_singularity/main
Also separate ConvertWish into ConvertWishSingularity and ConvertWishDocker
> DUCC: add convert-singularity-image command

- cvmfs/CMakeLists.txt
- cvmfs/catalog_diff_tool_impl.h
- cvmfs/ingestion/task_read.cc
- cvmfs/swissknife_pull.cc
- cvmfs/swissknife_reflog.cc
- cvmfs/util/exception.cc
- cvmfs/util/exception.h
- cvmfs/util/posix.cc
- test/quickcheck/CMakeLists.txt
- test/quickcheck/qc_catalog_merge_tool.cc
- test/unittests/CMakeLists.txt
- test/unittests/t_panic.cc
Follow up from #2424 
I believe is wiser to accept also the mask, this will allow us to use the PANIC more widely in the codebase.
> iterate over PANIC design and ergonomics

- cvmfs/server/cvmfs_server_coda.sh
- cvmfs/server/cvmfs_server_util.sh
See [CVM-1833](https://sft.its.cern.ch/jira/browse/CVM-1833)
> Change geodb update to use license key

- cvmfs/server/cvmfs_server_util.sh
- test/src/595-geoipdbupdate/main
See [CVM-1833](https://sft.its.cern.ch/jira/browse/CVM-1833).  Makes most sense to merge after #2469.
> add CVMFS_GEO_DB_FILE

- test/src/595-geoipdbupdate/main
See discussion in [CVM-1833](https://sft.its.cern.ch/jira/browse/CVM-1833)
> Let geoip update test pass with a preloaded geo db file and no license key

- cvmfs/CMakeLists.txt
- cvmfs/download.cc
- cvmfs/download.h
- cvmfs/publish/cmd_info.cc
- cvmfs/publish/cmd_info.h
- cvmfs/publish/repository.cc
- cvmfs/publish/repository.h
- cvmfs/publish/settings.cc
- cvmfs/publish/settings.h
- cvmfs/server/cvmfs_server_info.sh
- cvmfs/whitelist.cc
- cvmfs/whitelist.h
- test/unittests/CMakeLists.txt
- test/unittests/publish/t_repository.cc
Move the `cvmfs_server info` command to the new code base, including some minor adjustments to libcvmfs_server
> [publish] implement cvmfs_server info command

- cvmfs/statistics_database.cc
- test/unittests/t_statistics_sql.cc
Add missing semicolon to StatisticsDatabase upgrade code
T_StatisticsSql: fix test name to SchemaMigration1To3
> StatisticsDatabase: minor bugfix

- packaging/rpm/cvmfs-universal.spec
This rm in the rpm spec was causing rpm builds to fail.
> Fix rpm build

- cvmfs/monitor.cc
- test/common/mock_services/http_400.py
- test/common/mock_services/http_server.py
- test/src/030-missingrootcatalog/main
- test/src/089-external_cache_plugin/main
- test/test_functions
- python related fixes for integration tests
- 089 external cache manager test fix
> Fedora31 integration test fixes

- cvmfs/directory_entry.h
- cvmfs/ingestion/ingestion_source.h
- cvmfs/sync_item_dummy.h
- cvmfs/sync_union_tarball.cc
- test/src/653-tarball_ingest_from_stdin/main
> Fix catalog cvmfs ingest

- ducc/lib/image.go
Add authentication for downloading private images using singularity
> add authentication to singularity

- cvmfs/receiver/lease_path_util.cc
- cvmfs/server/cvmfs_server_transaction.sh
- test/src/800-repository_gateway/main
- test/src/807-nested_new_directories_gateway_ingest/main
> Fix lease on 2.7

- cvmfs/server/cvmfs_server_add_replica.sh
See [CVM-1851](https://sft.its.cern.ch/jira/browse/CVM-1851)
> Avoid leaving bad state when geodb update fails during add-replica

- cvmfs/server/cvmfs_server_add_replica.sh
See [CVM-1850](https://sft.its.cern.ch/jira/browse/CVM-1850)
> Expand listed options for non-root geodb maintenance

- cvmfs/cvmfs_talk.cc
- cvmfs/mountpoint.h
- cvmfs/talk.cc
- cvmfs/talk.h
- cvmfs/util/algorithm.cc
- cvmfs/util/algorithm.h
- test/unittests/t_util.cc
> Latency 2.7

- ducc/lib/conversion.go
- ducc/lib/image.go
- ducc/lib/recipe.go
Fix for allowing to ingest private images.
The fix is already in production and it is behaving well.
> fix authentication for downloading images

- cvmfs/server/cvmfs_server_transaction.sh
- test/src/808-lease_failure/main
- test/src/809-lease_failure/main
- test/test_functions
> Change cvmfs_server transaction return code

- cvmfs/make_cvmfs_server.sh
- cvmfs/server/cvmfs_server_eliminate_bulk_hashes.sh
- cvmfs/server/cvmfs_server_util.sh
- cvmfs/swissknife_migrate.cc
- cvmfs/swissknife_migrate.h
- test/src/677-removebulkhashes/main
The command removes bulk hashes from files that also exist in chunked form.
> Add a hidden `cvmfs_server eliminate-bulk-hashes` command

- ducc/lib/image.go
Minor fix, but it caused a fail build on unpacked.
I will merge it tomorrow.
> fix defer in case of http error

- ducc/lib/image.go
- ducc/lib/image_test.go
- ducc/lib/parse.go
- ducc/lib/parse_test.go
- ducc/lib/recipe.go
> fix cmd string and add support for missing protocol during parse

- test/cloud_testing/platforms/centos8_x86_64-FUSE3_setup.sh
- test/cloud_testing/platforms/centos8_x86_64-FUSE3_test.sh
- test/cloud_testing/platforms/centos8_x86_64_setup.sh
- test/cloud_testing/platforms/centos8_x86_64_test.sh
Jenkins cloudtesting job: https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/640/CVMFS_PLATFORM=el8,CVMFS_PLATFORM_CONFIG=x86_64,label=trampoline/
> Add centos8 cloudtesting scripts

- cmake/Modules/cvmfs_compiler.cmake
Backport the changes from @beojan (many thanks!) to the 2.7 branch.
> Gcc10 backport to cvmfs 2.7

- cvmfs/publish/cmd_transaction.cc
- cvmfs/publish/except.h
- cvmfs/publish/settings.cc
- cvmfs/publish/settings.h
I tried to address the issue of that Valetin brought up today.
I am definitely not sure if this is enough.
> Manage case when we don't find the server.conf configuratio file.
